//! ESP32-C3 / esp-hal 0.22 code generator.
//!
//! Generates and splices the GEN_BEGIN … GEN_END block for ESP32-C3 projects.
//! Structure of a generated `src/main.rs`:
//!
//! ```text
//! // Auto-generated by Embedded IDE
//! // MCU: ESP32-C3 | HAL: esp-hal 0.22
//!
//! #![no_std]
//! #![no_main]
//!
//! // <<< GENERATED BEGIN — do not edit between these markers >>>
//! use esp_hal::gpio::{Input, Level, Output, Pull};
//!
//! #[esp_hal::main]
//! fn main() -> ! {
//!     let peripherals = esp_hal::init(esp_hal::Config::default());
//!
//!     // ── GPIO ──
//!     let mut gpio2 = Output::new(peripherals.GPIO2, Level::Low); // GPIO Output
//!
//! // <<< GENERATED END >>>
//!     loop {
//!         // Your main loop code here.
//!     }
//! }
//! ```

use super::codegen::{GEN_BEGIN, GEN_END};
use super::pin_module::pin::Pin;
use super::pin_module::pin_function::PinFunction;
use std::collections::{BTreeMap, BTreeSet};

// ── User tail — closes fn main() ─────────────────────────────────────────────

const USER_TAIL: &str = "    loop {\n        // Your main loop code here.\n    }\n}\n";

// ── Public entry points ───────────────────────────────────────────────────────

/// Build a brand-new `src/main.rs` for an ESP32-C3 project.
/// Called when the MCU type is first selected or the project is reset.
pub fn fresh_esp32c3_main_rs(pins: &[&Pin]) -> String {
    let section = make_gen_section(pins);
    format!("{}{section}\n{USER_TAIL}", invariant_header())
}

/// Replace only the GEN block inside `existing`, preserving the user's loop body.
/// If markers are not found, rebuilds from scratch.
pub fn update_esp32c3_main_rs(existing: &str, pins: &[&Pin]) -> String {
    let new_section = make_gen_section(pins);
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        // Strip ALL leading newlines after GEN_END, then re-add exactly one
        // blank line so splice is idempotent (same as the STM32 path in codegen.rs).
        let after = existing[end..].trim_start_matches('\n');
        format!("{}{new_section}\n{after}", &existing[..begin])
    } else {
        // No markers — rebuild from scratch.
        format!("{}{new_section}\n{USER_TAIL}", invariant_header())
    }
}

// ── Invariant file header ─────────────────────────────────────────────────────
//
// Written once on project creation; never touched during pin-config updates.

fn invariant_header() -> &'static str {
    "// Auto-generated by Embedded IDE\n\
     // MCU: ESP32-C3 | HAL: esp-hal 0.22\n\n\
     #![no_std]\n\
     #![no_main]\n\n"
}

// ── Generated section builder ─────────────────────────────────────────────────

fn make_gen_section(pins: &[&Pin]) -> String {
    let configured: Vec<&Pin> = pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .copied()
        .collect();

    if configured.is_empty() {
        return make_default_gen_section();
    }

    // ── Feature flags ────────────────────────────────────────────────────────
    let has_output = configured.iter().any(|p| p.selected_function == PinFunction::GpioOutput);
    let has_input  = configured.iter().any(|p| p.selected_function == PinFunction::GpioInput);
    let has_adc    = configured.iter().any(|p| matches!(p.selected_function, PinFunction::AdcChannel { .. }));
    let has_uart   = configured.iter().any(|p| matches!(
        p.selected_function,
        PinFunction::UsartTx(_) | PinFunction::UsartRx(_)
    ));
    let has_spi    = configured.iter().any(|p| matches!(
        p.selected_function,
        PinFunction::SpiSck(_) | PinFunction::SpiMosi(_)
            | PinFunction::SpiMiso(_) | PinFunction::SpiNss(_)
    ));
    let has_i2c    = configured.iter().any(|p| matches!(
        p.selected_function,
        PinFunction::I2cScl(_) | PinFunction::I2cSda(_)
    ));
    let has_twai   = configured.iter().any(|p| matches!(
        p.selected_function,
        PinFunction::CanTx | PinFunction::CanRx
    ));
    let has_usb    = configured.iter().any(|p| matches!(
        p.selected_function,
        PinFunction::UsbDm | PinFunction::UsbDp
    ));

    // ── use block ─────────────────────────────────────────────────────────────
    let use_block = build_use_block(has_output, has_input, has_adc, has_uart, has_spi, has_i2c);

    // ── fn main() body ────────────────────────────────────────────────────────
    let mut body = String::new();
    body.push_str("    let peripherals = esp_hal::init(esp_hal::Config::default());\n");

    // ── GPIO Output / Input ───────────────────────────────────────────────────
    let outputs: Vec<&Pin> = configured.iter()
        .filter(|p| p.selected_function == PinFunction::GpioOutput)
        .copied().collect();
    let inputs: Vec<&Pin> = configured.iter()
        .filter(|p| p.selected_function == PinFunction::GpioInput)
        .copied().collect();

    if !outputs.is_empty() || !inputs.is_empty() {
        body.push('\n');
        body.push_str("    // ── GPIO ──\n");
        for p in &outputs {
            body.push_str(&format!(
                "    let mut {var} = Output::new(peripherals.{gpio}, Level::Low); // GPIO Output\n",
                var  = pin_var(&p.name),
                gpio = p.name,
            ));
        }
        for p in &inputs {
            body.push_str(&format!(
                "    let {var} = Input::new(peripherals.{gpio}, Pull::None); // GPIO Input\n",
                var  = pin_var(&p.name),
                gpio = p.name,
            ));
        }
    }

    // ── ADC — grouped by ADC instance ────────────────────────────────────────
    if has_adc {
        let mut adc_pins: BTreeMap<u8, Vec<&Pin>> = BTreeMap::new();
        for p in configured.iter()
            .filter(|p| matches!(p.selected_function, PinFunction::AdcChannel { .. }))
        {
            if let PinFunction::AdcChannel { adc, .. } = p.selected_function {
                adc_pins.entry(adc).or_default().push(p);
            }
        }

        for (adc_n, pin_list) in &adc_pins {
            body.push('\n');
            body.push_str(&format!("    // ── ADC{adc_n} ──\n"));
            body.push_str(&format!("    let mut adc{adc_n}_config = AdcConfig::new();\n"));
            for p in pin_list {
                if let PinFunction::AdcChannel { channel, .. } = p.selected_function {
                    body.push_str(&format!(
                        "    let mut {var}_adc = adc{adc_n}_config\
                         .enable_pin(peripherals.{gpio}, Attenuation::Db11); // ADC{adc_n} IN{channel}\n",
                        var  = pin_var(&p.name),
                        gpio = p.name,
                    ));
                }
            }
            body.push_str(&format!(
                "    let mut _adc{adc_n} = Adc::new(peripherals.ADC{adc_n}, adc{adc_n}_config);\n"
            ));
        }
    }

    // ── UART — grouped by peripheral instance ────────────────────────────────
    if has_uart {
        let mut uart_tx: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut uart_rx: BTreeMap<u8, &Pin> = BTreeMap::new();
        for p in configured.iter() {
            match p.selected_function {
                PinFunction::UsartTx(n) => { uart_tx.insert(n, p); }
                PinFunction::UsartRx(n) => { uart_rx.insert(n, p); }
                _ => {}
            }
        }
        let instances: BTreeSet<u8> = uart_tx.keys().chain(uart_rx.keys()).copied().collect();
        for n in instances {
            body.push('\n');
            body.push_str(&format!("    // ── UART{n} ──\n"));
            let rx_part = uart_rx.get(&n)
                .map(|p| format!("\n        .with_rx(peripherals.{})", p.name))
                .unwrap_or_default();
            let tx_part = uart_tx.get(&n)
                .map(|p| format!("\n        .with_tx(peripherals.{})", p.name))
                .unwrap_or_default();
            body.push_str(&format!(
                "    let mut _uart{n} = Uart::new(peripherals.UART{n}, UartConfig::default()){rx_part}{tx_part};\n"
            ));
        }
    }

    // ── SPI — grouped by peripheral instance ─────────────────────────────────
    if has_spi {
        let mut spi_sck:  BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut spi_mosi: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut spi_miso: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut spi_nss:  BTreeMap<u8, &Pin> = BTreeMap::new();
        for p in configured.iter() {
            match p.selected_function {
                PinFunction::SpiSck(n)  => { spi_sck.insert(n, p); }
                PinFunction::SpiMosi(n) => { spi_mosi.insert(n, p); }
                PinFunction::SpiMiso(n) => { spi_miso.insert(n, p); }
                PinFunction::SpiNss(n)  => { spi_nss.insert(n, p); }
                _ => {}
            }
        }
        let instances: BTreeSet<u8> = spi_sck.keys()
            .chain(spi_mosi.keys()).chain(spi_miso.keys()).chain(spi_nss.keys())
            .copied().collect();
        for n in instances {
            body.push('\n');
            body.push_str(&format!("    // ── SPI{n} ──\n"));
            let sck_part  = spi_sck.get(&n)
                .map(|p| format!("\n        .with_sck(peripherals.{})",  p.name))
                .unwrap_or_default();
            let mosi_part = spi_mosi.get(&n)
                .map(|p| format!("\n        .with_mosi(peripherals.{})", p.name))
                .unwrap_or_default();
            let miso_part = spi_miso.get(&n)
                .map(|p| format!("\n        .with_miso(peripherals.{})", p.name))
                .unwrap_or_default();
            let nss_part  = spi_nss.get(&n)
                .map(|p| format!("\n        .with_cs(peripherals.{})",   p.name))
                .unwrap_or_default();
            body.push_str(&format!(
                "    let mut _spi{n} = Spi::new(peripherals.SPI{n}, SpiConfig::default())\
                 {sck_part}{mosi_part}{miso_part}{nss_part};\n"
            ));
        }
    }

    // ── I2C — grouped by peripheral instance ─────────────────────────────────
    if has_i2c {
        let mut i2c_scl: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut i2c_sda: BTreeMap<u8, &Pin> = BTreeMap::new();
        for p in configured.iter() {
            match p.selected_function {
                PinFunction::I2cScl(n) => { i2c_scl.insert(n, p); }
                PinFunction::I2cSda(n) => { i2c_sda.insert(n, p); }
                _ => {}
            }
        }
        let instances: BTreeSet<u8> = i2c_scl.keys().chain(i2c_sda.keys()).copied().collect();
        for n in instances {
            body.push('\n');
            body.push_str(&format!("    // ── I2C{n} ──\n"));
            let scl_part = i2c_scl.get(&n)
                .map(|p| format!("\n        .with_scl(peripherals.{})", p.name))
                .unwrap_or_default();
            let sda_part = i2c_sda.get(&n)
                .map(|p| format!("\n        .with_sda(peripherals.{})", p.name))
                .unwrap_or_default();
            body.push_str(&format!(
                "    let mut _i2c{n} = I2c::new(peripherals.I2C{n}, I2cConfig::default())\
                 {scl_part}{sda_part};\n"
            ));
        }
    }

    // ── TWAI (CAN-compatible) — comment only ─────────────────────────────────
    if has_twai {
        let twai_tx = configured.iter().find(|p| p.selected_function == PinFunction::CanTx);
        let twai_rx = configured.iter().find(|p| p.selected_function == PinFunction::CanRx);
        body.push('\n');
        body.push_str("    // ── TWAI (CAN) — add esp-hal twai feature to Cargo.toml ──\n");
        if let Some(tx) = twai_tx {
            body.push_str(&format!("    // TX: peripherals.{}\n", tx.name));
        }
        if let Some(rx) = twai_rx {
            body.push_str(&format!("    // RX: peripherals.{}\n", rx.name));
        }
    }

    // ── USB — comment only (hardware-fixed on GPIO18/GPIO19) ─────────────────
    if has_usb {
        body.push('\n');
        body.push_str(
            "    // ── USB — configured automatically by the USB peripheral ──\n"
        );
    }

    // Blank line before GEN_END
    body.push('\n');

    format!(
        "{GEN_BEGIN}\n\
         {use_block}\
         #[esp_hal::main]\n\
         fn main() -> ! {{\n\
         {body}\
         {GEN_END}\n"
    )
}

// ── Default generated section (no pins configured yet) ────────────────────────

fn make_default_gen_section() -> String {
    format!(
        "{GEN_BEGIN}\n\
         // MCU: ESP32-C3\n\
         use esp_hal::prelude::*;\n\n\
         #[esp_hal::main]\n\
         fn main() -> ! {{\n\
             let _peripherals = esp_hal::init(esp_hal::Config::default());\n\n\
             // Select pins in the MCU Configurator to generate code here.\n\
         {GEN_END}\n"
    )
}

// ── use block builder ─────────────────────────────────────────────────────────

fn build_use_block(
    has_output: bool,
    has_input:  bool,
    has_adc:    bool,
    has_uart:   bool,
    has_spi:    bool,
    has_i2c:    bool,
) -> String {
    let mut lines: Vec<String> = Vec::new();

    // gpio — collect needed types alphabetically via BTreeSet
    let mut gpio_types: BTreeSet<&str> = BTreeSet::new();
    if has_output {
        gpio_types.insert("Level");
        gpio_types.insert("Output");
    }
    if has_input {
        gpio_types.insert("Input");
        gpio_types.insert("Pull");
    }
    if !gpio_types.is_empty() {
        let types = gpio_types.iter().copied().collect::<Vec<_>>().join(", ");
        lines.push(format!("use esp_hal::gpio::{{{types}}};"));
    }

    if has_adc {
        lines.push("use esp_hal::analog::adc::{Adc, AdcConfig, Attenuation};".into());
    }
    if has_uart {
        lines.push("use esp_hal::uart::{Uart, config::Config as UartConfig};".into());
    }
    if has_spi {
        lines.push("use esp_hal::spi::master::{Config as SpiConfig, Spi};".into());
    }
    if has_i2c {
        lines.push("use esp_hal::i2c::master::{Config as I2cConfig, I2c};".into());
    }

    if lines.is_empty() {
        // Fallback — should only happen if only USB / TWAI are selected
        return "use esp_hal::prelude::*;\n\n".into();
    }

    let mut block = lines.join("\n");
    block.push_str("\n\n");
    block
}

// ── Pin name → Rust variable name ────────────────────────────────────────────

/// Converts an ESP32 pin name to a snake_case variable name.
///
/// Examples:
/// - `"GPIO2"`  → `"gpio2"`
/// - `"GPIO20"` → `"gpio20"`
fn pin_var(pin_name: &str) -> String {
    pin_name.to_ascii_lowercase()
}
