//! ESP32-C3 / esp-hal 0.22 code generator.
//!
//! Generates and splices the GEN_BEGIN … GEN_END block for ESP32-C3 projects.
//! Structure of a generated `src/main.rs`:
//!
//! ```text
//! // Auto-generated by Embedded IDE
//! // MCU: ESP32-C3 | HAL: esp-hal 0.22
//!
//! #![no_std]
//! #![no_main]
//!
//! // <<< GENERATED BEGIN — do not edit between these markers >>>
//! use esp_hal::gpio::{Input, Level, Output, Pull};
//!
//! #[main]
//! fn main() -> ! {
//!     let peripherals = esp_hal::init(esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::max()));
//!
//!     // ── GPIO ──
//!     let mut gpio2 = Output::new(peripherals.GPIO2, Level::Low); // GPIO Output
//!
//! // <<< GENERATED END >>>
//!     loop {
//!         // Your main loop code here.
//!     }
//! }
//! ```
//!
//! The [`Runtime::Async`] path emits the same body from the same builder — only
//! the entry point differs (`#[esp_rtos::main] async fn main(Spawner)` plus the
//! `esp_rtos::start(...)` scheduler hand-off). See [`EspRuntime`].
//!
//! [`Runtime::Async`]: crate::panels::mcu_module::mcu::Runtime

use super::clock::ClockConfig;
use super::clock::graph::evaluate;
use super::codegen::{GEN_BEGIN, GEN_END, mcu_id_marker_line, pin_binding, sanitize_label};
use super::modules::{I2cModuleConfig, SpiModuleConfig, UsartModuleConfig};
use super::pins::logic::pin::Pin;
use super::pins::logic::pin_function::PinFunction;
use std::collections::{BTreeMap, BTreeSet};

// ── User tail — closes fn main() ─────────────────────────────────────────────

const USER_TAIL: &str = "    loop {\n        // Your main loop code here.\n    }\n}\n";

/// First link of every esp-hal bus builder chain: `Uart::new` / `Spi::new` /
/// `I2c::new` all return `Result<Self, ConfigError>` on esp-hal 1.1, so the
/// `.with_xxx(...)` links below them do not exist until it is unwrapped.
///
/// A bad config here is a programming error the IDE wrote (the values come from
/// the Virtual Module UI, which range-limits them), not a runtime condition the
/// firmware could handle — the same reason the STM32 backend emits
/// `pac::Peripherals::take().unwrap()`.
const UNWRAP_CFG: &str = "\n        .unwrap()";

// ── Runtime (entry point) ────────────────────────────────────────────────────

/// Which entry point the generated `main` opens — the only structural difference
/// between the two ESP paths. Everything below the entry (clock, GPIO, UART,
/// SPI, I2C bindings) is byte-for-byte identical: they are the same esp-hal
/// drivers, so one builder serves both.
///
/// Async is `esp-rtos`, NOT `esp-hal-embassy`. The latter is pinned to esp-hal
/// 1.0 by the private `__esp_hal_embassy` feature, which esp-hal 1.1 (what the
/// project template pins) no longer has — the dependency resolution fails before
/// anything compiles. `esp-rtos` is the same maintainers' replacement and drives
/// the very same `embassy-executor` / `embassy-time`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum EspRuntime {
    /// `#[esp_hal::main] fn main() -> !`
    Blocking,
    /// `#[esp_rtos::main] async fn main(_spawner: Spawner)`, with the scheduler
    /// started from TIMG0 + software interrupt 0.
    Async,
}

impl EspRuntime {
    /// The attribute + `fn` signature line(s) that open `main`, ending in `{\n`.
    fn entry(self) -> &'static str {
        match self {
            Self::Blocking => "#[esp_hal::main]\nfn main() -> ! {\n",
            Self::Async => "#[esp_rtos::main]\nasync fn main(_spawner: Spawner) {\n",
        }
    }

    /// The lines that hand the timer to the scheduler, emitted right after
    /// `esp_hal::init` — empty on the blocking path.
    ///
    /// TIMG0 is the timer the esp-rtos docs (and `esp-generate`) use; taking it
    /// here means user code cannot also claim `peripherals.TIMG0`, which is the
    /// normal trade for having `embassy_time::Timer` work at all.
    fn start_block(self) -> &'static str {
        match self {
            Self::Blocking => "",
            Self::Async => {
                "\n    // ── Async runtime (esp-rtos drives the embassy executor) ──\n\
                 \x20   let timg0 = TimerGroup::new(peripherals.TIMG0);\n\
                 \x20   let sw_int = SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);\n\
                 \x20   esp_rtos::start(timg0.timer0, sw_int.software_interrupt0);\n"
            }
        }
    }

    /// The extra `use` items the async entry + scheduler start need.
    fn use_lines(self) -> &'static [&'static str] {
        match self {
            Self::Blocking => &[],
            Self::Async => &[
                "use embassy_executor::Spawner;",
                "use esp_hal::interrupt::software::SoftwareInterruptControl;",
                "use esp_hal::timer::timg::TimerGroup;",
            ],
        }
    }
}

// ── Clock config → esp-hal `CpuClock` ─────────────────────────────────────────

/// The `esp_hal::init(...)` line, with the CPU clock taken from the clock graph.
///
/// esp-hal exposes only `CpuClock::_80MHz` / `_160MHz` for the ESP32-C3, so the
/// graph's `cpu` node (160 MHz on the ÷3 divider, 80 MHz on ÷6) maps to those.
/// When the chip has no graph clock the line falls back to `CpuClock::max()`,
/// matching the previous hardcoded default.
fn esp_init_line(clock: &ClockConfig) -> String {
    let cpu = match clock {
        ClockConfig::Graph(gc) => {
            let cpu_hz = evaluate(&gc.graph).get("cpu").copied().unwrap_or(0);
            if cpu_hz >= 120_000_000 {
                "esp_hal::clock::CpuClock::_160MHz"
            } else {
                "esp_hal::clock::CpuClock::_80MHz"
            }
        }
        ClockConfig::None => "esp_hal::clock::CpuClock::max()",
    };
    format!("esp_hal::init(esp_hal::Config::default().with_cpu_clock({cpu}))")
}

// ── Public entry points ───────────────────────────────────────────────────────

/// Build a brand-new `src/main.rs` for an ESP32-C3 project.
/// Called when the MCU type is first selected or the project is reset.
pub fn fresh_esp32c3_main_rs(
    pins: &[&Pin],
    clock: &ClockConfig,
    id: &str,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    custom_inits: &str,
    runtime: EspRuntime,
) -> String {
    let section = make_gen_section(pins, clock, usart, spi, i2c, custom_inits, runtime);
    format!("{}{section}\n{USER_TAIL}", invariant_header(id))
}

/// Replace only the GEN block inside `existing`, preserving the user's loop body.
/// If markers are not found, rebuilds from scratch.
pub fn update_esp32c3_main_rs(
    existing: &str,
    pins: &[&Pin],
    clock: &ClockConfig,
    id: &str,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    custom_inits: &str,
    runtime: EspRuntime,
) -> String {
    let new_section = make_gen_section(pins, clock, usart, spi, i2c, custom_inits, runtime);
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        // Strip ALL leading newlines after GEN_END, then re-add exactly one
        // blank line so splice is idempotent (same as the STM32 path in codegen.rs).
        let after = existing[end..].trim_start_matches('\n');
        format!("{}{new_section}\n{after}", &existing[..begin])
    } else {
        // No markers — rebuild from scratch.
        format!("{}{new_section}\n{USER_TAIL}", invariant_header(id))
    }
}

// ── Invariant file header ─────────────────────────────────────────────────────
//
// Written once on project creation; never touched during pin-config updates.

fn invariant_header(id: &str) -> String {
    format!(
        "// Auto-generated by Embedded IDE\n\
         {id_line}\
         #![no_std]\n\
         #![no_main]\n\n\
         pub mod pins;\n\n\
         \n\n\
         esp_bootloader_esp_idf::esp_app_desc!();\n\
         #[panic_handler]\n\
         fn panic(_: &core::panic::PanicInfo) -> ! {{\n\
             loop {{}}\n\
         }}\n\n\
         ",
        id_line = mcu_id_marker_line(id),
    )
}

// ── Generated section builder ─────────────────────────────────────────────────

fn make_gen_section(
    pins: &[&Pin],
    clock: &ClockConfig,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    // Custom-module `let x = Foo::new(…);` lines (see `Mcu::custom_module_inits`).
    custom_inits: &str,
    runtime: EspRuntime,
) -> String {
    let configured: Vec<&Pin> = pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .copied()
        .collect();

    if configured.is_empty() {
        return make_default_gen_section(clock, runtime);
    }

    // ── Feature flags ────────────────────────────────────────────────────────
    let has_output = configured
        .iter()
        .any(|p| p.selected_function == PinFunction::GpioOutput);
    let has_input = configured
        .iter()
        .any(|p| p.selected_function == PinFunction::GpioInput);
    let has_adc = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::AdcChannel { .. }));
    let has_uart = configured.iter().any(|p| {
        matches!(
            p.selected_function,
            PinFunction::UsartTx(_) | PinFunction::UsartRx(_)
        )
    });
    let has_spi = configured.iter().any(|p| {
        matches!(
            p.selected_function,
            PinFunction::SpiSck(_)
                | PinFunction::SpiMosi(_)
                | PinFunction::SpiMiso(_)
                | PinFunction::SpiNss(_)
        )
    });
    let has_i2c = configured.iter().any(|p| {
        matches!(
            p.selected_function,
            PinFunction::I2cScl(_) | PinFunction::I2cSda(_)
        )
    });
    let has_twai = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::CanTx | PinFunction::CanRx));
    let has_usb = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::UsbDm | PinFunction::UsbDp));

    // ── use block ─────────────────────────────────────────────────────────────
    let use_block = build_use_block(
        has_output, has_input, has_adc, has_uart, has_spi, has_i2c, runtime,
    );

    // ── fn main() body ────────────────────────────────────────────────────────
    let mut body = String::new();
    body.push_str(&format!(
        "    let peripherals = {};\n",
        esp_init_line(clock)
    ));
    // Async: start the scheduler before anything awaits (or spawns).
    body.push_str(runtime.start_block());

    // ── GPIO Output / Input ───────────────────────────────────────────────────
    let outputs: Vec<&Pin> = configured
        .iter()
        .filter(|p| p.selected_function == PinFunction::GpioOutput)
        .copied()
        .collect();
    let inputs: Vec<&Pin> = configured
        .iter()
        .filter(|p| p.selected_function == PinFunction::GpioInput)
        .copied()
        .collect();

    if !outputs.is_empty() || !inputs.is_empty() {
        body.push('\n');
        body.push_str("    // ── GPIO ──\n");
        for p in &outputs {
            body.push_str(&format!(
                "    let mut {var} = Output::new(peripherals.{gpio}, Level::High, OutputConfig::default()); // GPIO Output\n",
                var = esp_binding(p),
                gpio = p.name,
            ));
        }
        for p in &inputs {
            body.push_str(&format!(
                "    let {var} = Input::new(peripherals.{gpio}, InputConfig::default()); // GPIO Input\n",
                var = esp_binding(p),
                gpio = p.name,
            ));
        }
    }

    // ── ADC — grouped by ADC instance ────────────────────────────────────────
    if has_adc {
        let mut adc_pins: BTreeMap<u8, Vec<&Pin>> = BTreeMap::new();
        for p in configured
            .iter()
            .filter(|p| matches!(p.selected_function, PinFunction::AdcChannel { .. }))
        {
            if let PinFunction::AdcChannel { adc, .. } = p.selected_function {
                adc_pins.entry(adc).or_default().push(p);
            }
        }

        for (adc_n, pin_list) in &adc_pins {
            body.push('\n');
            body.push_str(&format!("    // ── ADC{adc_n} ──\n"));
            body.push_str(&format!(
                "    let mut adc{adc_n}_config = AdcConfig::new();\n"
            ));
            for p in pin_list {
                if let PinFunction::AdcChannel { .. } = p.selected_function {
                    body.push_str(&format!(
                        "    let mut {var} = adc{adc_n}_config\
                         .enable_pin(peripherals.{gpio}, Attenuation::_11dB); // {label}\n",
                        var = esp_binding(p),
                        gpio = p.name,
                        label = p.selected_function.label(),
                    ));
                }
            }
            body.push_str(&format!(
                "    let mut _adc{adc_n} = Adc::new(peripherals.ADC{adc_n}, adc{adc_n}_config);\n"
            ));
        }
    }

    // ── UART — grouped by peripheral instance ────────────────────────────────
    if has_uart {
        let mut uart_tx: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut uart_rx: BTreeMap<u8, &Pin> = BTreeMap::new();
        for p in configured.iter() {
            match p.selected_function {
                PinFunction::UsartTx(n) => {
                    uart_tx.insert(n, p);
                }
                PinFunction::UsartRx(n) => {
                    uart_rx.insert(n, p);
                }
                _ => {}
            }
        }
        let instances: BTreeSet<u8> = uart_tx.keys().chain(uart_rx.keys()).copied().collect();
        for n in instances {
            body.push('\n');
            body.push_str(&format!("    // ── UART{n} ──\n"));
            let rx_part = with_pin("with_rx", uart_rx.get(&n));
            let tx_part = with_pin("with_tx", uart_tx.get(&n));
            // A wired _USART module sets the baud rate; else esp-hal's default.
            let cfg = match usart.get(&n) {
                Some(c) => format!("UartConfig::default().with_baudrate({})", c.baud_rate),
                None => "UartConfig::default()".to_owned(),
            };
            let sfx = usart
                .get(&n)
                .map(|c| module_label_sfx(&c.custom_label))
                .unwrap_or_default();
            body.push_str(&format!(
                "    let mut _uart{n}{sfx} = Uart::new(peripherals.UART{n}, {cfg})\
                 {UNWRAP_CFG}{rx_part}{tx_part};\n"
            ));
        }
    }

    // ── SPI — grouped by peripheral instance ─────────────────────────────────
    if has_spi {
        let mut spi_sck: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut spi_mosi: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut spi_miso: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut spi_nss: BTreeMap<u8, &Pin> = BTreeMap::new();
        for p in configured.iter() {
            match p.selected_function {
                PinFunction::SpiSck(n) => {
                    spi_sck.insert(n, p);
                }
                PinFunction::SpiMosi(n) => {
                    spi_mosi.insert(n, p);
                }
                PinFunction::SpiMiso(n) => {
                    spi_miso.insert(n, p);
                }
                PinFunction::SpiNss(n) => {
                    spi_nss.insert(n, p);
                }
                _ => {}
            }
        }
        let instances: BTreeSet<u8> = spi_sck
            .keys()
            .chain(spi_mosi.keys())
            .chain(spi_miso.keys())
            .chain(spi_nss.keys())
            .copied()
            .collect();
        for n in instances {
            body.push('\n');
            body.push_str(&format!("    // ── SPI{n} ──\n"));
            let sck_part = with_pin("with_sck", spi_sck.get(&n));
            let mosi_part = with_pin("with_mosi", spi_mosi.get(&n));
            let miso_part = with_pin("with_miso", spi_miso.get(&n));
            let nss_part = with_pin("with_cs", spi_nss.get(&n));
            let sfx = spi
                .get(&n)
                .map(|c| module_label_sfx(&c.custom_label))
                .unwrap_or_default();
            body.push_str(&format!(
                "    let mut _spi{n}{sfx} = Spi::new(peripherals.SPI{n}, SpiConfig::default())\
                 {UNWRAP_CFG}{sck_part}{mosi_part}{miso_part}{nss_part};\n"
            ));
        }
    }

    // ── I2C — grouped by peripheral instance ─────────────────────────────────
    if has_i2c {
        let mut i2c_scl: BTreeMap<u8, &Pin> = BTreeMap::new();
        let mut i2c_sda: BTreeMap<u8, &Pin> = BTreeMap::new();
        for p in configured.iter() {
            match p.selected_function {
                PinFunction::I2cScl(n) => {
                    i2c_scl.insert(n, p);
                }
                PinFunction::I2cSda(n) => {
                    i2c_sda.insert(n, p);
                }
                _ => {}
            }
        }
        let instances: BTreeSet<u8> = i2c_scl.keys().chain(i2c_sda.keys()).copied().collect();
        for n in instances {
            body.push('\n');
            body.push_str(&format!("    // ── I2C{n} ──\n"));
            let scl_part = with_pin("with_scl", i2c_scl.get(&n));
            let sda_part = with_pin("with_sda", i2c_sda.get(&n));
            let sfx = i2c
                .get(&n)
                .map(|c| module_label_sfx(&c.custom_label))
                .unwrap_or_default();
            body.push_str(&format!(
                "    let mut _i2c{n}{sfx} = I2c::new(peripherals.I2C{n}, I2cConfig::default())\
                 {UNWRAP_CFG}{scl_part}{sda_part};\n"
            ));
        }
    }

    // ── TWAI (CAN-compatible) — comment only ─────────────────────────────────
    if has_twai {
        let twai_tx = configured
            .iter()
            .find(|p| p.selected_function == PinFunction::CanTx);
        let twai_rx = configured
            .iter()
            .find(|p| p.selected_function == PinFunction::CanRx);
        body.push('\n');
        body.push_str("    // ── TWAI (CAN) — add esp-hal twai feature to Cargo.toml ──\n");
        if let Some(tx) = twai_tx {
            body.push_str(&format!("    // TX: peripherals.{}\n", tx.name));
        }
        if let Some(rx) = twai_rx {
            body.push_str(&format!("    // RX: peripherals.{}\n", rx.name));
        }
    }

    // ── USB — comment only (hardware-fixed on GPIO18/GPIO19) ─────────────────
    if has_usb {
        body.push('\n');
        body.push_str("    // ── USB — configured automatically by the USB peripheral ──\n");
    }

    // ── Custom modules ── last, after every binding/init they consume.
    if !custom_inits.is_empty() {
        body.push('\n');
        body.push_str("    // ── Custom modules ──\n");
        body.push_str(custom_inits);
    }

    // Blank line before GEN_END
    body.push('\n');

    format!(
        "{GEN_BEGIN}\n\
         {use_block}\
         {entry}\
         {body}\
         {GEN_END}\n",
        entry = runtime.entry(),
    )
}

// ── Default generated section (no pins configured yet) ────────────────────────

fn make_default_gen_section(clock: &ClockConfig, runtime: EspRuntime) -> String {
    format!(
        "{GEN_BEGIN}\n\
         {use_block}\
         {entry}\
             let peripherals = {init};\n\
         {start}\n\
             // Select pins in the MCU Configurator to generate code here.\n\
         {GEN_END}\n",
        use_block = build_use_block(false, false, false, false, false, false, runtime),
        entry = runtime.entry(),
        init = esp_init_line(clock),
        start = runtime.start_block(),
    )
}

// ── use block builder ─────────────────────────────────────────────────────────

fn build_use_block(
    has_output: bool,
    has_input: bool,
    has_adc: bool,
    has_uart: bool,
    has_spi: bool,
    has_i2c: bool,
    runtime: EspRuntime,
) -> String {
    let mut lines: Vec<String> = Vec::new();

    // Entry-point imports first (`Spawner`, the timer + software interrupt the
    // scheduler start consumes) — none on the blocking path.
    lines.extend(runtime.use_lines().iter().map(|s| (*s).to_owned()));

    // gpio — collect needed types alphabetically via BTreeSet
    let mut gpio_types: BTreeSet<&str> = BTreeSet::new();
    if has_output {
        gpio_types.insert("Level");
        gpio_types.insert("Output");
        gpio_types.insert("OutputConfig");
    }
    if has_input {
        gpio_types.insert("Input");
        gpio_types.insert("InputConfig");
        gpio_types.insert("Pull");
    }
    if !gpio_types.is_empty() {
        let types = gpio_types.iter().copied().collect::<Vec<_>>().join(", ");
        lines.push(format!("use esp_hal::gpio::{{{types}}};"));
    }

    if has_adc {
        lines.push("use esp_hal::analog::adc::{Adc, AdcConfig, Attenuation};".into());
    }
    if has_uart {
        // esp-hal 1.1 exposes `uart::Config` directly — the old `uart::config`
        // submodule is gone (SPI/I2C keep theirs under `master`).
        lines.push("use esp_hal::uart::{Config as UartConfig, Uart};".into());
    }
    if has_spi {
        lines.push("use esp_hal::spi::master::{Config as SpiConfig, Spi};".into());
    }
    if has_i2c {
        lines.push("use esp_hal::i2c::master::{Config as I2cConfig, I2c};".into());
    }
    // No imports at all (blocking, and only USB/TWAI — which are comments —
    // selected): emit nothing rather than two stray blank lines above `fn main`.
    if lines.is_empty() {
        return String::new();
    }
    let mut block = lines.join("\n");
    block.push_str("\n\n");
    block
}

// ── Pin name → Rust variable name ────────────────────────────────────────────

/// Converts an ESP32 pin name to a snake_case variable name.
///
/// Examples:
/// - `"GPIO2"`  → `"gpio2"`
/// - `"GPIO20"` → `"gpio20"`
fn pin_var(pin_name: &str) -> String {
    pin_name.to_ascii_lowercase()
}

/// Binding (variable) name for a pin: `<gpio>_<type>[_<label>]`, e.g.
/// `gpio2_out`, `gpio0_adc1_in0`, or `gpio2_out_led` with a user label — the
/// ESP analogue of the STM32 `<pin>_<type>` format.
fn esp_binding(p: &Pin) -> String {
    pin_binding(&pin_var(&p.name), &p.selected_function, &p.custom_label)
}

/// One `.with_xxx(peripherals.GPIOn)` link of an esp-hal builder chain, with the
/// pin's function named in a comment on its OWN line above the call. Empty when
/// the peripheral has no pin for that role.
///
/// The comment must NOT trail the call: the chain's terminating `;` is appended
/// after the LAST link, so a trailing `// …` swallows it and the generated file
/// stops parsing (`expected ';', found keyword 'loop'`).
fn with_pin(method: &str, pin: Option<&&Pin>) -> String {
    pin.map(|p| {
        format!(
            "\n        // {label}\n        .{method}(peripherals.{name})",
            label = p.selected_function.label(),
            name = p.name,
        )
    })
    .unwrap_or_default()
}

/// `_<sanitized label>` suffix for a module's generated handle (`_uart1_imu`),
/// or "" when the module has no user label. Mirror of `stm32::module_label_sfx`.
fn module_label_sfx(label: &str) -> String {
    let s = sanitize_label(label);
    if s.is_empty() {
        String::new()
    } else {
        format!("_{s}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::panels::mcu_module::clock::graph::NodeState;
    use crate::panels::mcu_module::clock::graph::{GraphClock, esp32c3_graph, esp32c3_layout};
    use crate::panels::mcu_module::codegen::parse_mcu_id;

    fn esp_graph_clock() -> GraphClock {
        GraphClock {
            graph: esp32c3_graph(),
            layout: esp32c3_layout(),
        }
    }

    fn no_usart() -> BTreeMap<u8, UsartModuleConfig> {
        BTreeMap::new()
    }

    fn no_spi() -> BTreeMap<u8, SpiModuleConfig> {
        BTreeMap::new()
    }

    fn no_i2c() -> BTreeMap<u8, I2cModuleConfig> {
        BTreeMap::new()
    }

    /// The ESP CPU clock chosen in the diagram drives the generated
    /// `with_cpu_clock(...)` (bug: previously hardcoded to `max()`).
    #[test]
    fn default_cpu_clock_is_160mhz() {
        let code = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::Graph(esp_graph_clock()),
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert!(
            code.contains("CpuClock::_160MHz"),
            "default ESP CPU = 160 MHz:\n{code}"
        );
    }

    #[test]
    fn cpu_div6_emits_80mhz() {
        let mut gc = esp_graph_clock();
        gc.graph.node_mut("cpu_div").unwrap().state = NodeState::Index(1); // ÷6 → 80 MHz
        let code = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::Graph(gc),
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert!(
            code.contains("CpuClock::_80MHz"),
            "ESP CPU ÷6 = 80 MHz:\n{code}"
        );
        assert!(!code.contains("_160MHz"));
    }

    /// A chip with no modelled clock keeps the previous `max()` default.
    #[test]
    fn none_clock_falls_back_to_max() {
        let code = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::None,
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert!(code.contains("CpuClock::max()"), "{code}");
    }

    /// The MCU-id marker is emitted in the header and survives a re-splice, so a
    /// reopened project can restore the exact chip.
    #[test]
    fn id_marker_present_and_stable_across_update() {
        let fresh = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::None,
            "esp32c3-graph",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert_eq!(parse_mcu_id(&fresh).as_deref(), Some("esp32c3-graph"));
        let updated = update_esp32c3_main_rs(
            &fresh,
            &[],
            &ClockConfig::None,
            "esp32c3-graph",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert_eq!(parse_mcu_id(&updated).as_deref(), Some("esp32c3-graph"));
    }

    /// Every bus builder chain must end in a bare `.with_xxx(...)` so its `;` is
    /// real code. The pin labels used to TRAIL the call — the terminating `;`
    /// landed inside that comment and the file stopped parsing
    /// ("expected `;`, found keyword `loop`"), on both runtimes.
    #[test]
    fn bus_chains_close_outside_the_pin_comments() {
        use crate::panels::mcu_module::pins::logic::pin::Pin;
        let pin = |num: usize, name: &str, f: PinFunction| {
            let mut p = Pin::new(num, name).with_functions(vec![f.clone()]);
            p.selected_function = f;
            p
        };
        let pins = [
            pin(28, "GPIO21", PinFunction::UsartTx(0)),
            pin(27, "GPIO20", PinFunction::UsartRx(0)),
            pin(9, "GPIO4", PinFunction::SpiSck(2)),
            pin(10, "GPIO5", PinFunction::SpiMosi(2)),
            pin(12, "GPIO6", PinFunction::SpiMiso(2)),
            pin(13, "GPIO7", PinFunction::SpiNss(2)),
            pin(14, "GPIO8", PinFunction::I2cScl(0)),
            pin(15, "GPIO9", PinFunction::I2cSda(0)),
        ];
        let refs: Vec<&Pin> = pins.iter().collect();

        for runtime in [EspRuntime::Blocking, EspRuntime::Async] {
            let code = fresh_esp32c3_main_rs(
                &refs,
                &ClockConfig::None,
                "esp32c3",
                &no_usart(),
                &no_spi(),
                &no_i2c(),
                "",
                runtime,
            );
            for (i, line) in code.lines().enumerate() {
                if let Some((_, comment)) = line.split_once("//") {
                    assert!(
                        !comment.contains(';'),
                        "{runtime:?} line {}: `;` swallowed by a comment:\n{line}",
                        i + 1
                    );
                }
            }
            // Each bus is one statement, so one `;` per builder.
            for head in ["Uart::new", "Spi::new", "I2c::new"] {
                assert!(code.contains(head), "{runtime:?} emits {head}:\n{code}");
            }
            // esp-hal 1.1: the three constructors return Result, so the
            // `.with_xxx` links below them need the value unwrapped first.
            assert_eq!(
                code.matches(".unwrap()").count(),
                3,
                "{runtime:?} one unwrap per bus:\n{code}"
            );
            // esp-hal 1.1 moved UART's Config out of a `config` submodule.
            assert!(
                code.contains("use esp_hal::uart::{Config as UartConfig, Uart};"),
                "{runtime:?} uart import:\n{code}"
            );
            assert!(!code.contains("uart::config"), "{runtime:?}:\n{code}");
        }
    }

    /// A wired _USART module sets the baud rate on the generated `Uart::new`.
    #[test]
    fn module_baud_drives_uart_config() {
        use crate::panels::mcu_module::pins::logic::pin::Pin;
        let mut tx = Pin::new(28, "GPIO21").with_functions(vec![PinFunction::UsartTx(0)]);
        tx.selected_function = PinFunction::UsartTx(0);
        let mut rx = Pin::new(27, "GPIO20").with_functions(vec![PinFunction::UsartRx(0)]);
        rx.selected_function = PinFunction::UsartRx(0);

        let mut usart = no_usart();
        let mut cfg = UsartModuleConfig::new(0);
        cfg.baud_rate = 9600;
        usart.insert(0, cfg);

        let code = fresh_esp32c3_main_rs(
            &[&tx, &rx],
            &ClockConfig::None,
            "esp32c3",
            &usart,
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert!(
            code.contains("with_baudrate(9600)"),
            "baud on Uart::new:\n{code}"
        );

        // No module → plain default config.
        let plain = fresh_esp32c3_main_rs(
            &[&tx, &rx],
            &ClockConfig::None,
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            "",
            EspRuntime::Blocking,
        );
        assert!(
            plain.contains("UartConfig::default())"),
            "default config:\n{plain}"
        );
        assert!(!plain.contains("with_baudrate"));
    }
}
