//! ESP32-C3 / esp-hal code generator.
//!
//! Generates and splices the GEN_BEGIN … GEN_END block for ESP32-C3 projects.
//! The HAL version is not written here — the header line is built from
//! [`ESP_HAL_REQ`](crate::panels::mcu_module::project_gen::ESP_HAL_REQ), the same
//! constant `Cargo.toml` is generated from. Structure of a generated
//! `src/main.rs`:
//!
//! ```text
//! // Auto-generated by Embedded IDE
//! // MCU: ESP32-C3 | HAL: esp-hal 1.1.0 (blocking)
//! // embedded-ide:mcu=esp32c3
//! #![no_std]
//! #![no_main]
//!
//! // <<< GENERATED BEGIN — do not edit between these markers >>>
//! use esp_hal::gpio::{Level, Output, OutputConfig};
//!
//! #[esp_hal::main]
//! fn main() -> ! {
//!     let peripherals = esp_hal::init(esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::max()));
//!
//!     // ── GPIO ──
//!     let mut gpio2_out = Output::new(peripherals.GPIO2, Level::High, OutputConfig::default()); // GPIO Output
//!
//! // <<< GENERATED END >>>
//!     loop {
//!         // Your main loop code here.
//!     }
//! }
//! ```
//!
//! The [`Runtime::Async`] path emits the same body from the same builder — only
//! the entry point differs (`#[esp_rtos::main] async fn main(Spawner)` plus the
//! `esp_rtos::start(...)` scheduler hand-off). See [`EspRuntime`].
//!
//! [`Runtime::Async`]: crate::panels::mcu_module::mcu::Runtime

use super::clock::ClockConfig;
use super::clock::graph::evaluate;
use super::codegen::dma_map::DmaUse;
use super::codegen::{GEN_BEGIN, GEN_END, mcu_id_marker_line, pin_binding, sanitize_label};
use super::mcu_def::DmaDef;
use super::modules::{
    AsyncBusMode, I2cModuleConfig, I2sModuleConfig, McpwmModuleConfig, ParlIoModuleConfig,
    PcntModuleConfig, RmtModuleConfig, SpiModuleConfig, TimerModuleConfig, UsartModuleConfig,
};
use super::pins::logic::pin::Pin;
use super::pins::logic::pin_function::PinFunction;
use std::collections::{BTreeMap, BTreeSet};

// ── User tail — closes fn main() ─────────────────────────────────────────────

const USER_TAIL: &str = "    loop {\n        // Your main loop code here.\n    }\n}\n";

// ── Runtime (entry point) ────────────────────────────────────────────────────

/// Which entry point the generated `main` opens — the only structural difference
/// between the two ESP paths. Everything below the entry (clock, GPIO, UART,
/// SPI, I2C bindings) is byte-for-byte identical: they are the same esp-hal
/// drivers, so one builder serves both.
///
/// Async is `esp-rtos`, NOT `esp-hal-embassy`. The latter is pinned to esp-hal
/// 1.0 by the private `__esp_hal_embassy` feature, which esp-hal 1.1 (what the
/// project template pins) no longer has — the dependency resolution fails before
/// anything compiles. `esp-rtos` is the same maintainers' replacement and drives
/// the very same `embassy-executor` / `embassy-time`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum EspRuntime {
    /// `#[esp_hal::main] fn main() -> !`
    Blocking,
    /// `#[esp_rtos::main] async fn main(_spawner: Spawner)`, with the scheduler
    /// started from TIMG0 + software interrupt 0.
    Async,
}

impl EspRuntime {
    /// The attribute + `fn` signature line(s) that open `main`, ending in `{\n`.
    fn entry(self) -> &'static str {
        match self {
            Self::Blocking => "#[esp_hal::main]\nfn main() -> ! {\n",
            Self::Async => "#[esp_rtos::main]\nasync fn main(_spawner: Spawner) {\n",
        }
    }

    /// The lines that hand the timer to the scheduler, emitted right after
    /// `esp_hal::init` — empty on the blocking path.
    ///
    /// TIMG0 is the timer the esp-rtos docs (and `esp-generate`) use; taking it
    /// here means user code cannot also claim `peripherals.TIMG0`, which is the
    /// normal trade for having `embassy_time::Timer` work at all.
    fn start_block(self) -> &'static str {
        match self {
            Self::Blocking => "",
            Self::Async => {
                "\n    // ── Async runtime (esp-rtos drives the embassy executor) ──\n\
                 \x20   let timg0 = TimerGroup::new(peripherals.TIMG0);\n\
                 \x20   let sw_int = SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);\n\
                 \x20   esp_rtos::start(timg0.timer0, sw_int.software_interrupt0);\n"
            }
        }
    }

    /// The extra `use` items the async entry + scheduler start need.
    fn use_lines(self) -> &'static [&'static str] {
        match self {
            Self::Blocking => &[],
            Self::Async => &[
                "use embassy_executor::Spawner;",
                "use esp_hal::interrupt::software::SoftwareInterruptControl;",
                "use esp_hal::timer::timg::TimerGroup;",
            ],
        }
    }
}

// ── Clock config → esp-hal `CpuClock` ─────────────────────────────────────────

/// The `esp_hal::init(...)` line, with the CPU clock taken from the clock graph.
///
/// `CpuClock` is a DIFFERENT enum on every chip, and naming a variant the part
/// lacks is a compile error in the USER's project. This used to emit `_160MHz`
/// or `_80MHz` unconditionally — right for the ESP32-C3 it was written for, and
/// both wrong for an ESP32-H2, whose only variant is `_96MHz`. See
/// [`esp_clocks`](super::esp_clocks).
///
/// With no graph clock the line falls back to `CpuClock::max()`, valid on every
/// part — which is why chips added before this table still generated code that
/// built.
fn esp_init_line(clock: &ClockConfig, chip: &str) -> String {
    let cpu = match clock {
        ClockConfig::Graph(gc) => {
            let cpu_hz = evaluate(&gc.for_codegen()).get("cpu").copied().unwrap_or(0);
            super::esp_clocks::cpu_variant(chip, cpu_hz / 1_000_000)
                .unwrap_or_else(|| "esp_hal::clock::CpuClock::max()".to_owned())
        }
        ClockConfig::None => "esp_hal::clock::CpuClock::max()".to_owned(),
    };
    format!("esp_hal::init(esp_hal::Config::default().with_cpu_clock({cpu}))")
}

// ── Public entry points ───────────────────────────────────────────────────────

/// Build a brand-new `src/main.rs` for an ESP32-C3 project.
/// Called when the MCU type is first selected or the project is reset.
pub fn fresh_esp32c3_main_rs(
    pins: &[&Pin],
    clock: &ClockConfig,
    mcu_name: &str,
    id: &str,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    i2s: &BTreeMap<u8, I2sModuleConfig>,
    rmt: &BTreeMap<u8, RmtModuleConfig>,
    pcnt: &BTreeMap<u8, PcntModuleConfig>,
    mcpwm: &BTreeMap<u8, McpwmModuleConfig>,
    parl_io: &BTreeMap<u8, ParlIoModuleConfig>,
    timer: &BTreeMap<u8, TimerModuleConfig>,
    custom_inits: &str,
    // The chip id (`esp32h2`) — it decides which `CpuClock`
    // variants exist, and they differ per part.
    chip: &str,
    runtime: EspRuntime,
    // The chip's DMA channels, so a bus asking for one can be given
    // it here rather than left with a TODO.
    dma: Option<&DmaDef>,
) -> String {
    let section = make_gen_section(
        pins,
        clock,
        usart,
        spi,
        i2c,
        i2s,
        rmt,
        pcnt,
        mcpwm,
        parl_io,
        timer,
        custom_inits,
        chip,
        runtime,
        dma,
    );
    format!(
        "{}{section}\n{USER_TAIL}",
        invariant_header(mcu_name, id, runtime)
    )
}

/// Replace only the GEN block inside `existing`, preserving the user's loop body.
/// If markers are not found, rebuilds from scratch.
pub fn update_esp32c3_main_rs(
    existing: &str,
    pins: &[&Pin],
    clock: &ClockConfig,
    mcu_name: &str,
    id: &str,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    i2s: &BTreeMap<u8, I2sModuleConfig>,
    rmt: &BTreeMap<u8, RmtModuleConfig>,
    pcnt: &BTreeMap<u8, PcntModuleConfig>,
    mcpwm: &BTreeMap<u8, McpwmModuleConfig>,
    parl_io: &BTreeMap<u8, ParlIoModuleConfig>,
    timer: &BTreeMap<u8, TimerModuleConfig>,
    custom_inits: &str,
    // The chip id (`esp32h2`) — it decides which `CpuClock`
    // variants exist, and they differ per part.
    chip: &str,
    runtime: EspRuntime,
    // The chip's DMA channels, so a bus asking for one can be given
    // it here rather than left with a TODO.
    dma: Option<&DmaDef>,
) -> String {
    let new_section = make_gen_section(
        pins,
        clock,
        usart,
        spi,
        i2c,
        i2s,
        rmt,
        pcnt,
        mcpwm,
        parl_io,
        timer,
        custom_inits,
        chip,
        runtime,
        dma,
    );
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        // Strip ALL leading newlines after GEN_END, then re-add exactly one
        // blank line so splice is idempotent (same as the STM32 path in codegen.rs).
        let after = existing[end..].trim_start_matches('\n');
        // The region above the markers is the USER's (their own `use` items, their
        // panic handler) so it is kept as-is — except the one provenance line,
        // which is ours to keep truthful.
        let head = refresh_hal_line(&existing[..begin], mcu_name, runtime);
        format!("{head}{new_section}\n{after}")
    } else {
        // No markers — rebuild from scratch.
        format!(
            "{}{new_section}\n{USER_TAIL}",
            invariant_header(mcu_name, id, runtime)
        )
    }
}

// ── Invariant file header ─────────────────────────────────────────────────────
//
// Written once on project creation. Only the `// MCU: … | HAL: …` provenance
// line is refreshed afterwards (see `refresh_hal_line`) — everything else above
// the markers may have been edited by the user and is left alone.

/// First line of a generated file, and the anchor the provenance line is
/// inserted after when an older file has none.
const AUTOGEN_LINE: &str = "// Auto-generated by Embedded IDE";

/// Marker the provenance line starts with, so it can be found and rewritten.
const HAL_LINE_PREFIX: &str = "// MCU: ";

/// The `// MCU: … | HAL: …` line: which chip, which HAL **version**, which
/// runtime. Both versions come from the constants `Cargo.toml` is generated
/// from, so the comment cannot drift from the dependency it describes — the way
/// a hardcoded "esp-hal 0.22" kept claiming 0.22 on a 1.1 project.
fn hal_line(mcu_name: &str, runtime: EspRuntime) -> String {
    // "~1.1.0" / "^1.1" / "1.1.0" all describe the same release series; show it
    // without the requirement operator.
    let hal =
        crate::panels::mcu_module::project_gen::ESP_HAL_REQ.trim_start_matches(['~', '^', '=']);
    let rtos = crate::panels::mcu_module::project_gen::ESP_RTOS_REQ;
    match runtime {
        EspRuntime::Blocking => {
            format!("{HAL_LINE_PREFIX}{mcu_name} | HAL: esp-hal {hal} (blocking)\n")
        }
        EspRuntime::Async => {
            format!("{HAL_LINE_PREFIX}{mcu_name} | HAL: esp-hal {hal} + esp-rtos {rtos} (async)\n")
        }
    }
}

/// Rewrite the provenance line inside `head` (everything above `GEN_BEGIN`), or
/// insert it when the file has none — an older project keeps advertising the HAL
/// it was BORN with, and a runtime switch would otherwise leave "(blocking)" on
/// an async file. Idempotent: re-running on its own output changes nothing.
fn refresh_hal_line(head: &str, mcu_name: &str, runtime: EspRuntime) -> String {
    let wanted = hal_line(mcu_name, runtime);
    let mut out = String::with_capacity(head.len() + wanted.len());
    let mut done = false;
    for line in head.split_inclusive('\n') {
        if line.trim_start().starts_with(HAL_LINE_PREFIX) {
            if !done {
                out.push_str(&wanted); // replace in place, keeping its position
                done = true;
            }
            continue; // drop duplicates from older revisions
        }
        out.push_str(line);
        if !done && line.trim_end() == AUTOGEN_LINE {
            out.push_str(&wanted);
            done = true;
        }
    }
    if !done {
        // Neither a provenance line nor the autogen banner (a file the user
        // rewrote from scratch) — put it at the very top, where it reads.
        out.insert_str(0, &wanted);
    }
    out
}

fn invariant_header(mcu_name: &str, id: &str, runtime: EspRuntime) -> String {
    format!(
        "{AUTOGEN_LINE}\n\
         {hal}\
         {id_line}\
         #![no_std]\n\
         #![no_main]\n\n\
         pub mod pins;\n\n\
         \n\n\
         esp_bootloader_esp_idf::esp_app_desc!();\n\
         #[panic_handler]\n\
         fn panic(_: &core::panic::PanicInfo) -> ! {{\n\
             loop {{}}\n\
         }}\n\n\
         ",
        hal = hal_line(mcu_name, runtime),
        id_line = mcu_id_marker_line(id),
    )
}

// ── Generated section builder ─────────────────────────────────────────────────

fn make_gen_section(
    pins: &[&Pin],
    clock: &ClockConfig,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    i2s: &BTreeMap<u8, I2sModuleConfig>,
    rmt: &BTreeMap<u8, RmtModuleConfig>,
    pcnt: &BTreeMap<u8, PcntModuleConfig>,
    mcpwm: &BTreeMap<u8, McpwmModuleConfig>,
    parl_io: &BTreeMap<u8, ParlIoModuleConfig>,
    // PWM (LEDC) module settings, keyed by LEDC timer.
    timer: &BTreeMap<u8, TimerModuleConfig>,
    // Custom-module `let x = Foo::new(…);` lines (see `Mcu::custom_module_inits`).
    custom_inits: &str,
    // The chip id (`esp32h2`) — it decides which `CpuClock`
    // variants exist, and they differ per part.
    chip: &str,
    runtime: EspRuntime,
    dma: Option<&DmaDef>,
) -> String {
    let configured: Vec<&Pin> = pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .copied()
        .collect();

    if configured.is_empty() {
        return make_default_gen_section(clock, chip, runtime);
    }

    // ── Feature flags ────────────────────────────────────────────────────────
    let has_output = configured
        .iter()
        .any(|p| p.selected_function == PinFunction::GpioOutput);
    let has_input = configured
        .iter()
        .any(|p| p.selected_function == PinFunction::GpioInput);
    let has_adc = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::AdcChannel { .. }));
    let has_uart = configured.iter().any(|p| {
        matches!(
            p.selected_function,
            PinFunction::UsartTx(_) | PinFunction::UsartRx(_)
        )
    });
    let has_spi = configured.iter().any(|p| {
        matches!(
            p.selected_function,
            PinFunction::SpiSck(_)
                | PinFunction::SpiMosi(_)
                | PinFunction::SpiMiso(_)
                | PinFunction::SpiNss(_)
        )
    });
    let has_i2c = configured.iter().any(|p| {
        matches!(
            p.selected_function,
            PinFunction::I2cScl(_) | PinFunction::I2cSda(_)
        )
    });
    let has_twai = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::CanTx | PinFunction::CanRx));
    let has_usb = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::UsbDm | PinFunction::UsbDp));

    // ── use block ─────────────────────────────────────────────────────────────
    let has_pwm = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::TimerPwm { .. }));
    let has_rmt = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::RmtChannel(..)));
    let has_pcnt = configured
        .iter()
        .any(|p| matches!(p.selected_function, PinFunction::PcntEdge(..)));
    let use_block = build_use_block(
        has_output, has_input, has_adc, has_uart, has_spi, has_i2c, has_pwm, has_rmt, has_pcnt,
        runtime,
    );

    // ── fn main() body ────────────────────────────────────────────────────────
    let mut body = String::new();
    body.push_str(&format!(
        "    let peripherals = {};\n",
        esp_init_line(clock, chip)
    ));
    // Async: start the scheduler before anything awaits (or spawns).
    body.push_str(runtime.start_block());

    // ── GPIO Output / Input ───────────────────────────────────────────────────
    let outputs: Vec<&Pin> = configured
        .iter()
        .filter(|p| p.selected_function == PinFunction::GpioOutput)
        .copied()
        .collect();
    let inputs: Vec<&Pin> = configured
        .iter()
        .filter(|p| p.selected_function == PinFunction::GpioInput)
        .copied()
        .collect();

    if !outputs.is_empty() || !inputs.is_empty() {
        body.push('\n');
        body.push_str("    // ── GPIO ──\n");
        // A GPIO is declared for the reader's loop, which a fresh project does
        // not have yet, so every pin they have not got to warns — twice for an
        // output (`unused_variables` and `unused_mut`). These lines are INSIDE
        // the generated block, so that is a warning they cannot answer by
        // editing the line. Scoped to the one statement, it goes inert the
        // moment the pin is used. Same rule as the STM32F1 backend.
        const ALLOW: &str = "    #[allow(unused_mut, unused_variables)]\n";
        for p in &outputs {
            body.push_str(ALLOW);
            body.push_str(&format!(
                "    let mut {var} = Output::new(peripherals.{gpio}, Level::High, OutputConfig::default()); // GPIO Output\n",
                var = esp_binding(p),
                gpio = p.name,
            ));
        }
        for p in &inputs {
            body.push_str(ALLOW);
            body.push_str(&format!(
                "    let {var} = Input::new(peripherals.{gpio}, InputConfig::default()); // GPIO Input\n",
                var = esp_binding(p),
                gpio = p.name,
            ));
        }
    }

    // ── ADC — grouped by ADC instance ────────────────────────────────────────
    if has_adc {
        let mut adc_pins: BTreeMap<u8, Vec<&Pin>> = BTreeMap::new();
        for p in configured
            .iter()
            .filter(|p| matches!(p.selected_function, PinFunction::AdcChannel { .. }))
        {
            if let PinFunction::AdcChannel { adc, .. } = p.selected_function {
                adc_pins.entry(adc).or_default().push(p);
            }
        }

        for (adc_n, pin_list) in &adc_pins {
            body.push('\n');
            body.push_str(&format!("    // ── ADC{adc_n} ──\n"));
            body.push_str(&format!(
                "    let mut adc{adc_n}_config = AdcConfig::new();\n"
            ));
            for p in pin_list {
                if let PinFunction::AdcChannel { .. } = p.selected_function {
                    body.push_str(&format!(
                        "    let mut {var} = adc{adc_n}_config\
                         .enable_pin(peripherals.{gpio}, Attenuation::_11dB); // {label}\n",
                        var = esp_binding(p),
                        gpio = p.name,
                        label = p.selected_function.label(),
                    ));
                }
            }
            body.push_str(&format!(
                "    let mut _adc{adc_n} = Adc::new(peripherals.ADC{adc_n}, adc{adc_n}_config);\n"
            ));
        }
    }

    // ── Buses: bind the pins here, initialise in `pins/configs/<bus>.rs` ─────
    // Every wired pin keeps its OWN `let … = peripherals.GPIOn; // LABEL` line.
    // Two reasons: the canvas assignment stays visible where the user reads the
    // code, and it is the ONLY record a reopened project has — `parse_main_rs`
    // rebuilds the diagram from these lines (`mcu.config` stores no pin
    // functions). Moving them into the config module would lose the pins.
    // The I2S instances the canvas wires, so the allocator can serve them
    // first — an I2S without a channel cannot be generated at all.
    let i2s_wired: Vec<u8> = collect_buses(&configured).3.keys().copied().collect();
    let dma_plan = dma_plan(
        dma,
        runtime,
        spi,
        &i2s_wired,
        collect_parl_io(&configured).is_some(),
    );
    for (label, calls) in bus_sections(
        &configured,
        usart,
        spi,
        i2c,
        i2s,
        rmt,
        pcnt,
        mcpwm,
        parl_io.get(&0),
        crate::panels::mcu_module::mcu::gui::modules::rmt_source_hz(chip),
        runtime,
        &dma_plan,
    ) {
        body.push('\n');
        body.push_str(&format!("    // ── {label} ──\n"));
        body.push_str(&calls);
    }

    // ── PWM (LEDC) ───────────────────────────────────────────────────────────
    // The LEDC is ONE peripheral for the whole chip: `Ledc::new` may be called
    // once, and every timer and channel comes out of it. So it is built here,
    // not inside a config module, and lent to each.
    let pwm = pwm_channels(&configured);
    if !pwm.is_empty() {
        body.push('\n');
        body.push_str("    // ── PWM (LEDC) ──\n");
        body.push_str("    let ledc = Ledc::new(peripherals.LEDC);\n");
        for (t, chans) in &pwm {
            let sfx = timer
                .get(t)
                .map(|c| module_label_sfx(&c.custom_label))
                .unwrap_or_default();
            // Each pad keeps its own `let … = peripherals.GPIOn; // LABEL` line:
            // that is the only record `parse_main_rs` has of the wiring.
            let mut args = Vec::new();
            for (_, p) in chans {
                let var = esp_binding(p);
                body.push_str(&format!(
                    "    let {var} = peripherals.{gpio}; // {label}\n",
                    gpio = p.name,
                    label = p.selected_function.label(),
                ));
                args.push(var);
            }
            // The timer is a NAMED local because the channels borrow it for as
            // long as they live — `pwm{t}::init` takes it by reference.
            body.push_str(&format!(
                "    let lstimer{t} = pins::configs::pwm{t}::timer(&ledc);\n"
            ));
            body.push_str(&format!(
                "    let mut _pwm{t}{sfx} = pins::configs::pwm{t}::init(&ledc, &lstimer{t}, {});\n",
                args.join(", ")
            ));
        }
    }

    // ── TWAI (CAN-compatible) — comment only ─────────────────────────────────
    if has_twai {
        let twai_tx = configured
            .iter()
            .find(|p| p.selected_function == PinFunction::CanTx);
        let twai_rx = configured
            .iter()
            .find(|p| p.selected_function == PinFunction::CanRx);
        body.push('\n');
        body.push_str("    // ── TWAI (CAN) — add esp-hal twai feature to Cargo.toml ──\n");
        if let Some(tx) = twai_tx {
            body.push_str(&format!("    // TX: peripherals.{}\n", tx.name));
        }
        if let Some(rx) = twai_rx {
            body.push_str(&format!("    // RX: peripherals.{}\n", rx.name));
        }
    }

    // ── USB Serial/JTAG ──────────────────────────────────────────────────────
    // No pins are passed, and that is the peripheral, not a shortcut: the pads
    // are fixed in silicon and differ per part (C3 GPIO18/19, C6 GPIO12/13, S3
    // GPIO19/20, H2 GPIO26/27), so `UsbSerialJtag::new` takes the peripheral
    // alone. The two pads still carry `UsbDm`/`UsbDp` on the canvas — that is
    // what makes the pair visible and unassignable to anything else.
    if has_usb {
        body.push('\n');
        if has_usb_serial_jtag(chip) {
            body.push_str("    // ── USB Serial/JTAG ──\n");
            body.push_str(&format!(
                "    let mut _usb = pins::configs::usb::{}(peripherals.USB_DEVICE);\n",
                if runtime == EspRuntime::Async {
                    "init_async"
                } else {
                    "init"
                },
            ));
        } else {
            // The pads are real and the driver is not. Saying so beats an
            // "automatically configured" line that configures nothing.
            body.push_str(
                "    // ── USB — pads only ──\n\
                 \x20   // This chip has the USB pads, and its esp-hal has no\n\
                 \x20   // usb_serial_jtag driver. Nothing is generated for them.\n",
            );
        }
    }

    // ── Custom modules ── last, after every binding/init they consume.
    if !custom_inits.is_empty() {
        body.push('\n');
        body.push_str("    // ── Custom modules ──\n");
        body.push_str(custom_inits);
    }

    // Blank line before GEN_END
    body.push('\n');

    format!(
        "{GEN_BEGIN}\n\
         {use_block}\
         {entry}\
         {body}\
         {GEN_END}\n",
        entry = runtime.entry(),
    )
}

// ── Default generated section (no pins configured yet) ────────────────────────

fn make_default_gen_section(clock: &ClockConfig, chip: &str, runtime: EspRuntime) -> String {
    format!(
        "{GEN_BEGIN}\n\
         {use_block}\
         {entry}\
             let peripherals = {init};\n\
         {start}\n\
             // Select pins in the MCU Configurator to generate code here.\n\
         {GEN_END}\n",
        use_block = build_use_block(
            false, false, false, false, false, false, false, false, false, runtime,
        ),
        entry = runtime.entry(),
        init = esp_init_line(clock, chip),
        start = runtime.start_block(),
    )
}

// ── use block builder ─────────────────────────────────────────────────────────

fn build_use_block(
    has_output: bool,
    has_input: bool,
    has_adc: bool,
    has_uart: bool,
    has_spi: bool,
    has_i2c: bool,
    has_pwm: bool,
    has_rmt: bool,
    has_pcnt: bool,
    runtime: EspRuntime,
) -> String {
    let mut lines: Vec<String> = Vec::new();

    // Entry-point imports first (`Spawner`, the timer + software interrupt the
    // scheduler start consumes) — none on the blocking path.
    lines.extend(runtime.use_lines().iter().map(|s| (*s).to_owned()));

    // gpio — collect needed types alphabetically via BTreeSet
    let mut gpio_types: BTreeSet<&str> = BTreeSet::new();
    if has_output {
        gpio_types.insert("Level");
        gpio_types.insert("Output");
        gpio_types.insert("OutputConfig");
    }
    if has_input {
        gpio_types.insert("Input");
        gpio_types.insert("InputConfig");
        // NOT `Pull`: the generated `Input::new` takes `InputConfig::default()`
        // and never names a pull, so importing it earned every ESP project with
        // an input an unused-import warning. It belongs here the day the
        // generator emits `InputConfig::default().with_pull(..)`, and not before
        // — an import is a claim that the code below uses it.
    }
    if !gpio_types.is_empty() {
        let types = gpio_types.iter().copied().collect::<Vec<_>>().join(", ");
        lines.push(format!("use esp_hal::gpio::{{{types}}};"));
    }

    if has_adc {
        lines.push("use esp_hal::analog::adc::{Adc, AdcConfig, Attenuation};".into());
    }
    // The LEDC is the one peripheral `main.rs` builds itself: it is a single
    // chip-wide block, so `Ledc::new` cannot live in a per-timer config module.
    if has_pwm {
        lines.push("use esp_hal::ledc::Ledc;".into());
    }
    // The RMT is the same shape: one block for the chip, whose channels are
    // fields of what `Rmt::new` returns, so it too is built here and lent out.
    // `Rate` comes with it — the constructor takes the source clock.
    if has_rmt {
        lines.push("use esp_hal::rmt::Rmt;".into());
        lines.push("use esp_hal::time::Rate;".into());
    }
    // And once more for the pulse counter: one block, units as fields.
    if has_pcnt {
        lines.push("use esp_hal::pcnt::Pcnt;".into());
    }
    // Nothing for MCPWM: `McPwm::new` lives in the config module, and `main.rs`
    // only hands it the peripheral it already holds.
    // Nothing: the USB driver is built inside `pins/configs/usb.rs`, which
    // takes no argument from `main.rs` at all.
    // No bus imports: UART/SPI/I2C are built inside `pins/configs/<bus>.rs`, and
    // `main.rs` only hands them peripherals it already has in scope.
    let _ = (has_uart, has_spi, has_i2c);
    // No imports at all (blocking, and only USB/TWAI — which are comments —
    // selected): emit nothing rather than two stray blank lines above `fn main`.
    if lines.is_empty() {
        return String::new();
    }
    let mut block = lines.join("\n");
    block.push_str("\n\n");
    block
}

// ── Pin name → Rust variable name ────────────────────────────────────────────

/// Converts an ESP32 pin name to a snake_case variable name.
///
/// Examples:
/// - `"GPIO2"`  → `"gpio2"`
/// - `"GPIO20"` → `"gpio20"`
fn pin_var(pin_name: &str) -> String {
    pin_name.to_ascii_lowercase()
}

/// Binding (variable) name for a pin: `<gpio>_<type>[_<label>]`, e.g.
/// `gpio2_out`, `gpio0_adc1_in0`, or `gpio2_out_led` with a user label — the
/// ESP analogue of the STM32 `<pin>_<type>` format.
fn esp_binding(p: &Pin) -> String {
    pin_binding(&pin_var(&p.name), &p.selected_function, &p.custom_label)
}

/// The LEDC timers with at least one channel wired, each with its channels in
/// ascending order.
///
/// On the ESP32-C3 every one of the six channels belongs to `timer: 0` in the
/// pin table, so in practice this is one entry — but the shape is the model's,
/// not the chip's, and a part with four LEDC timers would fill it out.
pub fn pwm_channels<'a>(configured: &[&'a Pin]) -> Vec<(u8, Vec<(u8, &'a Pin)>)> {
    let mut by_timer: BTreeMap<u8, BTreeMap<u8, &Pin>> = BTreeMap::new();
    for p in configured {
        if let PinFunction::TimerPwm { timer, channel } = p.selected_function {
            by_timer.entry(timer).or_default().insert(channel, p);
        }
    }
    by_timer
        .into_iter()
        .map(|(t, chans)| (t, chans.into_iter().collect()))
        .collect()
}

/// The wired instances of each bus, as `(instance, signal → pin)` maps. One
/// pass over the pins instead of three near-identical ones.
type BusPins<'a> = BTreeMap<u8, BTreeMap<&'static str, &'a Pin>>;

fn collect_buses<'a>(
    configured: &[&'a Pin],
) -> (BusPins<'a>, BusPins<'a>, BusPins<'a>, BusPins<'a>) {
    let (mut uart, mut spi, mut i2c, mut i2s): (BusPins, BusPins, BusPins, BusPins) =
        Default::default();
    for p in configured {
        let (bus, n, sig) = match p.selected_function {
            PinFunction::UsartRx(n) => (&mut uart, n, "rx"),
            PinFunction::UsartTx(n) => (&mut uart, n, "tx"),
            PinFunction::SpiSck(n) => (&mut spi, n, "sck"),
            PinFunction::SpiMosi(n) => (&mut spi, n, "mosi"),
            PinFunction::SpiMiso(n) => (&mut spi, n, "miso"),
            PinFunction::SpiNss(n) => (&mut spi, n, "cs"),
            PinFunction::I2cScl(n) => (&mut i2c, n, "scl"),
            PinFunction::I2cSda(n) => (&mut i2c, n, "sda"),
            // The canvas keeps the STM32 signal names; the esp-hal method each
            // maps to is chosen in `i2s_file`, where the direction is known.
            PinFunction::I2sCk(n) => (&mut i2s, n, "ck"),
            PinFunction::I2sWs(n) => (&mut i2s, n, "ws"),
            PinFunction::I2sSd(n) => (&mut i2s, n, "sd"),
            PinFunction::I2sMck(n) => (&mut i2s, n, "mck"),
            _ => continue,
        };
        bus.entry(n).or_default().insert(sig, p);
    }
    (uart, spi, i2c, i2s)
}

/// The RMT channels the canvas wires, with the pad each is on.
///
/// Not part of [`collect_buses`]: a bus there is an instance with SEVERAL named
/// signals, and an RMT channel has exactly one wire. Keeping it separate is
/// what lets the emission stay a single `let` per channel.
fn collect_rmt<'a>(configured: &[&'a Pin]) -> BTreeMap<u8, &'a Pin> {
    configured
        .iter()
        .filter_map(|p| match p.selected_function {
            PinFunction::RmtChannel(n) => Some((n, *p)),
            _ => None,
        })
        .collect()
}

/// The parallel port's pads, in the order `init` takes them.
///
/// `(data lanes by index, clock, valid)`. The data lanes are returned SPARSE —
/// a bus whose D3 is unassigned yields no D3 — because the generated `init`
/// declares a parameter per lane of its width, and a gap there is a wiring
/// mistake worth showing rather than papering over.
fn collect_parl_io<'a>(
    configured: &[&'a Pin],
) -> Option<(BTreeMap<u8, &'a Pin>, Option<&'a Pin>, Option<&'a Pin>)> {
    let mut data: BTreeMap<u8, &Pin> = BTreeMap::new();
    let (mut clk, mut valid) = (None, None);
    for p in configured {
        match p.selected_function {
            PinFunction::ParlData { lane } => {
                data.insert(lane, *p);
            }
            PinFunction::ParlClk => clk = Some(*p),
            PinFunction::ParlValid => valid = Some(*p),
            _ => {}
        }
    }
    // The clock is what makes it a port rather than a handful of GPIOs, and
    // `init` always takes one — so nothing is generated without it.
    if data.is_empty() || clk.is_none() {
        return None;
    }
    Some((data, clk, valid))
}

/// `Some(has a valid pad)` when the parallel port is wired.
pub(crate) fn parl_io_wired(configured: &[&Pin]) -> Option<bool> {
    collect_parl_io(configured).map(|(_, _, v)| v.is_some())
}

/// The MCPWM outputs the canvas wires, by unit.
///
/// `(operator, is B)` per unit, in operator order then A before B — the order
/// the generated `init` declares its parameters in, so the call site and the
/// module cannot disagree about which pad is which.
fn collect_mcpwm<'a>(configured: &[&'a Pin]) -> BTreeMap<u8, Vec<(u8, bool, &'a Pin)>> {
    let mut out: BTreeMap<u8, Vec<(u8, bool, &Pin)>> = BTreeMap::new();
    for p in configured {
        let (unit, operator, b) = match p.selected_function {
            PinFunction::McpwmA { unit, operator } => (unit, operator, false),
            PinFunction::McpwmB { unit, operator } => (unit, operator, true),
            _ => continue,
        };
        out.entry(unit).or_default().push((operator, b, *p));
    }
    for v in out.values_mut() {
        v.sort_by_key(|(op, b, _)| (*op, *b));
    }
    out
}

/// `(unit, [(operator, is B)])` for every wired MCPWM unit.
pub(crate) fn mcpwm_outputs_wired(configured: &[&Pin]) -> Vec<(u8, Vec<(u8, bool)>)> {
    collect_mcpwm(configured)
        .into_iter()
        .map(|(u, outs)| (u, outs.into_iter().map(|(op, b, _)| (op, b)).collect()))
        .collect()
}

/// True when this chip's `esp-hal` has the USB Serial/JTAG driver.
///
/// # Why a list and not the metadata
///
/// The pads and the driver are different questions, and the answers differ on
/// two parts. Every chip here whose `UsbDm`/`UsbDp` pads exist gets them from
/// the vendor's analog list — including the ESP32-C61, which has the pads and
/// no `esp_hal::usb_serial_jtag` at all, and the ESP32-S2, whose USB pads
/// belong to a full OTG controller instead. Reading "has USB pads" as "can
/// build a USB Serial/JTAG" would generate `UsbSerialJtag::new` for both.
///
/// Kept here rather than on `EspChip` because this is the CODE generator and
/// the definition it works from carries pins, not driver names — the same
/// reason [`super::esp_clocks::max_mhz`] is a table keyed on the chip id.
/// Checked against the metadata by
/// [`tests::the_usb_serial_jtag_list_matches_esp_hal`].
pub(crate) fn has_usb_serial_jtag(chip: &str) -> bool {
    matches!(
        chip,
        "esp32c3" | "esp32c5" | "esp32c6" | "esp32h2" | "esp32s3"
    )
}

/// The PCNT units the canvas wires: the edge pad, and the ctrl pad if there is
/// one.
///
/// Keyed by UNIT. The edge pad is what makes a unit exist here — a ctrl pad on
/// its own counts nothing, and the module requires the edge signal, so this
/// keeps only the units that have one.
fn collect_pcnt<'a>(configured: &[&'a Pin]) -> BTreeMap<u8, (&'a Pin, Option<&'a Pin>)> {
    let mut edge: BTreeMap<u8, &Pin> = BTreeMap::new();
    let mut ctrl: BTreeMap<u8, &Pin> = BTreeMap::new();
    for p in configured {
        match p.selected_function {
            PinFunction::PcntEdge(n) => {
                edge.insert(n, *p);
            }
            PinFunction::PcntCtrl(n) => {
                ctrl.insert(n, *p);
            }
            _ => {}
        }
    }
    edge.into_iter()
        .map(|(n, e)| (n, (e, ctrl.get(&n).copied())))
        .collect()
}

/// `(unit, has a control pad)` for every wired PCNT unit.
///
/// The config-file list and `main.rs` are built from this same answer, so the
/// generated `init` can never take a `ctrl` argument the call does not pass.
pub(crate) fn pcnt_units_wired(configured: &[&Pin]) -> Vec<(u8, bool)> {
    collect_pcnt(configured)
        .into_iter()
        .map(|(n, (_, c))| (n, c.is_some()))
        .collect()
}

/// The RMT channels a set of pins wires, in channel order.
///
/// The config-file list and `main.rs` are built from this same answer, so a
/// channel can never get a file without a call or the other way round.
pub(crate) fn rmt_channels_wired(configured: &[&Pin]) -> Vec<u8> {
    collect_rmt(configured).into_keys().collect()
}

/// The I2S instances a set of pins wires, in instance order.
///
/// Public because the Configuration tab needs the same answer the code
/// generator gets: an I2S takes a DMA channel simply by being wired, with no
/// switch to consult, so the card and the generated project must count them the
/// same way or the card lies.
pub(crate) fn i2s_instances_wired(pins: &[&Pin]) -> Vec<u8> {
    let configured: Vec<&Pin> = pins
        .iter()
        .copied()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .collect();
    collect_buses(&configured).3.keys().copied().collect()
}

/// The order `i2s_file`'s `init` takes its pins in.
const I2S_ORDER: &[&str] = &["ck", "ws", "sd", "mck"];

/// `(instance, wired signals)` for each bus, in the order `init` takes them.
///
/// The SIGNALS matter as much as the instance: the generated `init` declares a
/// parameter per wired line, so a bus with no MISO gets a three-argument `init`
/// rather than one that ignores an argument — no unused-variable warnings in
/// the user's `main.rs`, and no pretending a pin is used when it is not. The
/// call site and the module are built from this same list, so they cannot
/// disagree.
pub fn bus_instances(configured: &[&Pin]) -> (BusWiring, BusWiring, BusWiring, BusWiring) {
    let (uart, spi, i2c, i2s_pins) = collect_buses(configured);
    let flatten = |b: BusPins, order: &[&'static str]| -> BusWiring {
        b.into_iter()
            .map(|(n, pins)| {
                let sigs = order
                    .iter()
                    .filter(|s| pins.contains_key(*s))
                    .copied()
                    .collect();
                (n, sigs)
            })
            .collect()
    };
    (
        flatten(uart, UART_ORDER),
        flatten(spi, SPI_ORDER),
        flatten(i2c, I2C_ORDER),
        flatten(i2s_pins, I2S_ORDER),
    )
}

/// `(instance, signals)` pairs — see [`bus_instances`].
pub type BusWiring = Vec<(u8, Vec<&'static str>)>;

/// Signal order for each bus: the order the pins are bound in `main.rs` and
/// declared in the generated `init`. One definition, used by both.
pub const UART_ORDER: &[&str] = &["rx", "tx"];
pub const SPI_ORDER: &[&str] = &["sck", "mosi", "miso", "cs"];
pub const I2C_ORDER: &[&str] = &["scl", "sda"];

/// `(section label, body)` for every wired bus instance: one `let` per pin,
/// then the `pins::configs::<bus><n>::init(…)` call that consumes them.
///
/// Signals the canvas did not wire are simply absent — `init` takes only what
/// its template declares (SCK+MOSI for SPI, both lines for UART/I2C), so a
/// Which GDMA channel each DMA-driven bus gets, and who has it.
///
/// # One channel, not two
///
/// Everywhere else in this IDE a bus on DMA takes a TX channel and an RX
/// channel. esp-hal does not work that way: `with_dma` (SPI) and `I2s::new`
/// take ONE channel, whose two halves (`DMA_IN_CHn` / `DMA_OUT_CHn`) the driver
/// drives together. So a bus here consumes a single entry, and a module's
/// hand-pinned `dma_tx` is read as "the channel" — `dma_rx` is not consulted.
///
/// # Order, and why I2S goes first
///
/// A SPI that gets no channel still generates: it falls back to the plain
/// blocking bus, and the config file written beside it agrees. An I2S that gets
/// no channel generates NOTHING — `I2s::new` takes a channel, there is no other
/// constructor — so it has the first claim on what is free.
///
/// Hand-pinned channels are reserved before either, exactly as on the STM32
/// path, so a choice made in one module is never handed to another.
pub(crate) struct DmaPlan {
    /// Keyed by SPI instance. Only the buses whose module asked for Async-DMA.
    pub spi: BTreeMap<u8, DmaUse>,
    /// Keyed by I2S instance. Every wired one, since I2S has no non-DMA form.
    pub i2s: BTreeMap<u8, DmaUse>,
    /// The parallel port, which is one per chip and also DMA-only.
    pub parl_io: Option<DmaUse>,
}

impl DmaPlan {
    /// Every channel taken, for the Configuration tab's DMA card.
    pub fn uses(&self) -> Vec<DmaUse> {
        self.parl_io
            .iter()
            .chain(self.i2s.values())
            .chain(self.spi.values())
            .cloned()
            .collect()
    }
}

pub(crate) fn dma_plan(
    dma: Option<&DmaDef>,
    runtime: EspRuntime,
    spi_cfg: &BTreeMap<u8, SpiModuleConfig>,
    // Every I2S instance the canvas wires. Unlike SPI there is nothing to opt
    // into: `I2s::new` takes a channel, so a wired I2S always wants one.
    i2s_wired: &[u8],
    // True when the canvas wires the parallel port.
    parl_io_wired: bool,
) -> DmaPlan {
    let mut plan = DmaPlan {
        spi: BTreeMap::new(),
        i2s: BTreeMap::new(),
        parl_io: None,
    };
    if runtime != EspRuntime::Async {
        return plan;
    }
    let Some(dma) = dma else {
        return plan;
    };
    let on_dma: Vec<u8> = spi_cfg
        .iter()
        .filter(|(_, c)| c.async_mode == AsyncBusMode::AsyncDma)
        .map(|(n, _)| *n)
        .collect();

    // Reserve every hand-pinned channel BEFORE allocating, so the allocator
    // cannot hand one of them to a different bus.
    let mut taken: Vec<String> = on_dma
        .iter()
        .filter_map(|n| spi_cfg.get(n))
        .map(|c| c.dma_tx.trim().to_owned())
        .filter(|c| !c.is_empty())
        .collect();

    // A pool offers every channel; a bolted DMA offers only the ones its
    // request table names for that peripheral.
    let mut claim = |request: String, manual: &str| -> Option<DmaUse> {
        let peri = if !manual.is_empty() {
            manual.to_owned()
        } else {
            let allowed: Vec<&str> = if dma.mux {
                dma.channels.iter().map(|c| c.peri.as_str()).collect()
            } else {
                dma.requests
                    .iter()
                    .find(|(req, _)| *req == request)
                    .map(|(_, chans)| chans.iter().map(String::as_str).collect())
                    .unwrap_or_default()
            };
            let free = allowed
                .into_iter()
                .find(|c| !taken.iter().any(|t| t == c))?;
            taken.push(free.to_owned());
            free.to_owned()
        };
        Some(DmaUse {
            peri,
            // esp-hal owns the DMA interrupt; no generated line names it.
            irq: String::new(),
            user: request,
            manual: !manual.is_empty(),
        })
    };

    for n in i2s_wired {
        if let Some(u) = claim(format!("I2S{n}"), "") {
            plan.i2s.insert(*n, u);
        }
    }
    // The parallel port is served with the I2S, and for the same reason: no
    // channel means no port at all, where a SPI merely loses its DMA.
    if parl_io_wired {
        plan.parl_io = claim("PARL_IO".to_owned(), "");
    }
    for n in on_dma {
        let manual = spi_cfg[&n].dma_tx.trim().to_owned();
        if let Some(u) = claim(format!("SPI{n}"), &manual) {
            plan.spi.insert(n, u);
        }
    }
    plan
}

/// half-wired bus is reported as a TODO comment rather than emitting a call
/// that would not compile.
fn bus_sections(
    configured: &[&Pin],
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi_cfg: &BTreeMap<u8, SpiModuleConfig>,
    i2c_cfg: &BTreeMap<u8, I2cModuleConfig>,
    i2s_cfg: &BTreeMap<u8, I2sModuleConfig>,
    rmt_cfg: &BTreeMap<u8, RmtModuleConfig>,
    pcnt_cfg: &BTreeMap<u8, PcntModuleConfig>,
    mcpwm_cfg: &BTreeMap<u8, McpwmModuleConfig>,
    parl_io_cfg: Option<&ParlIoModuleConfig>,
    // The RMT source clock, which `Rmt::new` takes as an argument.
    rmt_hz: u32,
    runtime: EspRuntime,
    // The channel each DMA-driven bus was given — see [`dma_plan`].
    dma_plan: &DmaPlan,
) -> Vec<(String, String)> {
    let (uart, spi, i2c, i2s_pins) = collect_buses(configured);
    let mut out = Vec::new();
    // Async runtime → call the `init_async` twin, so the handles are the
    // `.await`-able esp-hal drivers. `init` stays in the file for a bus the user
    // would rather keep blocking; switching is a one-word edit here.
    let init_fn = if runtime == EspRuntime::Async {
        "init_async"
    } else {
        "init"
    };

    // One `let` per wired pin, in `init`'s parameter order, returning the
    // binding names to pass along.
    let section = |pins: &BTreeMap<&'static str, &Pin>,
                   order: &[&'static str],
                   handle: String,
                   module: String,
                   periph: String,
                   // Appended after the pins, because that is where `init`
                   // takes it: the DMA channel, on a bus that asked for one.
                   tail: Option<String>| {
        let mut body = String::new();
        let mut args = Vec::new();
        for sig in order.iter().filter(|s| pins.contains_key(*s)) {
            let p = pins[sig];
            let var = esp_binding(p);
            body.push_str(&format!(
                "    let {var} = peripherals.{gpio}; // {label}\n",
                gpio = p.name,
                label = p.selected_function.label(),
            ));
            args.push(var);
        }
        args.extend(tail);
        body.push_str(&format!(
            "    let mut {handle} = pins::configs::{module}::{init_fn}({periph}, {});\n",
            args.join(", ")
        ));
        body
    };

    for (n, pins) in &uart {
        let sfx = usart
            .get(n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        out.push((
            format!("UART{n}"),
            section(
                pins,
                UART_ORDER,
                format!("_uart{n}{sfx}"),
                format!("uart{n}"),
                format!("peripherals.UART{n}"),
                None,
            ),
        ));
    }
    for (n, pins) in &spi {
        let sfx = spi_cfg
            .get(n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        out.push((
            format!("SPI{n}"),
            section(
                pins,
                SPI_ORDER,
                format!("_spi{n}{sfx}"),
                format!("spi{n}"),
                format!("peripherals.SPI{n}"),
                // A bus the allocator could not serve gets no channel and no
                // argument - and `init_async` without DMA is what the config
                // file then holds, so the two always agree.
                dma_plan
                    .spi
                    .get(n)
                    .map(|u| format!("peripherals.{}", u.peri)),
            ),
        ));
    }
    for (n, pins) in &i2c {
        let sfx = i2c_cfg
            .get(n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        out.push((
            format!("I2C{n}"),
            section(
                pins,
                I2C_ORDER,
                format!("_i2c{n}{sfx}"),
                format!("i2c{n}"),
                format!("peripherals.I2C{n}"),
                None,
            ),
        ));
    }
    // I2S last, and not through `section`: its `init` hands back a PAIR — the
    // driver and the ring buffer the DMA moves — so the binding is a tuple, and
    // a bus the allocator could not serve is skipped with a note rather than
    // called with an argument that does not exist.
    for (n, pins) in &i2s_pins {
        let sfx = i2s_cfg
            .get(n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        let handle = format!("_i2s{n}{sfx}");
        let mut body = String::new();
        let mut args = Vec::new();
        for sig in I2S_ORDER.iter().filter(|s| pins.contains_key(*s)) {
            let p = pins[sig];
            let var = esp_binding(p);
            body.push_str(&format!(
                "    let {var} = peripherals.{gpio}; // {label}\n",
                gpio = p.name,
                label = p.selected_function.label(),
            ));
            args.push(var);
        }
        match dma_plan.i2s.get(n) {
            Some(u) => body.push_str(&format!(
                "    let (mut {handle}, {handle}_buf) =\n\
                 \x20       pins::configs::i2s{n}::{init_fn}(peripherals.I2S{n}, peripherals.{}, {});\n",
                u.peri,
                args.join(", "),
            )),
            // No `init` call at all, because there is no constructor to call:
            // esp-hal's `I2s::new` takes a channel and there is no other form.
            None => body.push_str(&format!(
                "    // TODO: I2S{n} has no DMA channel left - every one is taken.\n\
                 \x20   // Free one in another module (Configuration tab shows who has what),\n\
                 \x20   // or pin this one by hand in the I2S module.\n"
            )),
        }
        out.push((format!("I2S{n}"), body));
    }
    // RMT last. One `Rmt::new` for the whole chip — the block is shared and the
    // channels are its fields — then one `let` per wired channel, exactly the
    // shape the LEDC takes for PWM.
    let rmt = collect_rmt(configured);
    if !rmt.is_empty() {
        let mut body = format!(
            "    let rmt = Rmt::new(peripherals.RMT, Rate::from_hz({rmt_hz}))\n\
             \x20       .unwrap(){};\n",
            if runtime == EspRuntime::Async {
                "\n\x20       .into_async()"
            } else {
                ""
            },
        );
        for (n, p) in &rmt {
            let sfx = rmt_cfg
                .get(n)
                .map(|c| module_label_sfx(&c.custom_label))
                .unwrap_or_default();
            let var = esp_binding(p);
            body.push_str(&format!(
                "    let {var} = peripherals.{gpio}; // {label}\n\
                 \x20   let mut _rmt{n}{sfx} =\n\
                 \x20       pins::configs::rmt{n}::{init_fn}(rmt.channel{n}, {var});\n",
                gpio = p.name,
                label = p.selected_function.label(),
            ));
        }
        out.push(("RMT".to_owned(), body));
    }
    // PCNT, the same shape again: one `Pcnt::new` for the chip, then one unit
    // lent to each config module.
    let pcnt = collect_pcnt(configured);
    if !pcnt.is_empty() {
        let mut body = String::from("    let pcnt = Pcnt::new(peripherals.PCNT);\n");
        for (n, (edge, ctrl)) in &pcnt {
            let sfx = pcnt_cfg
                .get(n)
                .map(|c| module_label_sfx(&c.custom_label))
                .unwrap_or_default();
            let ev = esp_binding(edge);
            body.push_str(&format!(
                "    let {ev} = peripherals.{gpio}; // {label}\n",
                gpio = edge.name,
                label = edge.selected_function.label(),
            ));
            let mut args = vec![ev];
            if let Some(c) = ctrl {
                let cv = esp_binding(c);
                body.push_str(&format!(
                    "    let {cv} = peripherals.{gpio}; // {label}\n",
                    gpio = c.name,
                    label = c.selected_function.label(),
                ));
                args.push(cv);
            }
            body.push_str(&format!(
                "    let {handle} =\n\
                 \x20       pins::configs::pcnt{n}::init(pcnt.unit{n}, {});\n",
                args.join(", "),
                handle = format!("_pcnt{n}{sfx}"),
            ));
        }
        out.push(("PCNT".to_owned(), body));
    }
    // PARL_IO. Like the I2S it is DMA-only, so a port with no channel left
    // produces a note rather than a call that could not be written.
    if let Some((data, clk, valid)) = collect_parl_io(configured) {
        let sfx = parl_io_cfg
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        let mut body = String::new();
        let mut args = Vec::new();
        let lanes = parl_io_cfg.map(|c| c.width.lanes()).unwrap_or(8);
        for lane in 0..lanes {
            let Some(p) = data.get(&lane) else {
                body.push_str(&format!(
                    "    // TODO: PARL_IO D{lane} is not assigned - the bus is {lanes} wide.\n"
                ));
                continue;
            };
            let var = esp_binding(p);
            body.push_str(&format!(
                "    let {var} = peripherals.{gpio}; // {label}\n",
                gpio = p.name,
                label = p.selected_function.label(),
            ));
            args.push(var);
        }
        for p in [clk, valid].into_iter().flatten() {
            // The valid pad is only an argument below sixteen bits; at sixteen
            // the signal rides the bus - see `parl_io_file`.
            if p.selected_function == PinFunction::ParlValid && lanes >= 16 {
                continue;
            }
            let var = esp_binding(p);
            body.push_str(&format!(
                "    let {var} = peripherals.{gpio}; // {label}\n",
                gpio = p.name,
                label = p.selected_function.label(),
            ));
            args.push(var);
        }
        match dma_plan.parl_io.as_ref() {
            Some(u) => body.push_str(&format!(
                "    let (mut _parl{sfx}, mut _parl{sfx}_buf) =\n\
                 \x20       pins::configs::parl_io::{init_fn}(peripherals.PARL_IO, peripherals.{}, {});\n",
                u.peri,
                args.join(", "),
            )),
            None => body.push_str(
                "    // TODO: the parallel port has no DMA channel left - every one is\n\
                 \x20   // taken. Free one in another module, or pin this one by hand.\n",
            ),
        }
        out.push(("PARL_IO".to_owned(), body));
    }
    // MCPWM last. The TIMER binding is not decorative: it owns the guard that
    // holds the peripheral clock on, so dropping it would silence every pin.
    for (unit, outs) in collect_mcpwm(configured) {
        let sfx = mcpwm_cfg
            .get(&unit)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        let mut body = String::new();
        let mut args = Vec::new();
        let mut handles = vec![format!("_mcpwm{unit}_timer{sfx}")];
        for (op, b, p) in &outs {
            let var = esp_binding(p);
            body.push_str(&format!(
                "    let {var} = peripherals.{gpio}; // {label}\n",
                gpio = p.name,
                label = p.selected_function.label(),
            ));
            args.push(var);
            handles.push(format!(
                "mut _mcpwm{unit}_op{op}{}{sfx}",
                if *b { "b" } else { "a" }
            ));
        }
        body.push_str(&format!(
            "    let ({}) =\n\
             \x20       pins::configs::mcpwm{unit}::init(peripherals.MCPWM{unit}, {});\n",
            handles.join(", "),
            args.join(", "),
        ));
        out.push((format!("MCPWM{unit}"), body));
    }
    out
}

/// `_<sanitized label>` suffix for a module's generated handle (`_uart1_imu`),
/// or "" when the module has no user label. Mirror of `stm32::module_label_sfx`.
fn module_label_sfx(label: &str) -> String {
    let s = sanitize_label(label);
    if s.is_empty() {
        String::new()
    } else {
        format!("_{s}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pwm_pin(name: &str, f: PinFunction) -> Pin {
        let mut p = Pin::new(1, name);
        p.selected_function = f;
        p
    }

    /// The LEDC is ONE peripheral for the whole chip, so `Ledc::new` belongs in
    /// `main.rs` — a per-timer config module could only build it once, and the
    /// second timer would have nothing to build from.
    #[test]
    fn the_ledc_is_built_once_in_main() {
        let mut pins = vec![
            pwm_pin(
                "GPIO19",
                PinFunction::TimerPwm {
                    timer: 0,
                    channel: 1,
                },
            ),
            pwm_pin(
                "GPIO18",
                PinFunction::TimerPwm {
                    timer: 0,
                    channel: 2,
                },
            ),
        ];
        let refs: Vec<&Pin> = pins.iter().collect();
        let mut timer = BTreeMap::new();
        let mut cfg = TimerModuleConfig::new(0);
        cfg.custom_label = "power led".into();
        timer.insert(0u8, cfg);
        let code = fresh_esp32c3_main_rs(
            &refs,
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &timer,
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert_eq!(
            code.matches("Ledc::new(peripherals.LEDC)").count(),
            1,
            "{code}"
        );
        assert!(code.contains("use esp_hal::ledc::Ledc;"), "{code}");
        // The pads keep their own `let … = peripherals.GPIOn;` lines: they are
        // the only record `parse_main_rs` rebuilds the diagram from.
        assert!(
            code.contains("let gpio19_tim0_ch1 = peripherals.GPIO19;"),
            "{code}"
        );
        assert!(
            code.contains("let gpio18_tim0_ch2 = peripherals.GPIO18;"),
            "{code}"
        );
        // The timer is a NAMED local — the channels borrow it for as long as
        // they live, so it cannot be a temporary.
        assert!(
            code.contains("let lstimer0 = pins::configs::pwm0::timer(&ledc);"),
            "{code}"
        );
        assert!(
            code.contains(
                "let mut _pwm0_power_led = pins::configs::pwm0::init(&ledc, &lstimer0, \
                 gpio19_tim0_ch1, gpio18_tim0_ch2);"
            ),
            "{code}"
        );
        // No PWM wired → no LEDC at all, and no stray import.
        pins.clear();
        pins.push(pwm_pin("GPIO8", PinFunction::GpioOutput));
        let refs: Vec<&Pin> = pins.iter().collect();
        let code = fresh_esp32c3_main_rs(
            &refs,
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert!(!code.contains("Ledc"), "{code}");
    }
    use crate::panels::mcu_module::clock::graph::NodeState;
    use crate::panels::mcu_module::clock::graph::{GraphClock, esp32c3_graph, esp32c3_layout};
    use crate::panels::mcu_module::codegen::parse_mcu_id;

    fn esp_graph_clock() -> GraphClock {
        GraphClock {
            graph: esp32c3_graph(),
            layout: esp32c3_layout(),
            bindings: Default::default(),
        }
    }

    fn no_usart() -> BTreeMap<u8, UsartModuleConfig> {
        BTreeMap::new()
    }

    fn no_spi() -> BTreeMap<u8, SpiModuleConfig> {
        BTreeMap::new()
    }

    fn no_i2c() -> BTreeMap<u8, I2cModuleConfig> {
        BTreeMap::new()
    }

    fn no_i2s() -> BTreeMap<u8, I2sModuleConfig> {
        BTreeMap::new()
    }

    fn no_rmt() -> BTreeMap<u8, RmtModuleConfig> {
        BTreeMap::new()
    }

    fn no_pcnt() -> BTreeMap<u8, PcntModuleConfig> {
        BTreeMap::new()
    }

    fn no_mcpwm() -> BTreeMap<u8, McpwmModuleConfig> {
        BTreeMap::new()
    }

    fn no_parl() -> BTreeMap<u8, ParlIoModuleConfig> {
        BTreeMap::new()
    }

    /// The ESP CPU clock chosen in the diagram drives the generated
    /// `with_cpu_clock(...)` (bug: previously hardcoded to `max()`).
    #[test]
    fn default_cpu_clock_is_160mhz() {
        let code = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::Graph(esp_graph_clock()),
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert!(
            code.contains("CpuClock::_160MHz"),
            "default ESP CPU = 160 MHz:\n{code}"
        );
    }

    #[test]
    fn cpu_div6_emits_80mhz() {
        let mut gc = esp_graph_clock();
        gc.graph.node_mut("cpu_div").unwrap().state = NodeState::Index(1); // ÷6 → 80 MHz
        let code = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::Graph(gc),
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert!(
            code.contains("CpuClock::_80MHz"),
            "ESP CPU ÷6 = 80 MHz:\n{code}"
        );
        assert!(!code.contains("_160MHz"));
    }

    /// A chip with no modelled clock keeps the previous `max()` default.
    #[test]
    fn none_clock_falls_back_to_max() {
        let code = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert!(code.contains("CpuClock::max()"), "{code}");
    }

    /// The MCU-id marker is emitted in the header and survives a re-splice, so a
    /// reopened project can restore the exact chip.
    #[test]
    fn id_marker_present_and_stable_across_update() {
        let fresh = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3-graph",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert_eq!(parse_mcu_id(&fresh).as_deref(), Some("esp32c3-graph"));
        let updated = update_esp32c3_main_rs(
            &fresh,
            &[],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3-graph",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert_eq!(parse_mcu_id(&updated).as_deref(), Some("esp32c3-graph"));
    }

    /// The provenance line names the REAL HAL version and runtime, and a
    /// re-splice refreshes it — including on a legacy file that still advertises
    /// the HAL its project was born with — without disturbing the user's own
    /// code above the markers.
    #[test]
    fn hal_header_line_tracks_version_and_runtime() {
        use crate::panels::mcu_module::project_gen::{ESP_HAL_REQ, ESP_RTOS_REQ};
        let hal = ESP_HAL_REQ.trim_start_matches(['~', '^', '=']);
        let blocking = fresh_esp32c3_main_rs(
            &[],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        assert!(
            blocking.contains(&format!("// MCU: ESP32-C3 | HAL: esp-hal {hal} (blocking)")),
            "{blocking}"
        );

        // Legacy file: stale HAL line, a hand-added `use`, no id marker.
        let legacy = blocking
            .replace(
                &format!("// MCU: ESP32-C3 | HAL: esp-hal {hal} (blocking)\n"),
                "// MCU: ESP32-C3 | HAL: esp-hal 0.22\n",
            )
            .replace("#![no_std]", "use my_crate::thing;\n#![no_std]");
        let updated = update_esp32c3_main_rs(
            &legacy,
            &[],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Async,
            None,
        );
        assert!(
            updated.contains(&format!(
                "// MCU: ESP32-C3 | HAL: esp-hal {hal} + esp-rtos {ESP_RTOS_REQ} (async)"
            )),
            "stale line rewritten for the async runtime:\n{updated}"
        );
        assert!(!updated.contains("esp-hal 0.22"), "{updated}");
        assert_eq!(updated.matches("// MCU: ").count(), 1, "no duplicate");
        assert!(
            updated.contains("use my_crate::thing;"),
            "user code above the markers survives:\n{updated}"
        );
        // The line keeps its position (right under the banner), not appended.
        let banner = updated
            .find("// Auto-generated by Embedded IDE")
            .expect("banner");
        let mcu_line = updated.find("// MCU: ").expect("mcu line");
        assert!(banner < mcu_line && mcu_line < updated.find("#![no_std]").unwrap());

        // Idempotent — a second pass is a no-op.
        let again = update_esp32c3_main_rs(
            &updated,
            &[],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &no_usart(),
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Async,
            None,
        );
        assert_eq!(again, updated, "re-splice must not churn the header");
    }

    /// Every bus builder chain must end in a bare `.with_xxx(...)` so its `;` is
    /// real code. The pin labels used to TRAIL the call — the terminating `;`
    /// landed inside that comment and the file stopped parsing
    /// ("expected `;`, found keyword `loop`"), on both runtimes.
    #[test]
    fn bus_chains_close_outside_the_pin_comments() {
        use crate::panels::mcu_module::pins::logic::pin::Pin;
        let pin = |num: usize, name: &str, f: PinFunction| {
            let mut p = Pin::new(num, name).with_functions(vec![f.clone()]);
            p.selected_function = f;
            p
        };
        let pins = [
            pin(28, "GPIO21", PinFunction::UsartTx(0)),
            pin(27, "GPIO20", PinFunction::UsartRx(0)),
            pin(9, "GPIO4", PinFunction::SpiSck(2)),
            pin(10, "GPIO5", PinFunction::SpiMosi(2)),
            pin(12, "GPIO6", PinFunction::SpiMiso(2)),
            pin(13, "GPIO7", PinFunction::SpiNss(2)),
            pin(14, "GPIO8", PinFunction::I2cScl(0)),
            pin(15, "GPIO9", PinFunction::I2cSda(0)),
        ];
        let refs: Vec<&Pin> = pins.iter().collect();

        for runtime in [EspRuntime::Blocking, EspRuntime::Async] {
            let code = fresh_esp32c3_main_rs(
                &refs,
                &ClockConfig::None,
                "ESP32-C3",
                "esp32c3",
                &no_usart(),
                &no_spi(),
                &no_i2c(),
                &no_i2s(),
                &no_rmt(),
                &no_pcnt(),
                &no_mcpwm(),
                &no_parl(),
                &Default::default(),
                "",
                "esp32c3",
                runtime,
                None,
            );
            for (i, line) in code.lines().enumerate() {
                if let Some((_, comment)) = line.split_once("//") {
                    assert!(
                        !comment.contains(';'),
                        "{runtime:?} line {}: `;` swallowed by a comment:\n{line}",
                        i + 1
                    );
                }
            }
            // Buses are no longer built here: main.rs binds the pins and calls
            // into `pins/configs/<bus>.rs` (see `codegen_esp_configs`).
            for head in ["Uart::new", "Spi::new", "I2c::new"] {
                assert!(
                    !code.contains(head),
                    "{runtime:?} builds {head} in main.rs, not in its config module:
{code}"
                );
            }
            // Async calls the `init_async` twin; Blocking the plain `init`.
            let init_fn = if runtime == EspRuntime::Async {
                "init_async"
            } else {
                "init"
            };
            for (module, periph) in [("uart0", "UART0"), ("spi2", "SPI2"), ("i2c0", "I2C0")] {
                let call = format!("pins::configs::{module}::{init_fn}(peripherals.{periph}");
                assert!(
                    code.contains(&call),
                    "{runtime:?} calls {call}:
{code}"
                );
            }
            // Every wired pin still has its own line — that is what a reopened
            // project reads back (see the round-trip test in `codegen::family`).
            for (var, gpio) in [
                ("gpio20_usart0_rx", "GPIO20"),
                ("gpio21_usart0_tx", "GPIO21"),
                ("gpio8_i2c0_scl", "GPIO8"),
            ] {
                assert!(
                    code.contains(&format!("let {var} = peripherals.{gpio};")),
                    "{runtime:?} binds {gpio}:
{code}"
                );
            }
        }
    }

    /// A wired _USART module sets the baud rate on the generated `Uart::new`.
    #[test]
    fn module_baud_drives_uart_config() {
        use crate::panels::mcu_module::pins::logic::pin::Pin;
        let mut tx = Pin::new(28, "GPIO21").with_functions(vec![PinFunction::UsartTx(0)]);
        tx.selected_function = PinFunction::UsartTx(0);
        let mut rx = Pin::new(27, "GPIO20").with_functions(vec![PinFunction::UsartRx(0)]);
        rx.selected_function = PinFunction::UsartRx(0);

        let mut usart = no_usart();
        let mut cfg = UsartModuleConfig::new(0);
        cfg.baud_rate = 9600;
        usart.insert(0, cfg);

        let code = fresh_esp32c3_main_rs(
            &[&tx, &rx],
            &ClockConfig::None,
            "ESP32-C3",
            "esp32c3",
            &usart,
            &no_spi(),
            &no_i2c(),
            &no_i2s(),
            &no_rmt(),
            &no_pcnt(),
            &no_mcpwm(),
            &no_parl(),
            &Default::default(),
            "",
            "esp32c3",
            EspRuntime::Blocking,
            None,
        );
        // The baud lives in the CONFIG MODULE now, not in main.rs — main.rs
        // only names the module. (The consts themselves are covered by
        // `codegen_esp_configs::tests::module_settings_land_inside_the_generated_block`.)
        assert!(
            code.contains("pins::configs::uart0::init(peripherals.UART0"),
            "main.rs calls the config module:
{code}"
        );
        assert!(
            !code.contains("with_baudrate"),
            "the baud is not in main.rs any more:
{code}"
        );
        // Both pins keep their own line, labelled — this is what a reopened
        // project parses back.
        assert!(code.contains("let gpio20_usart0_rx = peripherals.GPIO20; // USART0  RX"));
        assert!(code.contains("let gpio21_usart0_tx = peripherals.GPIO21; // USART0  TX"));
    }

    /// The hand-written USB Serial/JTAG list must match the vendor's own.
    ///
    /// Two parts make the difference worth pinning: the ESP32-C61 has the USB
    /// PADS and no driver, and the ESP32-S2's USB is a full OTG controller
    /// rather than a Serial/JTAG one. Read "has USB pads" as "can build this"
    /// and both get a `UsbSerialJtag::new` that does not compile.
    #[test]
    #[ignore]
    fn the_usb_serial_jtag_list_matches_esp_hal() {
        use crate::panels::mcu_module::esp_metadata::{self, RISCV_CHIPS};
        let dir = esp_metadata::vendor_dir().expect("esp-metadata");
        for id in RISCV_CHIPS.iter().chain(&["esp32", "esp32s2", "esp32s3"]) {
            let c = esp_metadata::load(&dir, id).expect("parses");
            let driver = c.drivers.iter().any(|d| d == "usb_serial_jtag");
            assert_eq!(
                has_usb_serial_jtag(id),
                driver,
                "{id}: the list and esp-hal disagree"
            );
        }
        // …and the two that have pads without a driver stay out.
        for id in ["esp32c61", "esp32s2"] {
            let c = esp_metadata::load(&dir, id).expect("parses");
            assert!(c.usb_pads().is_some(), "{id} has the pads");
            assert!(!has_usb_serial_jtag(id), "{id} must not be offered one");
        }
    }

    // ── DMA ──────────────────────────────────────────────────────────────────

    fn gdma(n: usize) -> DmaDef {
        DmaDef {
            mux: true,
            channels: (0..n)
                .map(
                    |i| crate::panels::mcu_module::codegen::dma_data::DmaChannel {
                        peri: format!("DMA_CH{i}"),
                        irq: String::new(),
                    },
                )
                .collect(),
            requests: Vec::new(),
        }
    }

    fn spi_on_dma(instance: u8) -> SpiModuleConfig {
        let mut c = SpiModuleConfig::new(instance);
        c.async_mode = AsyncBusMode::AsyncDma;
        c
    }

    /// A pool hands out free channels in instance order.
    #[test]
    fn gdma_channels_are_allocated_in_order() {
        let dma = gdma(3);
        let spi: BTreeMap<u8, SpiModuleConfig> =
            [(2u8, spi_on_dma(2)), (3u8, spi_on_dma(3))].into();
        let plan = dma_plan(Some(&dma), EspRuntime::Async, &spi, &[], false);
        assert_eq!(plan.spi[&2].peri, "DMA_CH0");
        assert_eq!(plan.spi[&3].peri, "DMA_CH1");
        assert!(plan.spi.values().all(|u| !u.manual && u.irq.is_empty()));
    }

    /// A hand-pinned channel is reserved BEFORE anything is allocated, so the
    /// bus emitted first cannot be handed the channel a later one asked for.
    #[test]
    fn a_pinned_channel_is_never_allocated_to_another_bus() {
        let dma = gdma(3);
        let mut later = spi_on_dma(3);
        later.dma_tx = "DMA_CH0".into();
        let spi: BTreeMap<u8, SpiModuleConfig> = [(2u8, spi_on_dma(2)), (3u8, later)].into();
        let plan = dma_plan(Some(&dma), EspRuntime::Async, &spi, &[], false);
        assert_eq!(plan.spi[&3].peri, "DMA_CH0", "the pinned one is honoured");
        assert!(plan.spi[&3].manual);
        assert_eq!(
            plan.spi[&2].peri, "DMA_CH1",
            "and SPI2 had to take the next"
        );
    }

    /// On the original ESP32 a channel is bolted to one peripheral, so SPI3 may
    /// only ever be given `DMA_SPI3` — never the first free channel.
    #[test]
    fn a_bolted_channel_follows_the_request_table() {
        let dma = DmaDef {
            mux: false,
            channels: ["DMA_SPI2", "DMA_SPI3", "DMA_I2S0"]
                .iter()
                .map(
                    |p| crate::panels::mcu_module::codegen::dma_data::DmaChannel {
                        peri: (*p).to_owned(),
                        irq: String::new(),
                    },
                )
                .collect(),
            requests: vec![
                ("SPI2".into(), vec!["DMA_SPI2".into()]),
                ("SPI3".into(), vec!["DMA_SPI3".into()]),
            ],
        };
        let spi: BTreeMap<u8, SpiModuleConfig> = [(3u8, spi_on_dma(3))].into();
        let plan = dma_plan(Some(&dma), EspRuntime::Async, &spi, &[], false);
        assert_eq!(plan.spi[&3].peri, "DMA_SPI3");
    }

    /// More DMA buses than channels: the ones that fit are served and the rest
    /// get nothing — rather than every bus being handed `DMA_CH0`.
    #[test]
    fn a_bus_with_no_channel_left_gets_none() {
        let dma = gdma(1);
        let spi: BTreeMap<u8, SpiModuleConfig> =
            [(2u8, spi_on_dma(2)), (3u8, spi_on_dma(3))].into();
        let plan = dma_plan(Some(&dma), EspRuntime::Async, &spi, &[], false);
        assert_eq!(plan.spi[&2].peri, "DMA_CH0");
        assert!(!plan.spi.contains_key(&3));
    }

    /// The switch is an ASYNC one. A blocking project ignores it entirely —
    /// esp-hal's DMA surface is on the async drivers.
    #[test]
    fn the_blocking_runtime_allocates_nothing() {
        let dma = gdma(3);
        let spi: BTreeMap<u8, SpiModuleConfig> = [(2u8, spi_on_dma(2))].into();
        assert!(
            dma_plan(Some(&dma), EspRuntime::Blocking, &spi, &[], false)
                .uses()
                .is_empty()
        );
        // …and a chip with no channel data cannot be served on any runtime.
        assert!(
            dma_plan(None, EspRuntime::Async, &spi, &[], false)
                .uses()
                .is_empty()
        );
    }

    /// A SPI that did NOT ask for DMA takes no channel, so the two paths never
    /// disagree about how many arguments `init_async` has.
    #[test]
    fn a_bus_that_did_not_ask_for_dma_takes_no_channel() {
        let dma = gdma(3);
        let spi: BTreeMap<u8, SpiModuleConfig> = [(2u8, SpiModuleConfig::new(2))].into();
        assert!(
            dma_plan(Some(&dma), EspRuntime::Async, &spi, &[], false)
                .uses()
                .is_empty()
        );
    }
}
