//! Generates a complete, buildable Cargo project from the current pin configuration.
//!
//! Output layout for RustEmbedded (STM32/ARM):
//! ```
//! <dest>/
//! ├── .cargo/
//! │   └── config.toml      — build target + linker flags + probe-rs runner
//! ├── src/
//! │   └── main.rs          — HAL code generated by codegen.rs
//! ├── .gitignore
//! ├── build.rs             — copies memory.x to OUT_DIR
//! ├── Cargo.toml
//! └── memory.x             — flash / RAM layout for this MCU
//! ```
//!
//! Output layout for EspRust (ESP32-C3):
//! ```
//! <dest>/
//! ├── .cargo/
//! │   └── config.toml      — target + build-std + espflash runner
//! ├── src/
//! │   └── main.rs          — esp-hal code
//! ├── .gitignore
//! └── Cargo.toml
//! ```
//! No `memory.x` or `build.rs` — esp-hal 0.23 generates both `memory.x` and
//! `linkall.x` in its own OUT_DIR via its build script.  Only `-Tlinkall.x` is
//! needed in rustflags; adding a second `-Tmemory.x` redefines IROM/DROM/etc.
//! and causes a linker error ("region already defined").

use super::mcu_catalog::ToolchainKind;
use super::mcu_def::ProjectDef;
use std::{fs, io, path::Path};

// ── Public types ──────────────────────────────────────────────────────────────

/// All generated file contents for one project snapshot.
/// Cheap to build (pure string formatting); regenerated every UI frame.
#[derive(Clone)]
pub struct ProjectFiles {
    pub main_rs: String,
    pub cargo_toml: String,
    pub cargo_config: String,
    pub memory_x: String, // empty for EspRust
    pub build_rs: String, // empty for EspRust
    pub gitignore: String,
}

// ── Generated-block markers (per comment style) ────────────────────────────────
//
// Every generated config file carries its chip-derived content inside a
// `<<< GENERATED >>> … <<< GENERATED END >>>` block, written with the comment
// syntax of that file. Anything the user adds outside the block is preserved
// when the block is refreshed (e.g. on a chip change) — the same contract as the
// GEN_BEGIN…GEN_END block in `main.rs`.

/// Comment syntax of a config file, used to frame the generated block.
#[derive(Clone, Copy)]
enum Cmt {
    /// `//` line comments — Rust (`build.rs`).
    Slash,
    /// `#` line comments — TOML, `.gitignore`.
    Hash,
    /// `/* … */` block comments — GNU ld linker script (`memory.x`).
    Block,
}

impl Cmt {
    fn begin(self) -> &'static str {
        match self {
            Cmt::Slash => "// <<< GENERATED — do not edit inside this block >>>",
            Cmt::Hash => "# <<< GENERATED — do not edit inside this block >>>",
            Cmt::Block => "/* <<< GENERATED — do not edit inside this block >>> */",
        }
    }
    fn end(self) -> &'static str {
        match self {
            Cmt::Slash => "// <<< GENERATED END >>>",
            Cmt::Hash => "# <<< GENERATED END >>>",
            Cmt::Block => "/* <<< GENERATED END >>> */",
        }
    }
    /// The user-editable tail invitation placed below the block on first build.
    fn tail(self) -> &'static str {
        match self {
            Cmt::Slash => {
                "// Add your own code below — preserved when the block above is refreshed.\n"
            }
            Cmt::Hash => {
                "# Add your own entries below — preserved when the block above is refreshed.\n"
            }
            Cmt::Block => {
                "/* Add your own entries below — preserved when the block above is refreshed. */\n"
            }
        }
    }
}

/// The framed generated block (`begin … body … end`); `body` must end in `\n`.
fn gen_block(style: Cmt, body: &str) -> String {
    format!("{}\n{}{}", style.begin(), body, style.end())
}

/// First-time file layout: the generated block followed by a user-editable tail.
fn initial_file(style: Cmt, body: &str) -> String {
    format!("{}\n{}", gen_block(style, body), style.tail())
}

/// Refresh the generated block in `existing`, preserving everything the user
/// added before or after the markers. Falls back to a fresh layout when the
/// markers are missing (legacy or hand-cleared file).
fn splice_block(existing: &str, style: Cmt, body: &str) -> String {
    let (begin, end) = (style.begin(), style.end());
    if let (Some(b), Some(e)) = (existing.find(begin), existing.find(end)) {
        if b < e {
            let before = &existing[..b];
            // Trim leading newlines after the end marker, then re-add exactly one
            // so repeated splices are idempotent (no blank-line creep).
            let after = existing[e + end.len()..].trim_start_matches('\n');
            return format!("{before}{}\n{after}", gen_block(style, body));
        }
    }
    if existing.trim().is_empty() {
        initial_file(style, body)
    } else {
        // Non-empty but no markers — an externally-authored file (or one whose
        // markers the user removed). Leave it untouched: the IDE only manages a
        // block in files it generated itself, so it never duplicates a hand-
        // written `[package]`/MEMORY/etc.
        existing.to_owned()
    }
}

/// The five generated project files that live at the project root (outside
/// `src/`). Each maps to a [`ProjectFileId`](crate::app::ProjectFileId).
#[derive(Clone, Copy)]
pub enum ConfigFile {
    CargoToml,
    CargoConfig,
    MemoryX,
    BuildRs,
    GitIgnore,
}

impl ConfigFile {
    /// The generated body + comment style for this file, or `None` when the file
    /// does not apply to the toolchain (e.g. `memory.x`/`build.rs` for ESP, which
    /// esp-hal supplies itself).
    fn body(self, c: &ProjectDef, toolchain: &ToolchainKind) -> Option<(Cmt, String)> {
        use ToolchainKind::{EspRust, RustEmbedded};
        match self {
            ConfigFile::CargoToml => match toolchain {
                RustEmbedded => Some((Cmt::Hash, cargo_toml_embedded(c))),
                EspRust => Some((Cmt::Hash, cargo_toml_esp(c))),
                _ => None,
            },
            ConfigFile::CargoConfig => match toolchain {
                RustEmbedded => Some((Cmt::Hash, cargo_config_embedded(c))),
                EspRust => Some((Cmt::Hash, cargo_config_esp(c))),
                _ => None,
            },
            ConfigFile::MemoryX => match toolchain {
                RustEmbedded => Some((Cmt::Block, memory_x(c))),
                _ => None,
            },
            ConfigFile::BuildRs => match toolchain {
                RustEmbedded => Some((Cmt::Slash, build_rs_embedded())),
                _ => None,
            },
            // `project_structure.config` is per-user view state (node positions
            // in the Structure diagram) — it changes on every drag, so it is
            // ignored rather than committed. `mcu.config` IS committed: it is
            // real configuration.
            ConfigFile::GitIgnore => Some((
                Cmt::Hash,
                format!(
                    "/target\n{}\n",
                    crate::panels::mcu_module::structure_config::FILE_NAME
                ),
            )),
        }
    }
}

/// Fresh full content for a config file (generated block + user tail), or an
/// empty string when the file does not apply to the toolchain.
pub fn gen_config(file: ConfigFile, c: &ProjectDef, toolchain: &ToolchainKind) -> String {
    file.body(c, toolchain)
        .map(|(style, body)| initial_file(style, &body))
        .unwrap_or_default()
}

/// Refresh the generated block of an already-edited config file, preserving the
/// user's surrounding edits. Empty string when the file does not apply.
pub fn splice_config(
    file: ConfigFile,
    existing: &str,
    c: &ProjectDef,
    toolchain: &ToolchainKind,
) -> String {
    file.body(c, toolchain)
        .map(|(style, body)| splice_block(existing, style, &body))
        .unwrap_or_default()
}

/// `true` when Cargo.toml line `line` declares the dependency `name`
/// (`name = …`), tolerating leading whitespace and any spacing around `=`.
fn is_dep_line(line: &str, name: &str) -> bool {
    line.trim_start()
        .strip_prefix(name)
        .map(|rest| rest.trim_start().starts_with('='))
        .unwrap_or(false)
}

/// Insert `add_lines` right after the `[dependencies]` header when `add`, or
/// drop every line matching `names` when `!add`. Idempotent + newline-preserving
/// — the shared engine behind the peripheral dep syncs. The caller pre-checks
/// the desired state (via a marker dep) so this only runs on a real transition.
fn edit_dep_lines(cargo_toml: &str, add: bool, names: &[&str], add_lines: &[&str]) -> String {
    let mut out: Vec<String> = Vec::new();
    let mut inserted = false;
    for line in cargo_toml.lines() {
        if !add && names.iter().any(|n| is_dep_line(line, n)) {
            continue; // feature gone → drop the deps we added
        }
        out.push(line.to_string());
        if add && !inserted && line.trim() == "[dependencies]" {
            out.extend(add_lines.iter().map(|s| s.to_string()));
            inserted = true;
        }
    }
    let mut s = out.join("\n");
    if cargo_toml.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Ensure a single dependency `name` is present iff `needs`. Idempotent — a
/// no-op when already in the desired state (no mtime churn). `is_dep_line`'s `=`
/// check keeps `embedded-hal` distinct from `embedded-hal-0-2`.
fn ensure_dep(cargo_toml: &str, name: &str, needs: bool, add_line: &str) -> String {
    let has = cargo_toml.lines().any(|l| is_dep_line(l, name));
    if needs == has {
        return cargo_toml.to_owned();
    }
    edit_dep_lines(cargo_toml, needs, &[name], &[add_line])
}

/// The single authority for the peripheral-driven `[dependencies]` lines, keyed
/// on which peripherals are configured. Idempotent (called every frame from
/// `init_frame`). Deps are SHARED across peripherals (`embedded-hal-0-2` by
/// USART+SPI+I2C, `nb` by CAN+USART+SPI), so managing them in ONE place — rather
/// than per-feature functions — is what stops two features fighting over the same
/// line (add/remove churn). `nb`-note: SPI's `SpiBus` bridge uses `nb` for the
/// per-byte FullDuplex path; the I2C bridge does not.
///
/// - `bxcan`            — CAN (`can1.rs`)
/// - `embedded-io`      — USART (`usart*.rs` exposes the port as embedded-io)
/// - `embedded-hal-0-2` — USART/SPI/I2C bridges (the HAL is on embedded-hal 0.2;
///   the package alias frees the `embedded-hal` name for the 1.0 traits below)
/// - `embedded-hal` 1.0 — SPI (`SpiBus`) + I2C (`I2c`) portable traits
/// - `nb`               — CAN + USART + SPI (`nb::block!`)
pub fn ensure_peripheral_deps(
    cargo_toml: &str,
    needs_can: bool,
    needs_usart: bool,
    needs_spi: bool,
    needs_i2c: bool,
    needs_gpio: bool,
) -> String {
    let eh1 = needs_spi || needs_i2c || needs_gpio; // SpiBus / I2c / OutputPin…
    let eh02 = needs_usart || eh1; // every bridge speaks to the HAL's eh 0.2
    let mut s = cargo_toml.to_owned();
    s = ensure_dep(&s, "bxcan", needs_can, "bxcan = \"0.7\"");
    s = ensure_dep(&s, "embedded-io", needs_usart, "embedded-io  = \"0.6\"");
    s = ensure_dep(
        &s,
        "embedded-hal-0-2",
        eh02,
        "embedded-hal-0-2 = { package = \"embedded-hal\", version = \"0.2.7\", features = [\"unproven\"] }",
    );
    s = ensure_dep(&s, "embedded-hal", eh1, "embedded-hal = \"1.0\"");
    // nb: CAN, USART, and the SPI SpiBus bridge (FullDuplex) — NOT I2C or GPIO.
    s = ensure_dep(&s, "nb", needs_can || needs_usart || needs_spi, "nb           = \"1\"");
    s
}

/// Add or remove the `usb-device` + `usbd-serial` dependencies AND the
/// `stm32-usbd` feature on the `stm32f1xx-hal` line, driven by whether a USB
/// peripheral is configured. Like [`ensure_can_deps`], idempotent and called
/// every frame — the generated USB CDC init needs both crates and the HAL
/// feature (which exposes `stm32f1xx_hal::usb`).
pub fn ensure_usb_deps(cargo_toml: &str, needs_usb: bool) -> String {
    let is_dep = |line: &str, name: &str| {
        line.trim_start()
            .strip_prefix(name)
            .map(|rest| rest.trim_start().starts_with('='))
            .unwrap_or(false)
    };
    let is_hal = |line: &str| line.trim_start().starts_with("stm32f1xx-hal");
    let has_usb_dep = cargo_toml.lines().any(|l| is_dep(l, "usb-device"));
    let has_feature = cargo_toml
        .lines()
        .any(|l| is_hal(l) && l.contains("\"stm32-usbd\""));
    if needs_usb == has_usb_dep && needs_usb == has_feature {
        return cargo_toml.to_owned(); // already in the desired state
    }

    let mut out: Vec<String> = Vec::new();
    let mut inserted = false;
    for line in cargo_toml.lines() {
        if !needs_usb && (is_dep(line, "usb-device") || is_dep(line, "usbd-serial")) {
            continue; // USB gone → drop the deps we added
        }
        // Toggle the `stm32-usbd` HAL feature inside the `features = [ … ]` array.
        if is_hal(line) && line.contains("features = [") {
            out.push(toggle_hal_feature(line, "stm32-usbd", needs_usb));
            continue;
        }
        out.push(line.to_string());
        if needs_usb && !inserted && line.trim() == "[dependencies]" {
            // Versions matched to stm32f1xx-hal 0.10's `usb` module (stm32-usbd),
            // which targets usb-device 0.2 / usbd-serial 0.1 (`.product()` API).
            out.push("usb-device  = \"0.2\"".to_string());
            out.push("usbd-serial = \"0.1\"".to_string());
            inserted = true;
        }
    }
    let mut s = out.join("\n");
    if cargo_toml.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Add or remove the embassy async-runtime deps, driven by whether the project
/// Runtime is Async (on an embassy-capable STM32). Manages `embassy-executor`
/// (the `#[embassy_executor::main]` entry) + `embassy-time`, toggles the
/// `time-driver-any` feature on the `embassy-stm32` line (embassy-time needs a
/// time driver, which the HAL supplies), and — when an async USART config file
/// exists (`needs_async_usart`) — adds `embedded-io-async` (the portable async
/// serial traits) + `static_cell` (the `BufferedUart` ring buffers). Idempotent +
/// newline-preserving (called every frame from `init_frame`). The executor's
/// `critical-section-single-core` impl is already pulled by `cortex-m` in the
/// base Cargo.toml.
pub fn ensure_async_deps(
    cargo_toml: &str,
    needs_async: bool,
    needs_async_usart: bool,
    needs_eh: bool,
    needs_eh_async: bool,
) -> String {
    let mut s = ensure_dep(
        cargo_toml,
        "embassy-executor",
        needs_async,
        "embassy-executor = { version = \"0.9\", features = [\"arch-cortex-m\", \"executor-thread\"] }",
    );
    s = ensure_dep(&s, "embassy-time", needs_async, "embassy-time = \"0.5\"");
    // Async USART (`BufferedUart` → embedded-io-async). NB the crate is published
    // as `static_cell` (underscore) — a `static-cell` key fails to resolve.
    s = ensure_dep(&s, "embedded-io-async", needs_async_usart, "embedded-io-async = \"0.6\"");
    s = ensure_dep(&s, "static_cell", needs_async_usart, "static_cell = \"2\"");
    // Async SPI/I2C: blocking init → `embedded-hal` 1.0 (SpiBus/I2c); async-DMA
    // init → `embedded-hal-async` (which builds on the 1.0 ErrorType, so eh is
    // kept whenever any SPI/I2C exists).
    s = ensure_dep(&s, "embedded-hal", needs_eh, "embedded-hal = \"1.0\"");
    s = ensure_dep(&s, "embedded-hal-async", needs_eh_async, "embedded-hal-async = \"1.0\"");

    // Toggle the `time-driver-any` HAL feature inside the `embassy-stm32`
    // `features = [ … ]` array. A no-op for non-embassy projects — async is only
    // offered where an `embassy-stm32` line exists.
    let is_embassy = |line: &str| line.trim_start().starts_with("embassy-stm32");
    let has_driver = s
        .lines()
        .any(|l| is_embassy(l) && l.contains("\"time-driver-any\""));
    if needs_async != has_driver {
        let mut out: Vec<String> = Vec::new();
        for line in s.lines() {
            if is_embassy(line) && line.contains("features = [") {
                out.push(toggle_hal_feature(line, "time-driver-any", needs_async));
            } else {
                out.push(line.to_string());
            }
        }
        let mut joined = out.join("\n");
        if s.ends_with('\n') {
            joined.push('\n');
        }
        s = joined;
    }
    s
}

/// Add or remove `"feature"` inside the `features = [ … ]` array of a single
/// dependency `line`, idempotently.
fn toggle_hal_feature(line: &str, feature: &str, add: bool) -> String {
    let quoted = format!("\"{feature}\"");
    let present = line.contains(&quoted);
    if add == present {
        return line.to_string();
    }
    if add {
        // Insert right after the opening bracket: `features = [` → `… ["feat", `.
        line.replacen("features = [", &format!("features = [{quoted}, "), 1)
    } else {
        // Remove the entry plus its trailing or leading separator.
        line.replace(&format!("{quoted}, "), "")
            .replace(&format!(", {quoted}"), "")
            .replace(&quoted, "")
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Builds all file contents in memory without touching the filesystem.
pub fn build_project_files(
    config: &ProjectDef,
    toolchain: &ToolchainKind,
    main_rs: &str,
) -> ProjectFiles {
    // Each config file carries its chip-derived content in a `<<< GENERATED >>>`
    // block (`gen_config` frames it with the file's comment syntax and returns
    // an empty string for files the toolchain doesn't use, e.g. memory.x/build.rs
    // on ESP, where esp-hal supplies them itself).
    ProjectFiles {
        main_rs: main_rs.to_owned(),
        cargo_toml: gen_config(ConfigFile::CargoToml, config, toolchain),
        cargo_config: gen_config(ConfigFile::CargoConfig, config, toolchain),
        memory_x: gen_config(ConfigFile::MemoryX, config, toolchain),
        build_rs: gen_config(ConfigFile::BuildRs, config, toolchain),
        gitignore: gen_config(ConfigFile::GitIgnore, config, toolchain),
    }
}

/// Writes the given project `files` into `dest` (creating the directory tree as
/// needed). `files` carries the *current* (possibly user-edited) content of each
/// generated file, so edits made in the IDE are written verbatim rather than
/// regenerated. `user_src_files` is a list of `(path_relative_to_src, content)`
/// pairs. A file with empty content (e.g. `memory.x`/`build.rs` on ESP) is not
/// written.
pub fn write_project(
    dest: &Path,
    files: &ProjectFiles,
    user_src_files: &[(String, String)],
    mcu_config: &str,
    // `project_structure.config` — Structure-tab view state, kept out of
    // `mcu.config` so node drags don't show up as config changes in Git.
    structure_config: &str,
) -> io::Result<()> {
    fs::create_dir_all(dest.join("src"))?;
    fs::create_dir_all(dest.join(".cargo"))?;

    // ── Remove stale .rs files from src/ ─────────────────────────────────────
    // When the user switches between chip types (e.g. STM32 → ESP32-C3), the
    // workspace directory still contains .rs files written during the previous
    // build (e.g. src/lib.rs with `use stm32f1xx_hal`).  Those stale files are
    // not part of the new project, but `cargo check` picks them up and fails.
    //
    // Build the authoritative set of paths that SHOULD exist inside src/:
    // main.rs (always generated) + every user source file.
    // Paths are relative to the PROJECT ROOT, so the keep-set covers the
    // firmware's src/ AND every library crate's sources in one pass. Pruning
    // walks from the root but skips `target/` — a member crate may have built
    // there, and walking it would be slow and pointless.
    let expected: std::collections::HashSet<String> = user_src_files
        .iter()
        .map(|(p, _)| p.clone())
        .chain(std::iter::once("src/main.rs".to_string()))
        .chain(std::iter::once("build.rs".to_string()))
        .collect();
    remove_stale_rs(dest, dest, &expected);

    // NOTE: Cargo.lock is intentionally NOT deleted here. Re-resolving the
    // dependency graph on every save made saving slow (cargo re-solves the
    // version graph before each check). The lock is reset only when the
    // chip/toolchain changes — see `AppIde::reset_workspace_lock`.

    // Files common to all toolchains. Written ONLY when changed (see
    // `write_if_changed`) so unchanged files keep their mtimes and neither
    // cargo nor rust-analyzer re-processes them.
    write_if_changed(&dest.join("Cargo.toml"), files.cargo_toml.as_bytes())?;
    write_if_changed(
        &dest.join(".cargo").join("config.toml"),
        files.cargo_config.as_bytes(),
    )?;
    write_if_changed(&dest.join("src").join("main.rs"), files.main_rs.as_bytes())?;
    write_if_changed(&dest.join(".gitignore"), files.gitignore.as_bytes())?;

    // memory.x + build.rs — only for RustEmbedded (STM32/ARM).
    //
    // For EspRust: esp-hal 0.23 generates its own complete memory.x (with
    // IROM, DROM, IRAM, DRAM, RTC_FAST) in its build-script OUT_DIR.
    // linkall.x starts with `INCLUDE "memory.x"` and searches the linker
    // -L paths in order.  If a project-level memory.x is present (from a
    // previous build or toolchain switch), it shadows esp-hal's file, causing
    // either "IROM already defined" (if -Tmemory.x is also present) or
    // missing regions (if the stale file is incomplete).
    // → Delete stale copies for ESP; write-if-changed for RustEmbedded.
    //   (The old remove-then-rewrite bumped build.rs's mtime on EVERY call,
    //   which made cargo RE-RUN the build script — and therefore re-check the
    //   whole crate — on every Save/Build/Clippy.)
    if files.memory_x.is_empty() {
        let _ = fs::remove_file(dest.join("memory.x"));
        let _ = fs::remove_file(dest.join("build.rs"));
    } else {
        write_if_changed(&dest.join("memory.x"), files.memory_x.as_bytes())?;
        write_if_changed(&dest.join("build.rs"), files.build_rs.as_bytes())?;
    }

    // User source files — root-relative, so this also writes the sources of
    // every extracted library crate.
    for (rel_path, content) in user_src_files {
        let full = dest.join(rel_path);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent)?;
        }
        write_if_changed(&full, content.as_bytes())?;
    }

    // mcu.config — virtual modules + clock state, persisted out-of-source at the
    // project root (not in src/, so the project tree doesn't show it). Written
    // only when there's something to persist; a stale one is removed otherwise.
    let mcu_config_path = dest.join(crate::panels::mcu_module::mcu_config::FILE_NAME);
    if mcu_config.trim().is_empty() {
        let _ = fs::remove_file(&mcu_config_path);
    } else {
        write_if_changed(&mcu_config_path, mcu_config.as_bytes())?;
    }

    // project_structure.config — same deal, but view state rather than config:
    // gitignored, and removed when there is nothing left to remember.
    let structure_path = dest.join(crate::panels::mcu_module::structure_config::FILE_NAME);
    if structure_config.trim().is_empty() {
        let _ = fs::remove_file(&structure_path);
    } else {
        write_if_changed(&structure_path, structure_config.as_bytes())?;
    }

    // ── Library crates left by ANOTHER project (build workspace only) ────────
    // The build workspace is a single directory shared by every project ever
    // opened, so a crate extracted elsewhere stays behind and accumulates —
    // eventually confusing cargo or rust-analyzer.
    //
    // Guarded by an exact path match against `build_workspace_dir()`, and
    // deliberately NOT extended to the user's project: a crate they created but
    // have not yet listed in `[workspace] members` is indistinguishable from
    // debris, and deleting it would be exactly the data loss this feature just
    // learned to avoid. If the comparison ever fails we simply skip the prune —
    // the safe direction.
    if dest == build_workspace_dir() {
        prune_foreign_crates(dest, &workspace_members(&files.cargo_toml));
    }

    Ok(())
}

/// Absolute path of the throw-away workspace every build / check / flash / size
/// run uses. It is a COPY of the project — the only place where deleting files
/// that don't belong to the current project is safe.
pub fn build_workspace_dir() -> std::path::PathBuf {
    std::env::temp_dir().join("embedded_ide_0_check")
}

/// Delete top-level directories of `root` that hold a `Cargo.toml` but are not
/// workspace `members` — library crates left behind by a DIFFERENT project.
///
/// The caller must guarantee `root` is disposable; see the call site. `src`,
/// `target`, `.cargo` and `.git` are never touched.
fn prune_foreign_crates(root: &Path, members: &[String]) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if matches!(name.as_str(), "src" | "target" | ".cargo" | ".git") {
            continue;
        }
        // Only crate roots are candidates — a plain folder is not ours to judge.
        if !path.join("Cargo.toml").is_file() {
            continue;
        }
        // A member may be nested (`crates/foo`); its first segment protects the
        // whole branch.
        let is_member = members
            .iter()
            .any(|m| m == &name || m.split('/').next() == Some(name.as_str()));
        if !is_member {
            let _ = fs::remove_dir_all(&path);
        }
    }
}

/// Directory names listed in the root manifest's `[workspace] members = [...]`.
/// Hand-parsed (no toml dependency): track the current `[section]`, then read
/// every quoted string in the `members` value, which may span lines.
pub fn workspace_members(cargo_toml: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_workspace = false;
    let mut collecting = false;
    for line in cargo_toml.lines() {
        let t = line.trim();
        if t.starts_with('[') && !collecting {
            // `[workspace.package]` etc. are not the members list.
            in_workspace = t == "[workspace]";
            continue;
        }
        if !in_workspace {
            continue;
        }
        if !collecting {
            let Some(rest) = t.strip_prefix("members") else {
                continue;
            };
            if !rest.trim_start().starts_with('=') {
                continue;
            }
            collecting = true;
            push_quoted(rest, &mut out);
        } else {
            push_quoted(t, &mut out);
        }
        if t.contains(']') {
            collecting = false;
            in_workspace = false; // one members list is enough
        }
    }
    out
}

/// Append every `"..."` substring of `s` to `out`.
fn push_quoted(s: &str, out: &mut Vec<String>) {
    let mut rest = s;
    while let Some(open) = rest.find('"') {
        let after = &rest[open + 1..];
        let Some(close) = after.find('"') else { return };
        let val = &after[..close];
        if !val.is_empty() {
            out.push(val.to_owned());
        }
        rest = &after[close + 1..];
    }
}


/// Write `content` to `path` ONLY when it differs from what's already on disk.
/// Keeping unchanged files' mtimes stable is critical: a changed mtime makes
/// cargo re-fingerprint the file (and for `build.rs`, re-run the build script →
/// re-check the whole crate) and makes rust-analyzer's VFS re-read and
/// re-analyze it — so blindly rewriting every file on every Save/Build/Clippy
/// was a main driver of the "everything gets slower over a session" problem.
///
/// PRESERVES the file's existing line-ending style. The IDE keeps every buffer
/// LF-normalized in memory (see [[crlf-normalization]]), but an EXTERNAL library
/// cloned on Windows is checked out CRLF (Git-for-Windows `core.autocrlf=true`).
/// Blindly writing LF over it made git flag EVERY file as modified — content
/// identical (`git diff` empty), only the EOL and the cached size differed, a
/// phantom `.M` that neither `git diff` nor `update-index --refresh` could
/// clear. Matching the on-disk EOL means an unchanged CRLF file is left byte-for-
/// byte alone (no rewrite → git clean), and a real edit is written back CRLF so
/// only the true change shows. Firmware files (LF from birth) are unaffected.
fn write_if_changed(path: &Path, content: &[u8]) -> io::Result<()> {
    let existing = fs::read(path).ok();
    // Match the EOL already on disk; default LF for a new file.
    let to_write: std::borrow::Cow<[u8]> =
        if existing.as_deref().is_some_and(has_crlf) && !content.is_empty() {
            std::borrow::Cow::Owned(lf_to_crlf(content))
        } else {
            std::borrow::Cow::Borrowed(content)
        };
    if existing.as_deref() == Some(to_write.as_ref()) {
        return Ok(());
    }
    fs::write(path, to_write.as_ref())
}

/// Whether `bytes` contains a Windows line ending (`\r\n`).
fn has_crlf(bytes: &[u8]) -> bool {
    bytes.windows(2).any(|w| w == b"\r\n")
}

/// Convert LF-normalized `content` to CRLF. Idempotent: a stray lone `\r` is
/// dropped so `\r\n` never becomes `\r\r\n`.
fn lf_to_crlf(content: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(content.len() + content.len() / 20 + 8);
    for &b in content {
        match b {
            b'\r' => {}
            b'\n' => {
                out.push(b'\r');
                out.push(b'\n');
            }
            other => out.push(other),
        }
    }
    out
}

/// Walks `dir` recursively and removes every `.rs` file whose path relative to
/// `root` is **not** listed in `keep`.  Errors on individual files are silently
/// ignored — a failed removal produces no stale content (the file stays) and
/// does not abort the project write.
fn remove_stale_rs(root: &Path, dir: &Path, keep: &std::collections::HashSet<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Build output and VCS metadata are not ours to prune.
            let name = entry.file_name();
            if name == "target" || name == ".git" {
                continue;
            }
            // NEVER prune inside a nested INDEPENDENT repo (a cloned library,
            // detached or member — it keeps its own `.git`). Its files are the
            // library's, not the IDE's `user_src_files`; deleting a `.rs` that
            // isn't (yet) tracked in-memory — e.g. one added by a `git pull` in
            // the library — was exactly the "detached lib left with an empty
            // src/" data loss. The disposable build copy has no `.git`, so its
            // chip-switch cleanup is unaffected.
            if path.join(".git").exists() {
                continue;
            }
            remove_stale_rs(root, &path, keep);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            if let Ok(rel) = path.strip_prefix(root) {
                // Normalise to forward slashes so the lookup matches on Windows
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                if !keep.contains(&rel_str) {
                    let _ = fs::remove_file(&path);
                }
            }
        }
    }
}

/// Default `src/main.rs` for an ESP32-C3 project (no pin layout configured yet).
pub fn esp32c3_fresh_main_rs() -> String {
    r#"// Auto-generated by Embedded IDE
// MCU: ESP32-C3 | HAL: esp-hal

#![no_std]
#![no_main]

pub mod pins;


esp_bootloader_esp_idf::esp_app_desc!();

#[esp_hal::main]
fn main() -> ! {
    let peripherals = esp_hal::init(esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::max()));
    loop {
        // Your main loop code here.
    }
}
"#
    .to_string()
}

// ── RustEmbedded file generators ──────────────────────────────────────────────

fn cargo_toml_embedded(c: &ProjectDef) -> String {
    format!(
        "[package]\n\
         name    = \"{name}-project\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [[bin]]\n\
         name  = \"{name}-project\"\n\
         test  = false\n\
         bench = false\n\
         \n\
         [dependencies]\n\
         cortex-m    = {{ version = \"0.7\", features = [\"critical-section-single-core\"] }}\n\
         cortex-m-rt = \"0.7\"\n\
         panic-halt  = \"0.2\"\n\
         {hal}\n\
         \n\
         # Flash with:  cargo flash --chip {chip} --release\n\
         # Debug with:  cargo run   --release   (requires probe-rs in PATH)\n\
         \n\
         [profile.release]\n\
         panic         = \"abort\"\n\
         codegen-units = 1\n\
         debug         = true\n\
         lto           = true\n\
         opt-level     = \"s\"\n\
         \n\
         [profile.dev]\n\
         panic     = \"abort\"\n\
         opt-level = 1\n",
        name = c.pkg_name,
        hal = c.hal_dep,
        chip = c.probe_chip,
    )
}

fn cargo_config_embedded(c: &ProjectDef) -> String {
    format!(
        "[build]\n\
         target = \"{target}\"\n\
         \n\
         [target.{target}]\n\
         # Requires probe-rs: https://probe.rs/docs/getting-started/installation/\n\
         runner    = \"probe-rs run --chip {chip}\"\n\
         rustflags = [\n\
             \"-C\", \"link-arg=-Tlink.x\",\n\
         ]\n",
        target = c.target,
        chip = c.probe_chip,
    )
}

fn memory_x(c: &ProjectDef) -> String {
    format!(
        "/* {comment} */\n\
         MEMORY\n\
         {{\n\
             FLASH : ORIGIN = {flash_o}, LENGTH = {flash_s}\n\
             RAM   : ORIGIN = {ram_o},   LENGTH = {ram_s}\n\
         }}\n",
        comment = c.memory_comment,
        flash_o = c.flash_origin,
        flash_s = c.flash_size,
        ram_o = c.ram_origin,
        ram_s = c.ram_size,
    )
}

/// `build.rs` placed in the project root.
/// Copies `memory.x` to `OUT_DIR` so the linker script (`link.x` for ARM,
/// `linkall.x` for ESP32) can find it via the `rustc-link-search` path.
fn build_rs_embedded() -> String {
    let mut s = String::new();
    s.push_str("use std::env;\n");
    s.push_str("use std::fs::File;\n");
    s.push_str("use std::io::Write;\n");
    s.push_str("use std::path::PathBuf;\n");
    s.push_str("\n");
    s.push_str("fn main() {\n");
    s.push_str("    let out = PathBuf::from(env::var_os(\"OUT_DIR\").unwrap());\n");
    s.push_str("    File::create(out.join(\"memory.x\"))\n");
    s.push_str("        .unwrap()\n");
    s.push_str("        .write_all(include_bytes!(\"memory.x\"))\n");
    s.push_str("        .unwrap();\n");
    s.push_str("    println!(\"cargo:rustc-link-search={}\", out.display());\n");
    s.push_str("    println!(\"cargo:rerun-if-changed=memory.x\");\n");
    s.push_str("}\n");
    s
}

// ── EspRust file generators ───────────────────────────────────────────────────

fn cargo_toml_esp(c: &ProjectDef) -> String {
    format!(
        "[package]\n\
         name    = \"{name}-project\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [[bin]]\n\
         name  = \"{name}-project\"\n\
         test  = false\n\
         bench = false\n\
         \n\
         [dependencies]\n\
         esp-hal       = {{ version = \"~1.1.0\", features = [\"{chip}\", \"unstable\"] }}\n\
         esp-println   = {{ version = \"0.13\", features = [\"{chip}\", \"log\"] }}\n\
         esp-bootloader-esp-idf = {{ version = \"0.5.0\", features = [\"{chip}\"] }}\n\
         critical-section = \"1.2.0\"\n\
         \n\
         # Flash with: espflash flash --chip {chip} --release\n\
         # Install:    cargo install espflash\n\
         \n\
         [profile.release]\n\
         codegen-units = 1\n\
         debug         = 2\n\
         lto           = \"fat\"\n\
         opt-level     = \"s\"\n\
         \n\
         [profile.dev]\n\
         opt-level     = \"s\"\n",
        name = c.pkg_name,
        chip = c.probe_chip, // "esp32c3"
    )
}

fn cargo_config_esp(c: &ProjectDef) -> String {
    format!(
        "[target.{target}]\n\
         # --ignore-app-descriptor: esp-hal bare-metal binaries do not carry an\n\
         # ESP-IDF app descriptor; espflash 4.x requires this flag to skip the\n\
         # descriptor check. Add --monitor to open the serial console after flash.\n\
         #runner = \"espflash flash --monitor --ignore-app-descriptor\"\n\
         runner = \"espflash flash --monitor --chip {chip}\"\n\
         # esp-hal 0.23 places linkall.x + memory.x in its OUT_DIR via its\n\
         # build script.  linkall.x uses `INCLUDE memory.x` internally, so\n\
         # the chip memory map (IROM, DROM, IRAM, DRAM, RTC_SLOW) is already\n\
         # present.  Only -Tlinkall.x is needed here; supplying a second\n\
         # -Tmemory.x would redefine those regions and cause a linker error.\n\
         rustflags = [\n\
            \"-C\", \"link-arg=-Tlinkall.x\",\n\
            # \"-C\", \"force-frame-pointers\",\n\
         ]\n\
         \n\
         [build]\n\
         target = \"{target}\"\n\
         \n\
         [env]\n\
         ESP_LOG = \"INFO\"\n\
         \n\
         [unstable]\n\
         build-std = [\"core\"]\n",
        target = c.target,
        chip = c.probe_chip,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn stm32_def() -> ProjectDef {
        ProjectDef {
            pkg_name: "demo".into(),
            target: "thumbv7m-none-eabi".into(),
            flash_origin: "0x08000000".into(),
            flash_size: "64K".into(),
            ram_origin: "0x20000000".into(),
            ram_size: "20K".into(),
            hal_dep: "stm32f1xx-hal = { version = \"0.10\" }".into(),
            probe_chip: "STM32F103C8".into(),
            memory_comment: "STM32F103C8".into(),
        }
    }

    #[test]
    fn cargo_toml_has_hash_markers_and_user_tail() {
        let f = gen_config(
            ConfigFile::CargoToml,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(f.contains("# <<< GENERATED"), "begin marker:\n{f}");
        assert!(f.contains("# <<< GENERATED END >>>"), "end marker");
        assert!(f.contains("stm32f1xx-hal"), "generated body present");
        assert!(
            f.contains("Add your own entries below"),
            "user tail present"
        );
    }

    #[test]
    fn memory_x_uses_block_comments_build_rs_uses_slashes() {
        let mx = gen_config(
            ConfigFile::MemoryX,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(
            mx.starts_with("/* <<< GENERATED"),
            "ld block comment:\n{mx}"
        );
        assert!(mx.contains("0x08000000"), "flash origin in body");
        let br = gen_config(
            ConfigFile::BuildRs,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(br.contains("// <<< GENERATED"), "rust line comment:\n{br}");
    }

    #[test]
    fn esp_has_no_memory_x_or_build_rs() {
        assert!(gen_config(ConfigFile::MemoryX, &stm32_def(), &ToolchainKind::EspRust).is_empty());
        assert!(gen_config(ConfigFile::BuildRs, &stm32_def(), &ToolchainKind::EspRust).is_empty());
    }

    #[test]
    fn splice_preserves_user_tail_and_is_idempotent() {
        let tc = ToolchainKind::RustEmbedded;
        // User adds an extra dependency in the editable tail.
        let edited = format!(
            "{}\n[dependencies.heapless]\nversion = \"0.8\"\n",
            gen_config(ConfigFile::CargoToml, &stm32_def(), &tc)
        );

        let once = splice_config(ConfigFile::CargoToml, &edited, &stm32_def(), &tc);
        assert!(once.contains("heapless"), "user tail preserved:\n{once}");
        assert!(once.contains("stm32f1xx-hal"), "generated block refreshed");

        // Re-splicing with the same chip is a no-op (no blank-line creep).
        let twice = splice_config(ConfigFile::CargoToml, &once, &stm32_def(), &tc);
        assert_eq!(once, twice, "splice must be idempotent");
    }

    #[test]
    fn splice_refreshes_block_on_chip_change_keeping_edits() {
        let tc = ToolchainKind::RustEmbedded;
        let edited = format!(
            "{}/* my note */\n",
            gen_config(ConfigFile::MemoryX, &stm32_def(), &tc)
        );
        let mut other = stm32_def();
        other.flash_origin = "0x08002000".into(); // different chip memory map
        let spliced = splice_config(ConfigFile::MemoryX, &edited, &other, &tc);
        assert!(spliced.contains("0x08002000"), "block reflects new chip");
        assert!(!spliced.contains("0x08000000"), "old generated value gone");
        assert!(spliced.contains("/* my note */"), "user edit preserved");
    }

    #[test]
    fn ensure_peripheral_deps_adds_removes_shared_and_is_idempotent() {
        let base = gen_config(
            ConfigFile::CargoToml,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        let none = |t: &str| ensure_peripheral_deps(t, false, false, false, false, false);
        assert!(!base.contains("bxcan") && !base.contains("embedded-hal"), "clean base");

        // CAN only → bxcan + nb; no embedded-io/hal.
        let can = ensure_peripheral_deps(&base, true, false, false, false, false);
        assert!(can.contains("bxcan = \"0.7\"") && can.contains("nb           = \"1\""));
        assert!(!can.contains("embedded-io") && !can.contains("embedded-hal"));
        assert_eq!(none(&can), base, "removal restores base");

        // USART only → embedded-io + embedded-hal-0-2 + nb; NO embedded-hal 1.0.
        let usart = ensure_peripheral_deps(&base, false, true, false, false, false);
        assert!(usart.contains("embedded-io  = \"0.6\""), "{usart}");
        assert!(usart.contains("embedded-hal-0-2 = { package = \"embedded-hal\""), "{usart}");
        assert!(usart.contains("nb           = \"1\""));
        // The exact `embedded-hal = ` (1.0) line must NOT be present for USART-only.
        assert!(!usart.lines().any(|l| is_dep_line(l, "embedded-hal")), "no eh 1.0:\n{usart}");
        assert_eq!(none(&usart), base);

        // SPI only → embedded-hal 1.0 + embedded-hal-0-2 + nb; no embedded-io.
        let spi = ensure_peripheral_deps(&base, false, false, true, false, false);
        assert!(spi.lines().any(|l| is_dep_line(l, "embedded-hal")), "eh 1.0 present");
        assert!(spi.contains("embedded-hal-0-2") && spi.contains("nb           ="));
        assert!(!spi.contains("embedded-io"));

        // I2C only → embedded-hal 1.0 + embedded-hal-0-2, but NO nb (I2c bridge
        // needs no nb::block!).
        let i2c = ensure_peripheral_deps(&base, false, false, false, true, false);
        assert!(i2c.lines().any(|l| is_dep_line(l, "embedded-hal")) && i2c.contains("embedded-hal-0-2"));
        assert!(!i2c.lines().any(|l| is_dep_line(l, "nb")), "no nb for i2c-only:\n{i2c}");

        // GPIO only → embedded-hal 1.0 + embedded-hal-0-2, NO nb, NO embedded-io.
        let gpio = ensure_peripheral_deps(&base, false, false, false, false, true);
        assert!(gpio.lines().any(|l| is_dep_line(l, "embedded-hal")) && gpio.contains("embedded-hal-0-2"));
        assert!(!gpio.lines().any(|l| is_dep_line(l, "nb")) && !gpio.contains("embedded-io"));
        assert_eq!(none(&gpio), base);

        // Everything on → all present, exactly one line each; idempotent.
        let all = ensure_peripheral_deps(&base, true, true, true, true, true);
        for dep in ["bxcan", "embedded-io", "embedded-hal", "embedded-hal-0-2", "nb"] {
            assert_eq!(
                all.lines().filter(|l| is_dep_line(l, dep)).count(),
                1,
                "exactly one `{dep}` line:\n{all}"
            );
        }
        assert_eq!(ensure_peripheral_deps(&all, true, true, true, true, true), all, "idempotent");
        assert_eq!(none(&all), base, "full teardown restores base");
    }

    #[test]
    fn ensure_usb_deps_adds_removes_deps_and_hal_feature() {
        // A Cargo.toml whose HAL line carries a features array (as generated).
        let base = "[dependencies]\n\
                    stm32f1xx-hal = { version = \"0.10\", features = [\"stm32f103\", \"rt\"] }\n";

        let with = ensure_usb_deps(base, true);
        assert!(
            with.contains("usb-device  = \"0.2\""),
            "usb-device added:\n{with}"
        );
        assert!(with.contains("usbd-serial = \"0.1\""), "usbd-serial added");
        assert!(with.contains("\"stm32-usbd\""), "stm32-usbd feature added");
        // Idempotent.
        assert_eq!(ensure_usb_deps(&with, true), with, "add must be idempotent");
        assert_eq!(
            with.matches("\"stm32-usbd\"").count(),
            1,
            "feature not duplicated"
        );

        // Removing restores the original (deps + feature gone).
        let removed = ensure_usb_deps(&with, false);
        assert!(
            !removed.contains("usb-device"),
            "usb-device removed:\n{removed}"
        );
        assert!(!removed.contains("stm32-usbd"), "feature removed");
        assert_eq!(removed, base, "removal restores the original");
        assert_eq!(
            ensure_usb_deps(base, false),
            base,
            "no-op when nothing to remove"
        );
    }

    #[test]
    fn ensure_async_deps_adds_removes_executor_time_and_driver() {
        // An embassy Cargo.toml (as generated for a non-F1 STM32 chip).
        let base = "[dependencies]\n\
                    embassy-stm32 = { version = \"0.4\", features = [\"stm32f411re\"] }\n";

        // Async runtime, no bus peripherals yet → executor + time + driver, but
        // none of the peripheral trait crates.
        let with = ensure_async_deps(base, true, false, false, false);
        assert!(with.contains("embassy-executor = { version = \"0.9\""), "executor added:\n{with}");
        assert!(with.contains("embassy-time = \"0.5\""), "embassy-time added");
        assert!(with.contains("\"time-driver-any\""), "HAL time driver added");
        assert!(!with.contains("embedded-io-async"), "no async USART crate yet");
        assert!(!with.lines().any(|l| is_dep_line(l, "static_cell")), "no static_cell yet");
        assert!(!with.lines().any(|l| is_dep_line(l, "embedded-hal")), "no embedded-hal yet");
        // The chip feature survives the driver insertion.
        assert!(with.contains("\"stm32f411re\""), "chip feature kept:\n{with}");
        // Idempotent — no duplicate deps/features.
        assert_eq!(ensure_async_deps(&with, true, false, false, false), with, "add must be idempotent");
        assert_eq!(with.matches("\"time-driver-any\"").count(), 1, "driver not duplicated");
        assert_eq!(with.lines().filter(|l| is_dep_line(l, "embassy-executor")).count(), 1);

        // Add an async USART → embedded-io-async + static_cell appear too.
        let with_usart = ensure_async_deps(base, true, true, false, false);
        assert!(with_usart.contains("embedded-io-async = \"0.6\""), "async serial trait crate:\n{with_usart}");
        assert!(with_usart.lines().any(|l| is_dep_line(l, "static_cell")), "static_cell (underscore)");
        assert!(!with_usart.contains("static-cell ="), "must NOT use the hyphen name");
        assert_eq!(ensure_async_deps(&with_usart, true, true, false, false), with_usart, "usart add idempotent");

        // Blocking SPI/I2C on async → embedded-hal 1.0, NOT embedded-hal-async.
        let with_bus = ensure_async_deps(base, true, false, true, false);
        assert!(with_bus.lines().any(|l| is_dep_line(l, "embedded-hal")), "embedded-hal added:\n{with_bus}");
        assert!(!with_bus.lines().any(|l| is_dep_line(l, "embedded-hal-async")), "no async trait crate for blocking bus");

        // Async-DMA SPI/I2C → both embedded-hal + embedded-hal-async.
        let with_dma = ensure_async_deps(base, true, false, true, true);
        assert!(with_dma.lines().any(|l| is_dep_line(l, "embedded-hal")), "embedded-hal present");
        assert!(with_dma.contains("embedded-hal-async = \"1.0\""), "async trait crate added:\n{with_dma}");
        assert_eq!(ensure_async_deps(&with_dma, true, false, true, true), with_dma, "dma add idempotent");

        // Dropping just the USART removes only its two crates (executor stays).
        let no_usart = ensure_async_deps(&with_usart, true, false, false, false);
        assert!(!no_usart.contains("embedded-io-async") && !no_usart.lines().any(|l| is_dep_line(l, "static_cell")));
        assert!(no_usart.contains("embassy-executor"), "runtime deps stay");

        // Removing everything restores the original exactly.
        let removed = ensure_async_deps(&with_dma, false, false, false, false);
        assert!(!removed.contains("embassy-executor"), "executor removed:\n{removed}");
        assert!(!removed.contains("embassy-time"), "embassy-time removed");
        assert!(!removed.contains("time-driver-any"), "driver feature removed");
        assert!(!removed.contains("embedded-io-async"), "async serial crate removed");
        assert!(!removed.lines().any(|l| is_dep_line(l, "embedded-hal")), "embedded-hal removed");
        assert!(!removed.contains("embedded-hal-async"), "async trait crate removed");
        assert_eq!(removed, base, "removal restores the original");
        assert_eq!(ensure_async_deps(base, false, false, false, false), base, "no-op when nothing to remove");
    }

    /// A hand-written file with no GEN markers (external project) must be shown
    /// verbatim — never get a generated block injected above it (which would
    /// duplicate `[package]`).
    #[test]
    fn external_file_without_markers_is_left_untouched() {
        let external = "[package]\nname = \"theirs\"\n\n[dependencies]\nserde = \"1\"\n";
        let out = splice_config(
            ConfigFile::CargoToml,
            external,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert_eq!(out, external);
    }

    /// Only foreign CRATE directories go; everything else in the workspace is
    /// left alone. (Pruning is guarded to the throw-away build workspace at the
    /// call site — this covers the decision, not the guard.)
    #[test]
    fn prune_removes_only_non_member_crates() {
        let dir = tempfile::TempDir::new().unwrap();
        let root = dir.path();
        let crate_at = |name: &str| {
            fs::create_dir_all(root.join(name).join("src")).unwrap();
            fs::write(root.join(name).join("Cargo.toml"), "[package]
").unwrap();
        };
        crate_at("mw_radar");   // current member  -> keep
        crate_at("stale_lib");  // another project -> remove
        fs::create_dir_all(root.join("src")).unwrap();       // firmware sources
        fs::create_dir_all(root.join("target")).unwrap();    // build output
        fs::create_dir_all(root.join("assets")).unwrap();    // plain folder, no manifest

        prune_foreign_crates(root, &["mw_radar".to_string()]);

        assert!(root.join("mw_radar").is_dir(), "member kept");
        assert!(!root.join("stale_lib").exists(), "foreign crate removed");
        assert!(root.join("src").is_dir(), "src kept");
        assert!(root.join("target").is_dir(), "target kept");
        assert!(root.join("assets").is_dir(), "a folder without Cargo.toml is not ours to judge");
    }

    /// `write_if_changed` must preserve a CRLF file's line endings, or the IDE
    /// (LF in memory) rewrites a Windows-checkout library as LF → git flags every
    /// file as a phantom modification. An unchanged CRLF file is left untouched;
    /// a real edit is written back as CRLF.
    #[test]
    fn write_if_changed_preserves_crlf() {
        let dir = tempfile::TempDir::new().unwrap();
        let f = dir.path().join("radar.rs");
        fs::write(&f, b"a\r\nb\r\n").unwrap(); // CRLF on disk (git checkout)
        // Same content, LF form (the in-memory buffer) → must NOT rewrite.
        let mtime_before = fs::metadata(&f).unwrap().modified().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(10));
        write_if_changed(&f, b"a\nb\n").unwrap();
        assert_eq!(fs::read(&f).unwrap(), b"a\r\nb\r\n", "CRLF file left byte-identical");
        assert_eq!(
            fs::metadata(&f).unwrap().modified().unwrap(),
            mtime_before,
            "no rewrite → mtime stable"
        );
        // A real edit is written back CRLF (only the change, no EOL flip).
        write_if_changed(&f, b"a\nc\n").unwrap();
        assert_eq!(fs::read(&f).unwrap(), b"a\r\nc\r\n", "edit kept CRLF");
        // An LF file stays LF.
        let g = dir.path().join("main.rs");
        fs::write(&g, b"x\ny\n").unwrap();
        write_if_changed(&g, b"x\nz\n").unwrap();
        assert_eq!(fs::read(&g).unwrap(), b"x\nz\n", "LF file stays LF");
    }

    /// `remove_stale_rs` must NOT delete `.rs` inside a nested INDEPENDENT repo
    /// (a cloned/detached library keeps its own `.git`), even when those files
    /// aren't in the keep-set — that was the "detached lib left with empty src/"
    /// data loss. A genuinely-stale `.rs` in the firmware's own tree still goes.
    #[test]
    fn stale_prune_spares_nested_git_repos() {
        let dir = tempfile::TempDir::new().unwrap();
        let root = dir.path();
        // Firmware: a stale file NOT in the keep-set.
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(root.join("src").join("stale.rs"), "// old").unwrap();
        // An independent library (its own .git) with a file also not in keep.
        let lib = root.join("mylib");
        fs::create_dir_all(lib.join("src")).unwrap();
        fs::create_dir_all(lib.join(".git")).unwrap();
        fs::write(lib.join("src").join("lib.rs"), "pub fn go() {}").unwrap();

        let keep: std::collections::HashSet<String> =
            ["src/main.rs".to_string()].into_iter().collect();
        remove_stale_rs(root, root, &keep);

        assert!(!root.join("src").join("stale.rs").exists(), "firmware stale .rs pruned");
        assert!(
            lib.join("src").join("lib.rs").exists(),
            "a file inside a nested independent repo must be spared"
        );
    }

    /// A nested member (`crates/foo`) must protect its whole branch.
    #[test]
    fn a_nested_member_protects_its_top_level_directory() {
        let dir = tempfile::TempDir::new().unwrap();
        let root = dir.path();
        fs::create_dir_all(root.join("crates")).unwrap();
        fs::write(root.join("crates").join("Cargo.toml"), "[package]
").unwrap();

        prune_foreign_crates(root, &["crates/foo".to_string()]);
        assert!(root.join("crates").is_dir());
    }
}
