//! Generates a complete, buildable Cargo project from the current pin configuration.
//!
//! Output layout:
//! ```
//! <dest>/
//! ├── .cargo/
//! │   └── config.toml      — build target + linker flags + probe-rs runner
//! ├── src/
//! │   └── main.rs          — HAL code generated by codegen.rs
//! ├── .gitignore
//! ├── build.rs             — copies memory.x to OUT_DIR for the linker
//! ├── Cargo.toml
//! └── memory.x             — flash / RAM layout for this MCU
//! ```

use super::mcu_catalog::McuProjectConfig;
use std::{fs, io, path::Path};

// ── Public types ──────────────────────────────────────────────────────────────

/// All generated file contents for one project snapshot.
/// Cheap to build (pure string formatting); regenerated every UI frame.
pub struct ProjectFiles {
    pub main_rs: String,
    pub cargo_toml: String,
    pub cargo_config: String,
    pub memory_x: String,
    pub build_rs: String,
    pub gitignore: String,
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Builds all file contents in memory without touching the filesystem.
pub fn build_project_files(config: &McuProjectConfig, main_rs: &str) -> ProjectFiles {
    ProjectFiles {
        main_rs: main_rs.to_owned(),
        cargo_toml: cargo_toml(config),
        cargo_config: cargo_config(config),
        memory_x: memory_x(config),
        build_rs: build_rs(),
        gitignore: "/target\n".to_owned(),
    }
}

/// Writes all project files into `dest` (creates the directory tree as needed).
/// `user_src_files` is a list of `(path_relative_to_src, content)` pairs for
/// user-created files (e.g. `("utils.rs", "...")` or `("drivers/spi.rs", "...")`).
pub fn write_project(
    dest: &Path,
    config: &McuProjectConfig,
    main_rs: &str,
    user_src_files: &[(String, String)],
) -> io::Result<()> {
    let files = build_project_files(config, main_rs);

    fs::create_dir_all(dest.join("src"))?;
    fs::create_dir_all(dest.join(".cargo"))?;

    fs::write(dest.join("Cargo.toml"), &files.cargo_toml)?;
    fs::write(dest.join(".cargo").join("config.toml"), &files.cargo_config)?;
    fs::write(dest.join("memory.x"), &files.memory_x)?;
    fs::write(dest.join("build.rs"), &files.build_rs)?;
    fs::write(dest.join("src").join("main.rs"), &files.main_rs)?;
    fs::write(dest.join(".gitignore"), &files.gitignore)?;

    for (rel_path, content) in user_src_files {
        let full = dest.join("src").join(rel_path);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(full, content)?;
    }

    Ok(())
}

// ── File content generators ───────────────────────────────────────────────────

fn cargo_toml(c: &McuProjectConfig) -> String {
    format!(
        "[package]\n\
         name    = \"{name}-project\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [[bin]]\n\
         name  = \"{name}-project\"\n\
         test  = false\n\
         bench = false\n\
         \n\
         [dependencies]\n\
         cortex-m    = {{ version = \"0.7\", features = [\"critical-section-single-core\"] }}\n\
         cortex-m-rt = \"0.7\"\n\
         panic-halt  = \"0.2\"\n\
         {hal}\n\
         \n\
         # Flash with:  cargo flash --chip {chip} --release\n\
         # Debug with:  cargo run   --release   (requires probe-rs in PATH)\n\
         \n\
         [profile.release]\n\
         panic = \"abort\"\n\
         codegen-units = 1\n\
         debug         = true\n\
         lto           = true\n\
         opt-level     = \"s\"\n\
         \n\
         [profile.dev]\n\
         panic = \"abort\"\n\
         opt-level = 1\n",
        name = c.pkg_name,
        hal = c.hal_dep,
        chip = c.probe_chip,
    )
}

fn cargo_config(c: &McuProjectConfig) -> String {
    format!(
        "[build]\n\
         target = \"{target}\"\n\
         \n\
         [target.{target}]\n\
         # Requires probe-rs: https://probe.rs/docs/getting-started/installation/\n\
         runner    = \"probe-rs run --chip {chip}\"\n\
         rustflags = [\n\
             \"-C\", \"link-arg=-Tlink.x\",\n\
         ]\n",
        target = c.target,
        chip = c.probe_chip,
    )
}

fn memory_x(c: &McuProjectConfig) -> String {
    format!(
        "/* {comment} */\n\
         MEMORY\n\
         {{\n\
            FLASH : ORIGIN = {flash_o}, LENGTH = {flash_s}\n\
             RAM   : ORIGIN = {ram_o},   LENGTH = {ram_s}\n\
         }}\n",
        comment = c.memory_comment,
        flash_o = c.flash_origin,
        flash_s = c.flash_size,
        ram_o = c.ram_origin,
        ram_s = c.ram_size,
    )
}

/// `build.rs` placed in the project root.
/// Copies `memory.x` to `OUT_DIR` so `cortex-m-rt`'s `link.x` can find it.
fn build_rs() -> String {
    // Written as a regular string to avoid any escaping confusion.
    let mut s = String::new();
    s.push_str("use std::env;\n");
    s.push_str("use std::fs::File;\n");
    s.push_str("use std::io::Write;\n");
    s.push_str("use std::path::PathBuf;\n");
    s.push_str("\n");
    s.push_str("fn main() {\n");
    s.push_str("    let out = PathBuf::from(env::var_os(\"OUT_DIR\").unwrap());\n");
    s.push_str("    File::create(out.join(\"memory.x\"))\n");
    s.push_str("        .unwrap()\n");
    s.push_str("        .write_all(include_bytes!(\"memory.x\"))\n");
    s.push_str("        .unwrap();\n");
    s.push_str("    println!(\"cargo:rustc-link-search={}\", out.display());\n");
    s.push_str("    println!(\"cargo:rerun-if-changed=memory.x\");\n");
    s.push_str("}\n");
    s
}
