//! Generates a complete, buildable Cargo project from the current pin configuration.
//!
//! Output layout for RustEmbedded (STM32/ARM):
//! ```
//! <dest>/
//! ├── .cargo/
//! │   └── config.toml      — build target + linker flags + probe-rs runner
//! ├── src/
//! │   └── main.rs          — HAL code generated by codegen.rs
//! ├── .gitignore
//! ├── build.rs             — copies memory.x to OUT_DIR
//! ├── Cargo.toml
//! └── memory.x             — flash / RAM layout for this MCU
//! ```
//!
//! Output layout for EspRust (ESP32-C3):
//! ```
//! <dest>/
//! ├── .cargo/
//! │   └── config.toml      — target + build-std + espflash runner
//! ├── src/
//! │   └── main.rs          — esp-hal code
//! ├── .gitignore
//! └── Cargo.toml
//! ```
//! No `memory.x` or `build.rs` — esp-hal 0.23 generates both `memory.x` and
//! `linkall.x` in its own OUT_DIR via its build script.  Only `-Tlinkall.x` is
//! needed in rustflags; adding a second `-Tmemory.x` redefines IROM/DROM/etc.
//! and causes a linker error ("region already defined").

use super::mcu_catalog::ToolchainKind;
use super::mcu_def::ProjectDef;
use std::{fs, io, path::Path};

// ── Public types ──────────────────────────────────────────────────────────────

/// All generated file contents for one project snapshot.
/// Cheap to build (pure string formatting); regenerated every UI frame.
#[derive(Clone)]
pub struct ProjectFiles {
    pub main_rs: String,
    pub cargo_toml: String,
    pub cargo_config: String,
    pub memory_x: String, // empty for EspRust
    pub build_rs: String, // empty for EspRust
    pub gitignore: String,
}

// ── Generated-block markers (per comment style) ────────────────────────────────
//
// Every generated config file carries its chip-derived content inside a
// `<<< GENERATED >>> … <<< GENERATED END >>>` block, written with the comment
// syntax of that file. Anything the user adds outside the block is preserved
// when the block is refreshed (e.g. on a chip change) — the same contract as the
// GEN_BEGIN…GEN_END block in `main.rs`.

/// Comment syntax of a config file, used to frame the generated block.
#[derive(Clone, Copy)]
enum Cmt {
    /// `//` line comments — Rust (`build.rs`).
    Slash,
    /// `#` line comments — TOML, `.gitignore`.
    Hash,
    /// `/* … */` block comments — GNU ld linker script (`memory.x`).
    Block,
}

impl Cmt {
    fn begin(self) -> &'static str {
        match self {
            Cmt::Slash => "// <<< GENERATED — do not edit inside this block >>>",
            Cmt::Hash => "# <<< GENERATED — do not edit inside this block >>>",
            Cmt::Block => "/* <<< GENERATED — do not edit inside this block >>> */",
        }
    }
    fn end(self) -> &'static str {
        match self {
            Cmt::Slash => "// <<< GENERATED END >>>",
            Cmt::Hash => "# <<< GENERATED END >>>",
            Cmt::Block => "/* <<< GENERATED END >>> */",
        }
    }
    /// The user-editable tail invitation placed below the block on first build.
    fn tail(self) -> &'static str {
        match self {
            Cmt::Slash => {
                "// Add your own code below — preserved when the block above is refreshed.\n"
            }
            Cmt::Hash => {
                "# Add your own entries below — preserved when the block above is refreshed.\n"
            }
            Cmt::Block => {
                "/* Add your own entries below — preserved when the block above is refreshed. */\n"
            }
        }
    }
}

/// The framed generated block (`begin … body … end`); `body` must end in `\n`.
fn gen_block(style: Cmt, body: &str) -> String {
    format!("{}\n{}{}", style.begin(), body, style.end())
}

/// First-time file layout: the generated block followed by a user-editable tail.
fn initial_file(style: Cmt, body: &str) -> String {
    format!("{}\n{}", gen_block(style, body), style.tail())
}

/// Refresh the generated block in `existing`, preserving everything the user
/// added before or after the markers. Falls back to a fresh layout when the
/// markers are missing (legacy or hand-cleared file).
fn splice_block(existing: &str, style: Cmt, body: &str) -> String {
    let (begin, end) = (style.begin(), style.end());
    if let (Some(b), Some(e)) = (existing.find(begin), existing.find(end)) {
        if b < e {
            let before = &existing[..b];
            // Trim leading newlines after the end marker, then re-add exactly one
            // so repeated splices are idempotent (no blank-line creep).
            let after = existing[e + end.len()..].trim_start_matches('\n');
            return format!("{before}{}\n{after}", gen_block(style, body));
        }
    }
    if existing.trim().is_empty() {
        initial_file(style, body)
    } else {
        // Non-empty but no markers — an externally-authored file (or one whose
        // markers the user removed). Leave it untouched: the IDE only manages a
        // block in files it generated itself, so it never duplicates a hand-
        // written `[package]`/MEMORY/etc.
        existing.to_owned()
    }
}

/// The five generated project files that live at the project root (outside
/// `src/`). Each maps to a [`ProjectFileId`](crate::app::ProjectFileId).
#[derive(Clone, Copy)]
pub enum ConfigFile {
    CargoToml,
    CargoConfig,
    MemoryX,
    BuildRs,
    GitIgnore,
}

impl ConfigFile {
    /// The generated body + comment style for this file, or `None` when the file
    /// does not apply to the toolchain (e.g. `memory.x`/`build.rs` for ESP, which
    /// esp-hal supplies itself).
    fn body(self, c: &ProjectDef, toolchain: &ToolchainKind) -> Option<(Cmt, String)> {
        use ToolchainKind::{EspRust, RustEmbedded};
        match self {
            ConfigFile::CargoToml => match toolchain {
                RustEmbedded => Some((Cmt::Hash, cargo_toml_embedded(c))),
                EspRust => Some((Cmt::Hash, cargo_toml_esp(c))),
                _ => None,
            },
            ConfigFile::CargoConfig => match toolchain {
                RustEmbedded => Some((Cmt::Hash, cargo_config_embedded(c))),
                EspRust => Some((Cmt::Hash, cargo_config_esp(c))),
                _ => None,
            },
            ConfigFile::MemoryX => match toolchain {
                RustEmbedded => Some((Cmt::Block, memory_x(c))),
                _ => None,
            },
            ConfigFile::BuildRs => match toolchain {
                RustEmbedded => Some((Cmt::Slash, build_rs_embedded())),
                _ => None,
            },
            // `project_structure.config` is per-user view state (node positions
            // in the Structure diagram) — it changes on every drag, so it is
            // ignored rather than committed. `mcu.config` IS committed: it is
            // real configuration.
            ConfigFile::GitIgnore => Some((
                Cmt::Hash,
                format!(
                    "/target\n{}\n",
                    crate::panels::mcu_module::structure_config::FILE_NAME
                ),
            )),
        }
    }
}

/// Fresh full content for a config file (generated block + user tail), or an
/// empty string when the file does not apply to the toolchain.
pub fn gen_config(file: ConfigFile, c: &ProjectDef, toolchain: &ToolchainKind) -> String {
    file.body(c, toolchain)
        .map(|(style, body)| initial_file(style, &body))
        .unwrap_or_default()
}

/// Refresh the generated block of an already-edited config file, preserving the
/// user's surrounding edits. Empty string when the file does not apply.
pub fn splice_config(
    file: ConfigFile,
    existing: &str,
    c: &ProjectDef,
    toolchain: &ToolchainKind,
) -> String {
    file.body(c, toolchain)
        .map(|(style, body)| splice_block(existing, style, &body))
        .unwrap_or_default()
}

/// Add or remove the `bxcan` + `nb` dependencies in a Cargo.toml's
/// `[dependencies]` section, driven by whether a CAN peripheral is configured.
///
/// The generated `src/pins/configs/can1.rs` uses the external `bxcan` crate (and
/// `nb` for its blocking API), which the base `[dependencies]` block doesn't
/// include. This is called every frame from `init_frame`, so it must be
/// idempotent: it returns the input unchanged when the deps are already in the
/// desired state, and drops the auto-added lines again once CAN is removed.
pub fn ensure_can_deps(cargo_toml: &str, needs_can: bool) -> String {
    // True when `line` declares the dependency `name` (`name = …`), tolerating
    // leading whitespace and any spacing around `=`.
    let is_dep = |line: &str, name: &str| {
        line.trim_start()
            .strip_prefix(name)
            .map(|rest| rest.trim_start().starts_with('='))
            .unwrap_or(false)
    };
    let has_bxcan = cargo_toml.lines().any(|l| is_dep(l, "bxcan"));
    if needs_can == has_bxcan {
        return cargo_toml.to_owned(); // already in the desired state — no churn
    }

    let mut out: Vec<String> = Vec::new();
    let mut inserted = false;
    for line in cargo_toml.lines() {
        if !needs_can && (is_dep(line, "bxcan") || is_dep(line, "nb")) {
            continue; // CAN gone → drop the deps we added
        }
        out.push(line.to_string());
        if needs_can && !inserted && line.trim() == "[dependencies]" {
            out.push("bxcan = \"0.7\"".to_string());
            out.push("nb    = \"1\"".to_string());
            inserted = true;
        }
    }
    let mut s = out.join("\n");
    if cargo_toml.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Add or remove the `usb-device` + `usbd-serial` dependencies AND the
/// `stm32-usbd` feature on the `stm32f1xx-hal` line, driven by whether a USB
/// peripheral is configured. Like [`ensure_can_deps`], idempotent and called
/// every frame — the generated USB CDC init needs both crates and the HAL
/// feature (which exposes `stm32f1xx_hal::usb`).
pub fn ensure_usb_deps(cargo_toml: &str, needs_usb: bool) -> String {
    let is_dep = |line: &str, name: &str| {
        line.trim_start()
            .strip_prefix(name)
            .map(|rest| rest.trim_start().starts_with('='))
            .unwrap_or(false)
    };
    let is_hal = |line: &str| line.trim_start().starts_with("stm32f1xx-hal");
    let has_usb_dep = cargo_toml.lines().any(|l| is_dep(l, "usb-device"));
    let has_feature = cargo_toml
        .lines()
        .any(|l| is_hal(l) && l.contains("\"stm32-usbd\""));
    if needs_usb == has_usb_dep && needs_usb == has_feature {
        return cargo_toml.to_owned(); // already in the desired state
    }

    let mut out: Vec<String> = Vec::new();
    let mut inserted = false;
    for line in cargo_toml.lines() {
        if !needs_usb && (is_dep(line, "usb-device") || is_dep(line, "usbd-serial")) {
            continue; // USB gone → drop the deps we added
        }
        // Toggle the `stm32-usbd` HAL feature inside the `features = [ … ]` array.
        if is_hal(line) && line.contains("features = [") {
            out.push(toggle_hal_feature(line, "stm32-usbd", needs_usb));
            continue;
        }
        out.push(line.to_string());
        if needs_usb && !inserted && line.trim() == "[dependencies]" {
            // Versions matched to stm32f1xx-hal 0.10's `usb` module (stm32-usbd),
            // which targets usb-device 0.2 / usbd-serial 0.1 (`.product()` API).
            out.push("usb-device  = \"0.2\"".to_string());
            out.push("usbd-serial = \"0.1\"".to_string());
            inserted = true;
        }
    }
    let mut s = out.join("\n");
    if cargo_toml.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Add or remove `"feature"` inside the `features = [ … ]` array of a single
/// dependency `line`, idempotently.
fn toggle_hal_feature(line: &str, feature: &str, add: bool) -> String {
    let quoted = format!("\"{feature}\"");
    let present = line.contains(&quoted);
    if add == present {
        return line.to_string();
    }
    if add {
        // Insert right after the opening bracket: `features = [` → `… ["feat", `.
        line.replacen("features = [", &format!("features = [{quoted}, "), 1)
    } else {
        // Remove the entry plus its trailing or leading separator.
        line.replace(&format!("{quoted}, "), "")
            .replace(&format!(", {quoted}"), "")
            .replace(&quoted, "")
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Builds all file contents in memory without touching the filesystem.
pub fn build_project_files(
    config: &ProjectDef,
    toolchain: &ToolchainKind,
    main_rs: &str,
) -> ProjectFiles {
    // Each config file carries its chip-derived content in a `<<< GENERATED >>>`
    // block (`gen_config` frames it with the file's comment syntax and returns
    // an empty string for files the toolchain doesn't use, e.g. memory.x/build.rs
    // on ESP, where esp-hal supplies them itself).
    ProjectFiles {
        main_rs: main_rs.to_owned(),
        cargo_toml: gen_config(ConfigFile::CargoToml, config, toolchain),
        cargo_config: gen_config(ConfigFile::CargoConfig, config, toolchain),
        memory_x: gen_config(ConfigFile::MemoryX, config, toolchain),
        build_rs: gen_config(ConfigFile::BuildRs, config, toolchain),
        gitignore: gen_config(ConfigFile::GitIgnore, config, toolchain),
    }
}

/// Writes the given project `files` into `dest` (creating the directory tree as
/// needed). `files` carries the *current* (possibly user-edited) content of each
/// generated file, so edits made in the IDE are written verbatim rather than
/// regenerated. `user_src_files` is a list of `(path_relative_to_src, content)`
/// pairs. A file with empty content (e.g. `memory.x`/`build.rs` on ESP) is not
/// written.
pub fn write_project(
    dest: &Path,
    files: &ProjectFiles,
    user_src_files: &[(String, String)],
    mcu_config: &str,
    // `project_structure.config` — Structure-tab view state, kept out of
    // `mcu.config` so node drags don't show up as config changes in Git.
    structure_config: &str,
) -> io::Result<()> {
    fs::create_dir_all(dest.join("src"))?;
    fs::create_dir_all(dest.join(".cargo"))?;

    // ── Remove stale .rs files from src/ ─────────────────────────────────────
    // When the user switches between chip types (e.g. STM32 → ESP32-C3), the
    // workspace directory still contains .rs files written during the previous
    // build (e.g. src/lib.rs with `use stm32f1xx_hal`).  Those stale files are
    // not part of the new project, but `cargo check` picks them up and fails.
    //
    // Build the authoritative set of paths that SHOULD exist inside src/:
    // main.rs (always generated) + every user source file.
    // Paths are relative to the PROJECT ROOT, so the keep-set covers the
    // firmware's src/ AND every library crate's sources in one pass. Pruning
    // walks from the root but skips `target/` — a member crate may have built
    // there, and walking it would be slow and pointless.
    let expected: std::collections::HashSet<String> = user_src_files
        .iter()
        .map(|(p, _)| p.clone())
        .chain(std::iter::once("src/main.rs".to_string()))
        .chain(std::iter::once("build.rs".to_string()))
        .collect();
    remove_stale_rs(dest, dest, &expected);

    // NOTE: Cargo.lock is intentionally NOT deleted here. Re-resolving the
    // dependency graph on every save made saving slow (cargo re-solves the
    // version graph before each check). The lock is reset only when the
    // chip/toolchain changes — see `AppIde::reset_workspace_lock`.

    // Files common to all toolchains. Written ONLY when changed (see
    // `write_if_changed`) so unchanged files keep their mtimes and neither
    // cargo nor rust-analyzer re-processes them.
    write_if_changed(&dest.join("Cargo.toml"), files.cargo_toml.as_bytes())?;
    write_if_changed(
        &dest.join(".cargo").join("config.toml"),
        files.cargo_config.as_bytes(),
    )?;
    write_if_changed(&dest.join("src").join("main.rs"), files.main_rs.as_bytes())?;
    write_if_changed(&dest.join(".gitignore"), files.gitignore.as_bytes())?;

    // memory.x + build.rs — only for RustEmbedded (STM32/ARM).
    //
    // For EspRust: esp-hal 0.23 generates its own complete memory.x (with
    // IROM, DROM, IRAM, DRAM, RTC_FAST) in its build-script OUT_DIR.
    // linkall.x starts with `INCLUDE "memory.x"` and searches the linker
    // -L paths in order.  If a project-level memory.x is present (from a
    // previous build or toolchain switch), it shadows esp-hal's file, causing
    // either "IROM already defined" (if -Tmemory.x is also present) or
    // missing regions (if the stale file is incomplete).
    // → Delete stale copies for ESP; write-if-changed for RustEmbedded.
    //   (The old remove-then-rewrite bumped build.rs's mtime on EVERY call,
    //   which made cargo RE-RUN the build script — and therefore re-check the
    //   whole crate — on every Save/Build/Clippy.)
    if files.memory_x.is_empty() {
        let _ = fs::remove_file(dest.join("memory.x"));
        let _ = fs::remove_file(dest.join("build.rs"));
    } else {
        write_if_changed(&dest.join("memory.x"), files.memory_x.as_bytes())?;
        write_if_changed(&dest.join("build.rs"), files.build_rs.as_bytes())?;
    }

    // User source files — root-relative, so this also writes the sources of
    // every extracted library crate.
    for (rel_path, content) in user_src_files {
        let full = dest.join(rel_path);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent)?;
        }
        write_if_changed(&full, content.as_bytes())?;
    }

    // mcu.config — virtual modules + clock state, persisted out-of-source at the
    // project root (not in src/, so the project tree doesn't show it). Written
    // only when there's something to persist; a stale one is removed otherwise.
    let mcu_config_path = dest.join(crate::panels::mcu_module::mcu_config::FILE_NAME);
    if mcu_config.trim().is_empty() {
        let _ = fs::remove_file(&mcu_config_path);
    } else {
        write_if_changed(&mcu_config_path, mcu_config.as_bytes())?;
    }

    // project_structure.config — same deal, but view state rather than config:
    // gitignored, and removed when there is nothing left to remember.
    let structure_path = dest.join(crate::panels::mcu_module::structure_config::FILE_NAME);
    if structure_config.trim().is_empty() {
        let _ = fs::remove_file(&structure_path);
    } else {
        write_if_changed(&structure_path, structure_config.as_bytes())?;
    }

    // ── Library crates left by ANOTHER project (build workspace only) ────────
    // The build workspace is a single directory shared by every project ever
    // opened, so a crate extracted elsewhere stays behind and accumulates —
    // eventually confusing cargo or rust-analyzer.
    //
    // Guarded by an exact path match against `build_workspace_dir()`, and
    // deliberately NOT extended to the user's project: a crate they created but
    // have not yet listed in `[workspace] members` is indistinguishable from
    // debris, and deleting it would be exactly the data loss this feature just
    // learned to avoid. If the comparison ever fails we simply skip the prune —
    // the safe direction.
    if dest == build_workspace_dir() {
        prune_foreign_crates(dest, &workspace_members(&files.cargo_toml));
    }

    Ok(())
}

/// Absolute path of the throw-away workspace every build / check / flash / size
/// run uses. It is a COPY of the project — the only place where deleting files
/// that don't belong to the current project is safe.
pub fn build_workspace_dir() -> std::path::PathBuf {
    std::env::temp_dir().join("embedded_ide_0_check")
}

/// Delete top-level directories of `root` that hold a `Cargo.toml` but are not
/// workspace `members` — library crates left behind by a DIFFERENT project.
///
/// The caller must guarantee `root` is disposable; see the call site. `src`,
/// `target`, `.cargo` and `.git` are never touched.
fn prune_foreign_crates(root: &Path, members: &[String]) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if matches!(name.as_str(), "src" | "target" | ".cargo" | ".git") {
            continue;
        }
        // Only crate roots are candidates — a plain folder is not ours to judge.
        if !path.join("Cargo.toml").is_file() {
            continue;
        }
        // A member may be nested (`crates/foo`); its first segment protects the
        // whole branch.
        let is_member = members
            .iter()
            .any(|m| m == &name || m.split('/').next() == Some(name.as_str()));
        if !is_member {
            let _ = fs::remove_dir_all(&path);
        }
    }
}

/// Directory names listed in the root manifest's `[workspace] members = [...]`.
/// Hand-parsed (no toml dependency): track the current `[section]`, then read
/// every quoted string in the `members` value, which may span lines.
pub fn workspace_members(cargo_toml: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_workspace = false;
    let mut collecting = false;
    for line in cargo_toml.lines() {
        let t = line.trim();
        if t.starts_with('[') && !collecting {
            // `[workspace.package]` etc. are not the members list.
            in_workspace = t == "[workspace]";
            continue;
        }
        if !in_workspace {
            continue;
        }
        if !collecting {
            let Some(rest) = t.strip_prefix("members") else {
                continue;
            };
            if !rest.trim_start().starts_with('=') {
                continue;
            }
            collecting = true;
            push_quoted(rest, &mut out);
        } else {
            push_quoted(t, &mut out);
        }
        if t.contains(']') {
            collecting = false;
            in_workspace = false; // one members list is enough
        }
    }
    out
}

/// Append every `"..."` substring of `s` to `out`.
fn push_quoted(s: &str, out: &mut Vec<String>) {
    let mut rest = s;
    while let Some(open) = rest.find('"') {
        let after = &rest[open + 1..];
        let Some(close) = after.find('"') else { return };
        let val = &after[..close];
        if !val.is_empty() {
            out.push(val.to_owned());
        }
        rest = &after[close + 1..];
    }
}


/// Write `content` to `path` ONLY when it differs from what's already on disk.
/// Keeping unchanged files' mtimes stable is critical: a changed mtime makes
/// cargo re-fingerprint the file (and for `build.rs`, re-run the build script →
/// re-check the whole crate) and makes rust-analyzer's VFS re-read and
/// re-analyze it — so blindly rewriting every file on every Save/Build/Clippy
/// was a main driver of the "everything gets slower over a session" problem.
fn write_if_changed(path: &Path, content: &[u8]) -> io::Result<()> {
    if let Ok(existing) = fs::read(path) {
        if existing == content {
            return Ok(());
        }
    }
    fs::write(path, content)
}

/// Walks `dir` recursively and removes every `.rs` file whose path relative to
/// `root` is **not** listed in `keep`.  Errors on individual files are silently
/// ignored — a failed removal produces no stale content (the file stays) and
/// does not abort the project write.
fn remove_stale_rs(root: &Path, dir: &Path, keep: &std::collections::HashSet<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Build output and VCS metadata are not ours to prune.
            let name = entry.file_name();
            if name == "target" || name == ".git" {
                continue;
            }
            remove_stale_rs(root, &path, keep);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            if let Ok(rel) = path.strip_prefix(root) {
                // Normalise to forward slashes so the lookup matches on Windows
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                if !keep.contains(&rel_str) {
                    let _ = fs::remove_file(&path);
                }
            }
        }
    }
}

/// Default `src/main.rs` for an ESP32-C3 project (no pin layout configured yet).
pub fn esp32c3_fresh_main_rs() -> String {
    r#"// Auto-generated by Embedded IDE
// MCU: ESP32-C3 | HAL: esp-hal

#![no_std]
#![no_main]

pub mod pins;


esp_bootloader_esp_idf::esp_app_desc!();

#[esp_hal::main]
fn main() -> ! {
    let peripherals = esp_hal::init(esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::max()));
    loop {
        // Your main loop code here.
    }
}
"#
    .to_string()
}

// ── RustEmbedded file generators ──────────────────────────────────────────────

fn cargo_toml_embedded(c: &ProjectDef) -> String {
    format!(
        "[package]\n\
         name    = \"{name}-project\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [[bin]]\n\
         name  = \"{name}-project\"\n\
         test  = false\n\
         bench = false\n\
         \n\
         [dependencies]\n\
         cortex-m    = {{ version = \"0.7\", features = [\"critical-section-single-core\"] }}\n\
         cortex-m-rt = \"0.7\"\n\
         panic-halt  = \"0.2\"\n\
         {hal}\n\
         \n\
         # Flash with:  cargo flash --chip {chip} --release\n\
         # Debug with:  cargo run   --release   (requires probe-rs in PATH)\n\
         \n\
         [profile.release]\n\
         panic         = \"abort\"\n\
         codegen-units = 1\n\
         debug         = true\n\
         lto           = true\n\
         opt-level     = \"s\"\n\
         \n\
         [profile.dev]\n\
         panic     = \"abort\"\n\
         opt-level = 1\n",
        name = c.pkg_name,
        hal = c.hal_dep,
        chip = c.probe_chip,
    )
}

fn cargo_config_embedded(c: &ProjectDef) -> String {
    format!(
        "[build]\n\
         target = \"{target}\"\n\
         \n\
         [target.{target}]\n\
         # Requires probe-rs: https://probe.rs/docs/getting-started/installation/\n\
         runner    = \"probe-rs run --chip {chip}\"\n\
         rustflags = [\n\
             \"-C\", \"link-arg=-Tlink.x\",\n\
         ]\n",
        target = c.target,
        chip = c.probe_chip,
    )
}

fn memory_x(c: &ProjectDef) -> String {
    format!(
        "/* {comment} */\n\
         MEMORY\n\
         {{\n\
             FLASH : ORIGIN = {flash_o}, LENGTH = {flash_s}\n\
             RAM   : ORIGIN = {ram_o},   LENGTH = {ram_s}\n\
         }}\n",
        comment = c.memory_comment,
        flash_o = c.flash_origin,
        flash_s = c.flash_size,
        ram_o = c.ram_origin,
        ram_s = c.ram_size,
    )
}

/// `build.rs` placed in the project root.
/// Copies `memory.x` to `OUT_DIR` so the linker script (`link.x` for ARM,
/// `linkall.x` for ESP32) can find it via the `rustc-link-search` path.
fn build_rs_embedded() -> String {
    let mut s = String::new();
    s.push_str("use std::env;\n");
    s.push_str("use std::fs::File;\n");
    s.push_str("use std::io::Write;\n");
    s.push_str("use std::path::PathBuf;\n");
    s.push_str("\n");
    s.push_str("fn main() {\n");
    s.push_str("    let out = PathBuf::from(env::var_os(\"OUT_DIR\").unwrap());\n");
    s.push_str("    File::create(out.join(\"memory.x\"))\n");
    s.push_str("        .unwrap()\n");
    s.push_str("        .write_all(include_bytes!(\"memory.x\"))\n");
    s.push_str("        .unwrap();\n");
    s.push_str("    println!(\"cargo:rustc-link-search={}\", out.display());\n");
    s.push_str("    println!(\"cargo:rerun-if-changed=memory.x\");\n");
    s.push_str("}\n");
    s
}

// ── EspRust file generators ───────────────────────────────────────────────────

fn cargo_toml_esp(c: &ProjectDef) -> String {
    format!(
        "[package]\n\
         name    = \"{name}-project\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [[bin]]\n\
         name  = \"{name}-project\"\n\
         test  = false\n\
         bench = false\n\
         \n\
         [dependencies]\n\
         esp-hal       = {{ version = \"~1.1.0\", features = [\"{chip}\", \"unstable\"] }}\n\
         esp-println   = {{ version = \"0.13\", features = [\"{chip}\", \"log\"] }}\n\
         esp-bootloader-esp-idf = {{ version = \"0.5.0\", features = [\"{chip}\"] }}\n\
         critical-section = \"1.2.0\"\n\
         \n\
         # Flash with: espflash flash --chip {chip} --release\n\
         # Install:    cargo install espflash\n\
         \n\
         [profile.release]\n\
         codegen-units = 1\n\
         debug         = 2\n\
         lto           = \"fat\"\n\
         opt-level     = \"s\"\n\
         \n\
         [profile.dev]\n\
         opt-level     = \"s\"\n",
        name = c.pkg_name,
        chip = c.probe_chip, // "esp32c3"
    )
}

fn cargo_config_esp(c: &ProjectDef) -> String {
    format!(
        "[target.{target}]\n\
         # --ignore-app-descriptor: esp-hal bare-metal binaries do not carry an\n\
         # ESP-IDF app descriptor; espflash 4.x requires this flag to skip the\n\
         # descriptor check. Add --monitor to open the serial console after flash.\n\
         #runner = \"espflash flash --monitor --ignore-app-descriptor\"\n\
         runner = \"espflash flash --monitor --chip {chip}\"\n\
         # esp-hal 0.23 places linkall.x + memory.x in its OUT_DIR via its\n\
         # build script.  linkall.x uses `INCLUDE memory.x` internally, so\n\
         # the chip memory map (IROM, DROM, IRAM, DRAM, RTC_SLOW) is already\n\
         # present.  Only -Tlinkall.x is needed here; supplying a second\n\
         # -Tmemory.x would redefine those regions and cause a linker error.\n\
         rustflags = [\n\
            \"-C\", \"link-arg=-Tlinkall.x\",\n\
            # \"-C\", \"force-frame-pointers\",\n\
         ]\n\
         \n\
         [build]\n\
         target = \"{target}\"\n\
         \n\
         [env]\n\
         ESP_LOG = \"INFO\"\n\
         \n\
         [unstable]\n\
         build-std = [\"core\"]\n",
        target = c.target,
        chip = c.probe_chip,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn stm32_def() -> ProjectDef {
        ProjectDef {
            pkg_name: "demo".into(),
            target: "thumbv7m-none-eabi".into(),
            flash_origin: "0x08000000".into(),
            flash_size: "64K".into(),
            ram_origin: "0x20000000".into(),
            ram_size: "20K".into(),
            hal_dep: "stm32f1xx-hal = { version = \"0.10\" }".into(),
            probe_chip: "STM32F103C8".into(),
            memory_comment: "STM32F103C8".into(),
        }
    }

    #[test]
    fn cargo_toml_has_hash_markers_and_user_tail() {
        let f = gen_config(
            ConfigFile::CargoToml,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(f.contains("# <<< GENERATED"), "begin marker:\n{f}");
        assert!(f.contains("# <<< GENERATED END >>>"), "end marker");
        assert!(f.contains("stm32f1xx-hal"), "generated body present");
        assert!(
            f.contains("Add your own entries below"),
            "user tail present"
        );
    }

    #[test]
    fn memory_x_uses_block_comments_build_rs_uses_slashes() {
        let mx = gen_config(
            ConfigFile::MemoryX,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(
            mx.starts_with("/* <<< GENERATED"),
            "ld block comment:\n{mx}"
        );
        assert!(mx.contains("0x08000000"), "flash origin in body");
        let br = gen_config(
            ConfigFile::BuildRs,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(br.contains("// <<< GENERATED"), "rust line comment:\n{br}");
    }

    #[test]
    fn esp_has_no_memory_x_or_build_rs() {
        assert!(gen_config(ConfigFile::MemoryX, &stm32_def(), &ToolchainKind::EspRust).is_empty());
        assert!(gen_config(ConfigFile::BuildRs, &stm32_def(), &ToolchainKind::EspRust).is_empty());
    }

    #[test]
    fn splice_preserves_user_tail_and_is_idempotent() {
        let tc = ToolchainKind::RustEmbedded;
        // User adds an extra dependency in the editable tail.
        let edited = format!(
            "{}\n[dependencies.heapless]\nversion = \"0.8\"\n",
            gen_config(ConfigFile::CargoToml, &stm32_def(), &tc)
        );

        let once = splice_config(ConfigFile::CargoToml, &edited, &stm32_def(), &tc);
        assert!(once.contains("heapless"), "user tail preserved:\n{once}");
        assert!(once.contains("stm32f1xx-hal"), "generated block refreshed");

        // Re-splicing with the same chip is a no-op (no blank-line creep).
        let twice = splice_config(ConfigFile::CargoToml, &once, &stm32_def(), &tc);
        assert_eq!(once, twice, "splice must be idempotent");
    }

    #[test]
    fn splice_refreshes_block_on_chip_change_keeping_edits() {
        let tc = ToolchainKind::RustEmbedded;
        let edited = format!(
            "{}/* my note */\n",
            gen_config(ConfigFile::MemoryX, &stm32_def(), &tc)
        );
        let mut other = stm32_def();
        other.flash_origin = "0x08002000".into(); // different chip memory map
        let spliced = splice_config(ConfigFile::MemoryX, &edited, &other, &tc);
        assert!(spliced.contains("0x08002000"), "block reflects new chip");
        assert!(!spliced.contains("0x08000000"), "old generated value gone");
        assert!(spliced.contains("/* my note */"), "user edit preserved");
    }

    #[test]
    fn ensure_can_deps_adds_removes_and_is_idempotent() {
        let base = gen_config(
            ConfigFile::CargoToml,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert!(!base.contains("bxcan"), "base has no CAN deps");

        // Adding when CAN is configured inserts both crates inside [dependencies].
        let with = ensure_can_deps(&base, true);
        assert!(with.contains("bxcan = \"0.7\""), "bxcan added:\n{with}");
        assert!(with.contains("nb    = \"1\""), "nb added");
        let deps_idx = with.find("[dependencies]").unwrap();
        assert!(
            with[deps_idx..].find("bxcan").unwrap()
                < with[deps_idx..].find("stm32f1xx-hal").unwrap()
                || with.contains("bxcan"),
            "bxcan within deps section"
        );

        // Re-running with CAN still on is a no-op (no duplicate lines / churn).
        let with2 = ensure_can_deps(&with, true);
        assert_eq!(with, with2, "add must be idempotent");
        assert_eq!(with.matches("bxcan").count(), 1, "no duplicate bxcan");

        // Removing when CAN is gone drops exactly the two lines, back to base.
        let removed = ensure_can_deps(&with, false);
        assert!(!removed.contains("bxcan"), "bxcan removed:\n{removed}");
        assert!(!removed.contains("nb    ="), "nb removed");
        assert_eq!(removed, base, "removal restores the original");

        // Removing when there's nothing to remove is also a no-op.
        assert_eq!(ensure_can_deps(&base, false), base);
    }

    #[test]
    fn ensure_usb_deps_adds_removes_deps_and_hal_feature() {
        // A Cargo.toml whose HAL line carries a features array (as generated).
        let base = "[dependencies]\n\
                    stm32f1xx-hal = { version = \"0.10\", features = [\"stm32f103\", \"rt\"] }\n";

        let with = ensure_usb_deps(base, true);
        assert!(
            with.contains("usb-device  = \"0.2\""),
            "usb-device added:\n{with}"
        );
        assert!(with.contains("usbd-serial = \"0.1\""), "usbd-serial added");
        assert!(with.contains("\"stm32-usbd\""), "stm32-usbd feature added");
        // Idempotent.
        assert_eq!(ensure_usb_deps(&with, true), with, "add must be idempotent");
        assert_eq!(
            with.matches("\"stm32-usbd\"").count(),
            1,
            "feature not duplicated"
        );

        // Removing restores the original (deps + feature gone).
        let removed = ensure_usb_deps(&with, false);
        assert!(
            !removed.contains("usb-device"),
            "usb-device removed:\n{removed}"
        );
        assert!(!removed.contains("stm32-usbd"), "feature removed");
        assert_eq!(removed, base, "removal restores the original");
        assert_eq!(
            ensure_usb_deps(base, false),
            base,
            "no-op when nothing to remove"
        );
    }

    /// A hand-written file with no GEN markers (external project) must be shown
    /// verbatim — never get a generated block injected above it (which would
    /// duplicate `[package]`).
    #[test]
    fn external_file_without_markers_is_left_untouched() {
        let external = "[package]\nname = \"theirs\"\n\n[dependencies]\nserde = \"1\"\n";
        let out = splice_config(
            ConfigFile::CargoToml,
            external,
            &stm32_def(),
            &ToolchainKind::RustEmbedded,
        );
        assert_eq!(out, external);
    }

    /// Only foreign CRATE directories go; everything else in the workspace is
    /// left alone. (Pruning is guarded to the throw-away build workspace at the
    /// call site — this covers the decision, not the guard.)
    #[test]
    fn prune_removes_only_non_member_crates() {
        let dir = tempfile::TempDir::new().unwrap();
        let root = dir.path();
        let crate_at = |name: &str| {
            fs::create_dir_all(root.join(name).join("src")).unwrap();
            fs::write(root.join(name).join("Cargo.toml"), "[package]
").unwrap();
        };
        crate_at("mw_radar");   // current member  -> keep
        crate_at("stale_lib");  // another project -> remove
        fs::create_dir_all(root.join("src")).unwrap();       // firmware sources
        fs::create_dir_all(root.join("target")).unwrap();    // build output
        fs::create_dir_all(root.join("assets")).unwrap();    // plain folder, no manifest

        prune_foreign_crates(root, &["mw_radar".to_string()]);

        assert!(root.join("mw_radar").is_dir(), "member kept");
        assert!(!root.join("stale_lib").exists(), "foreign crate removed");
        assert!(root.join("src").is_dir(), "src kept");
        assert!(root.join("target").is_dir(), "target kept");
        assert!(root.join("assets").is_dir(), "a folder without Cargo.toml is not ours to judge");
    }

    /// A nested member (`crates/foo`) must protect its whole branch.
    #[test]
    fn a_nested_member_protects_its_top_level_directory() {
        let dir = tempfile::TempDir::new().unwrap();
        let root = dir.path();
        fs::create_dir_all(root.join("crates")).unwrap();
        fs::write(root.join("crates").join("Cargo.toml"), "[package]
").unwrap();

        prune_foreign_crates(root, &["crates/foo".to_string()]);
        assert!(root.join("crates").is_dir());
    }
}
