[package]
name = "embedded_ide_0"
version = "0.1.0"
edition = "2024"
author = "Traian Istrati"

[dependencies]
eframe           = { version = "0.34.1", features = ["persistence"] }
egui             = "0.34.1"
egui_code_editor = "0.3.2"
egui-phosphor    = { version = "0.12.0", features = ["regular"] }
rfd              = "0.15"
serde_json       = "1"
serde            = { version = "1", features = ["derive"] }
similar          = "2"
ron              = "0.8"
notify           = "6"
serialport = "4"
rusb = "0.9"
ureq = "2"


[dev-dependencies]
tempfile = "3.8"
