//! Async `embassy-stm32` code generation — the [`Runtime::Async`] path.
//!
//! Structurally the twin of [`super::embassy_common`] (blocking), differing only
//! in the *entry point*: instead of `#[cortex_m_rt::entry] fn main() -> !`, the
//! async runtime uses `#[embassy_executor::main] async fn main(Spawner)` and the
//! executor drives the future. GPIO bindings are byte-for-byte identical
//! (`Output::new` / `Input::new` are the same embassy types in both modes), so
//! the per-pin body comes straight from [`embassy_common::gpio_bindings`] and
//! round-trips through [`super::parse_main_rs`] the same way.
//!
//! Selected for every STM32 family that runs on `embassy-stm32` when the project
//! Runtime is Async (see [`super::family::AsyncEmbassyBackend`]). The clock block
//! is shared with the blocking backend ([`super::rcc::graph_clock_block`]) —
//! `embassy_stm32::init` is runtime-agnostic.
//!
//! [`Runtime::Async`]: crate::panels::mcu_module::mcu::Runtime

use super::common::sanitize_label;
use super::embassy_common::{gpio_bindings, NO_PINS_PLACEHOLDER};
use super::{mcu_id_marker_line, GEN_BEGIN, GEN_END, USER_TAIL};
use crate::panels::mcu_module::modules::{
    AsyncBusMode, I2cModuleConfig, Parity, SpiModuleConfig, StopBits, UsartModuleConfig,
};
use crate::panels::mcu_module::pins::logic::pin::Pin;
use crate::panels::mcu_module::pins::logic::pin_function::PinFunction;
use std::collections::BTreeMap;

/// Invariant file header for the async runtime (above `GEN_BEGIN`, rebuilt on
/// every re-splice). Imports `Spawner` (the entry-fn argument) and drops the
/// blocking `cortex_m_rt::entry` — the `#[embassy_executor::main]` macro owns the
/// entry point.
///
/// The `unused_*` lints are allowed at **crate** level here, not on `fn main`:
/// `#[embassy_executor::main]` rewrites the fn into a spawned task and does NOT
/// carry a function-level `#[allow]` onto the moved body, so an unwired pin (or
/// the `let p` on a chip with no pins yet) would otherwise warn. The blocking
/// backend can scope the allow to `fn main`; async needs the crate attribute.
pub fn invariant_header(mcu_name: &str, mcu_id: &str) -> String {
    format!(
        "// Auto-generated by Embedded IDE\n\
         // MCU: {mcu_name} | HAL: embassy-stm32 (async)\n\
         {id}\n\
         #![no_std]\n\
         #![no_main]\n\
         #![allow(unused_variables, unused_mut)]\n\n\
         use embassy_executor::Spawner;\n\
         use panic_halt as _;\n\n",
        id = mcu_id_marker_line(mcu_id),
    )
}

/// The generated section for the async runtime: gpio `use` items (only when
/// needed), the `#[embassy_executor::main]` entry, the caller-supplied
/// `clock_block` (which must define `let p = …` and end in `\n`), one `let`
/// binding per configured GPIO/raw pin, then `periph_calls` — the peripheral init
/// lines (e.g. USART `init(...)`) whose pins are NOT in `pins` (they are moved
/// into the driver). Opens `async fn main(_spawner: Spawner)` — `USER_TAIL`
/// closes it with the editable loop.
pub fn make_generated_section(
    mcu_name: &str,
    pins: &[&Pin],
    clock_block: &str,
    periph_calls: &str,
) -> String {
    let (use_line, mut body) = gpio_bindings(pins);
    if !periph_calls.is_empty() {
        if !body.is_empty() {
            body.push('\n');
        }
        body.push_str(periph_calls);
    }
    if body.is_empty() {
        body.push_str(NO_PINS_PLACEHOLDER);
    }
    // No fn-level `#[allow]` — the macro would drop it; the crate attribute in
    // `invariant_header` covers the unused-pin / unused-`p` cases instead.
    format!(
        "{GEN_BEGIN}\n\
         {use_line}\n\
         #[embassy_executor::main]\n\
         async fn main(_spawner: Spawner) {{\n\
         \x20   // {mcu_name}\n\
         {clock_block}\
         \n\
         {body}\
         {GEN_END}\n",
    )
}

/// Re-splice the generated section of an existing `main.rs`, preserving the user
/// tail. Unlike the blocking splice, the *header* is rebuilt too (not kept from
/// `existing[..begin]`): this is what lets a Blocking→Async runtime switch swap
/// the header's imports/entry over an existing file. Rebuilds from scratch when
/// the markers are gone.
pub fn splice_section(existing: &str, new_section: &str, mcu_name: &str, mcu_id: &str) -> String {
    let header = invariant_header(mcu_name, mcu_id);
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        let after = existing[end..].trim_start_matches('\n');
        // Preserve only the user code AFTER the markers; the header above them is
        // regenerated so a runtime switch updates the imports + entry.
        let _ = begin; // header replaces everything before the markers
        format!("{header}{new_section}\n{after}")
    } else {
        format!("{header}{new_section}\n{USER_TAIL}")
    }
}

// ── Async USART config file (embassy BufferedUart → embedded-io-async) ─────────

/// `src/pins/configs/usart{N}.rs` for the async runtime: an embassy
/// `BufferedUart` exposed through the STANDARD `embedded-io-async` traits, so app
/// code written generic over `embedded_io_async::{Read, Write}` is portable. The
/// interrupt-driven driver needs an ISR binding (`bind_interrupts!`, module-local
/// `Irqs`) and `'static` TX/RX buffers (`static_cell::StaticCell`). `init` is
/// GENERIC over the pin types (`impl RxPin/TxPin`) so the file is the same for
/// every chip — only the instance number differs; the concrete pins are chosen at
/// the call site in `main.rs`. Real-compile verified on STM32F411RE.
const ASYNC_USART_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const BAUDRATE: u32 = {BAUD};
const DATA_BITS: u8 = {DATA}; // 7, 8, 9
const PARITY: char = '{PARITY}'; // 'N' None, 'O' Odd, 'E' Even
const STOP_BITS: u8 = {STOP}; // 1, 2
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// `init` returns a value implementing the STANDARD `embedded-io-async` traits
// (`Read` + `Write`), so your application code stays portable across chips/HALs:
//
//     async fn app<S: embedded_io_async::Read + embedded_io_async::Write>(s: &mut S) { /* … */ }
use embassy_stm32::usart::{
    BufferedInterruptHandler, BufferedUart, Config, DataBits, Parity, RxPin, StopBits, TxPin,
};
use embassy_stm32::{bind_interrupts, peripherals, Peri};
use static_cell::StaticCell;

/// Byte capacity of the interrupt-driven TX/RX ring buffers.
const BUF_LEN: usize = 256;

bind_interrupts!(struct Irqs {
    USART{N} => BufferedInterruptHandler<peripherals::USART{N}>;
});

fn get_config() -> Config {
    let mut config = Config::default();
    config.baudrate = BAUDRATE;
    config.data_bits = match DATA_BITS {
        7 => DataBits::DataBits7,
        9 => DataBits::DataBits9,
        _ => DataBits::DataBits8,
    };
    config.parity = match PARITY {
        'O' => Parity::ParityOdd,
        'E' => Parity::ParityEven,
        _ => Parity::ParityNone,
    };
    config.stop_bits = match STOP_BITS {
        2 => StopBits::STOP2,
        _ => StopBits::STOP1,
    };
    config
}

/// Initialise USART{N} as an async `embedded-io-async` Read + Write value.
pub fn init<'d>(
    usart: Peri<'d, peripherals::USART{N}>,
    rx: Peri<'d, impl RxPin<peripherals::USART{N}>>,
    tx: Peri<'d, impl TxPin<peripherals::USART{N}>>,
) -> impl embedded_io_async::Read + embedded_io_async::Write + 'd {
    static TX_BUF: StaticCell<[u8; BUF_LEN]> = StaticCell::new();
    static RX_BUF: StaticCell<[u8; BUF_LEN]> = StaticCell::new();
    let tx_buf = TX_BUF.init([0; BUF_LEN]);
    let rx_buf = RX_BUF.init([0; BUF_LEN]);
    BufferedUart::new(usart, rx, tx, tx_buf, rx_buf, Irqs, get_config()).unwrap()
}
"#;

/// The USART peripheral instances that have BOTH a TX and an RX pin configured —
/// the ones an async `BufferedUart` (bidirectional) can be built for. Returns
/// `(instance, tx_pin_name, rx_pin_name)` sorted by instance. A one-sided UART
/// (only TX or only RX) is skipped in v1: `BufferedUart::new` needs both.
fn usart_wires(pins: &[&Pin]) -> Vec<(u8, String, String)> {
    let find = |want: PinFunction| -> Option<String> {
        pins.iter()
            .find(|p| !p.reserved && p.selected_function == want)
            .map(|p| p.name.clone())
    };
    // Instances present on the wired pins (embassy chips have USART1/2/3/6/…).
    let mut instances: Vec<u8> = pins
        .iter()
        .filter_map(|p| match p.selected_function {
            PinFunction::UsartTx(n) | PinFunction::UsartRx(n) => Some(n),
            _ => None,
        })
        .collect();
    instances.sort_unstable();
    instances.dedup();

    instances
        .into_iter()
        .filter_map(|n| {
            let tx = find(PinFunction::UsartTx(n))?;
            let rx = find(PinFunction::UsartRx(n))?;
            Some((n, tx, rx))
        })
        .collect()
}

/// SPI instances with SCK + MOSI + MISO all wired (a full-duplex `SpiBus`).
/// Returns `(instance, sck, mosi, miso)` sorted by instance.
fn spi_wires(pins: &[&Pin]) -> Vec<(u8, String, String, String)> {
    let find = |want: PinFunction| -> Option<String> {
        pins.iter()
            .find(|p| !p.reserved && p.selected_function == want)
            .map(|p| p.name.clone())
    };
    let mut instances: Vec<u8> = pins
        .iter()
        .filter_map(|p| match p.selected_function {
            PinFunction::SpiSck(n) | PinFunction::SpiMosi(n) | PinFunction::SpiMiso(n) => Some(n),
            _ => None,
        })
        .collect();
    instances.sort_unstable();
    instances.dedup();
    instances
        .into_iter()
        .filter_map(|n| {
            let sck = find(PinFunction::SpiSck(n))?;
            let mosi = find(PinFunction::SpiMosi(n))?;
            let miso = find(PinFunction::SpiMiso(n))?;
            Some((n, sck, mosi, miso))
        })
        .collect()
}

/// I2C instances with both SCL + SDA wired. Returns `(instance, scl, sda)`.
fn i2c_wires(pins: &[&Pin]) -> Vec<(u8, String, String)> {
    let find = |want: PinFunction| -> Option<String> {
        pins.iter()
            .find(|p| !p.reserved && p.selected_function == want)
            .map(|p| p.name.clone())
    };
    let mut instances: Vec<u8> = pins
        .iter()
        .filter_map(|p| match p.selected_function {
            PinFunction::I2cScl(n) | PinFunction::I2cSda(n) => Some(n),
            _ => None,
        })
        .collect();
    instances.sort_unstable();
    instances.dedup();
    instances
        .into_iter()
        .filter_map(|n| {
            let scl = find(PinFunction::I2cScl(n))?;
            let sda = find(PinFunction::I2cSda(n))?;
            Some((n, scl, sda))
        })
        .collect()
}

/// The label suffix (`_imu`) for a module's generated handle, or "" when unset.
fn label_sfx(label: &str) -> String {
    let s = sanitize_label(label);
    if s.is_empty() {
        String::new()
    } else {
        format!("_{s}")
    }
}

/// Everything the async backend derives from the wired bus peripherals: the pins
/// they consume (to drop from raw bindings), the `main.rs` init call lines, and
/// the `src/pins/configs/*.rs` bodies. One pass over USART + SPI + I2C.
pub struct AsyncPeriphs {
    /// Pin names moved into a driver → excluded from the raw GPIO bindings.
    pub consumed_pins: Vec<String>,
    /// The `main.rs` peripheral init lines (with a section header). "" if none.
    pub init_calls: String,
    /// `(file_name, generated_body)` per configured bus peripheral.
    pub config_files: Vec<(String, String)>,
    /// True if any SPI/I2C uses async-DMA (drives the `embedded-hal-async` dep).
    pub any_async_dma: bool,
    /// True if any SPI/I2C exists at all (drives the `embedded-hal` 1.0 dep).
    pub any_spi_i2c: bool,
}

/// Whether a SPI/I2C module runs in async-DMA mode (else blocking).
fn is_dma(mode: AsyncBusMode) -> bool {
    mode == AsyncBusMode::AsyncDma
}

/// The DMA-channel placeholders for an async-DMA init call. Deliberately
/// undefined fields (`p.DMA_TX_TODO`) so the project fails to compile at exactly
/// this line until the user supplies channels valid for the peripheral on their
/// chip — the IDE can't know them (it doesn't model DMA).
const DMA_TODO: &str = "p.DMA_TX_TODO, p.DMA_RX_TODO";

pub fn async_peripherals(
    pins: &[&Pin],
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
) -> AsyncPeriphs {
    let mut consumed = Vec::new();
    let mut calls = String::new();
    let mut files = Vec::new();
    let mut any_async_dma = false;
    let mut any_spi_i2c = false;

    for (n, tx, rx) in usart_wires(pins) {
        consumed.push(tx.clone());
        consumed.push(rx.clone());
        let sfx = usart.get(&n).map(|c| label_sfx(&c.custom_label)).unwrap_or_default();
        // BufferedUart::new takes (peri, rx, tx, …); the config's `init` mirrors it.
        calls.push_str(&format!(
            "    let mut _serial{n}{sfx} = \
             pins::configs::usart{n}::init(p.USART{n}, p.{rx}, p.{tx});\n"
        ));
        files.push((format!("usart{n}.rs"), usart_config_file(n, usart.get(&n))));
    }

    for (n, sck, mosi, miso) in spi_wires(pins) {
        any_spi_i2c = true;
        consumed.push(sck.clone());
        consumed.push(mosi.clone());
        consumed.push(miso.clone());
        let cfg = spi.get(&n);
        let sfx = cfg.map(|c| label_sfx(&c.custom_label)).unwrap_or_default();
        let dma = cfg.map(|c| is_dma(c.async_mode)).unwrap_or(false);
        any_async_dma |= dma;
        if dma {
            calls.push_str(&format!(
                "    // TODO(async DMA): pass DMA channels valid for SPI{n} on this chip,\n\
                 \x20   //   e.g. p.DMA2_CH3 (tx) + p.DMA2_CH2 (rx). Replace the TODO fields below.\n"
            ));
            calls.push_str(&format!(
                "    let mut _spi{n}{sfx} = \
                 pins::configs::spi{n}::init(p.SPI{n}, p.{sck}, p.{mosi}, p.{miso}, {DMA_TODO});\n"
            ));
        } else {
            calls.push_str(&format!(
                "    let mut _spi{n}{sfx} = \
                 pins::configs::spi{n}::init(p.SPI{n}, p.{sck}, p.{mosi}, p.{miso});\n"
            ));
        }
        files.push((format!("spi{n}.rs"), spi_config_file(n, cfg)));
    }

    for (n, scl, sda) in i2c_wires(pins) {
        any_spi_i2c = true;
        consumed.push(scl.clone());
        consumed.push(sda.clone());
        let cfg = i2c.get(&n);
        let sfx = cfg.map(|c| label_sfx(&c.custom_label)).unwrap_or_default();
        let dma = cfg.map(|c| is_dma(c.async_mode)).unwrap_or(false);
        any_async_dma |= dma;
        if dma {
            calls.push_str(&format!(
                "    // TODO(async DMA): pass DMA channels valid for I2C{n} on this chip,\n\
                 \x20   //   e.g. p.DMA1_CH6 (tx) + p.DMA1_CH0 (rx). Replace the TODO fields below.\n"
            ));
            calls.push_str(&format!(
                "    let mut _i2c{n}{sfx} = \
                 pins::configs::i2c{n}::init(p.I2C{n}, p.{scl}, p.{sda}, {DMA_TODO});\n"
            ));
        } else {
            calls.push_str(&format!(
                "    let mut _i2c{n}{sfx} = \
                 pins::configs::i2c{n}::init(p.I2C{n}, p.{scl}, p.{sda});\n"
            ));
        }
        files.push((format!("i2c{n}.rs"), i2c_config_file(n, cfg)));
    }

    let init_calls = if calls.is_empty() {
        String::new()
    } else {
        format!("    // ── Peripheral initialisation ──\n{calls}")
    };
    AsyncPeriphs {
        consumed_pins: consumed,
        init_calls,
        config_files: files,
        any_async_dma,
        any_spi_i2c,
    }
}

/// Render [`ASYNC_USART_TMPL`] for instance `n` with the Virtual Module's config
/// (baud / data bits / parity / stop bits), or embassy defaults when unset.
pub fn usart_config_file(n: u8, cfg: Option<&UsartModuleConfig>) -> String {
    let baud = cfg.map(|c| c.baud_rate).unwrap_or(115_200);
    let data = cfg.map(|c| c.data_bits).unwrap_or(8);
    let parity = match cfg.map(|c| c.parity) {
        Some(Parity::Odd) => 'O',
        Some(Parity::Even) => 'E',
        _ => 'N',
    };
    let stop = match cfg.map(|c| c.stop_bits) {
        Some(StopBits::Two) => 2,
        _ => 1,
    };
    ASYNC_USART_TMPL
        .replace("{N}", &n.to_string())
        .replace("{BAUD}", &baud.to_string())
        .replace("{DATA}", &data.to_string())
        .replace("{PARITY}", &parity.to_string())
        .replace("{STOP}", &stop.to_string())
}

// ── Async SPI config file (blocking | async-DMA) ──────────────────────────────

/// Blocking SPI (`Spi::new_blocking`) exposed as the STANDARD blocking
/// `embedded-hal` 1.0 `SpiBus<u8>`. No DMA — compiles out of the box.
const ASYNC_SPI_TMPL_BLOCKING: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const SPI_MODE: u8 = {MODE}; // 0..=3 (CPOL/CPHA)
const CLOCK_HZ: u32 = {CLK};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// `init` returns a STANDARD `embedded-hal` 1.0 `SpiBus<u8>` (BLOCKING). A blocking
// bus in an async project is a common, valid pattern; for `.await`-able DMA SPI
// switch this module to "Async-DMA" in the IDE.
//
//     fn app<S: embedded_hal::spi::SpiBus<u8>>(spi: &mut S) { /* … */ }
use embassy_stm32::spi::{Config, MisoPin, MosiPin, SckPin, Spi, MODE_0, MODE_1, MODE_2, MODE_3};
use embassy_stm32::time::Hertz;
use embassy_stm32::{peripherals, Peri};

fn get_config() -> Config {
    let mut config = Config::default();
    config.mode = match SPI_MODE {
        1 => MODE_1,
        2 => MODE_2,
        3 => MODE_3,
        _ => MODE_0,
    };
    config.frequency = Hertz(CLOCK_HZ);
    config
}

/// Initialise SPI{N} as a blocking `embedded-hal` 1.0 SpiBus value.
pub fn init<'d>(
    spi: Peri<'d, peripherals::SPI{N}>,
    sck: Peri<'d, impl SckPin<peripherals::SPI{N}>>,
    mosi: Peri<'d, impl MosiPin<peripherals::SPI{N}>>,
    miso: Peri<'d, impl MisoPin<peripherals::SPI{N}>>,
) -> impl embedded_hal::spi::SpiBus<u8> + 'd {
    Spi::new_blocking(spi, sck, mosi, miso, get_config())
}
"#;

/// Async DMA SPI (`Spi::new`) exposed as `embedded-hal-async` `SpiBus<u8>`
/// (`.await`-able). Needs two DMA channels, passed by `main.rs`.
const ASYNC_SPI_TMPL_DMA: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const SPI_MODE: u8 = {MODE}; // 0..=3 (CPOL/CPHA)
const CLOCK_HZ: u32 = {CLK};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// `init` returns an ASYNC `embedded-hal-async` `SpiBus<u8>` (`.await`-able),
// backed by DMA. The DMA channels are passed in from `main.rs`.
//
//     async fn app<S: embedded_hal_async::spi::SpiBus<u8>>(spi: &mut S) { /* … */ }
use embassy_stm32::spi::{
    Config, MisoPin, MosiPin, RxDma, SckPin, Spi, TxDma, MODE_0, MODE_1, MODE_2, MODE_3,
};
use embassy_stm32::time::Hertz;
use embassy_stm32::{peripherals, Peri};

fn get_config() -> Config {
    let mut config = Config::default();
    config.mode = match SPI_MODE {
        1 => MODE_1,
        2 => MODE_2,
        3 => MODE_3,
        _ => MODE_0,
    };
    config.frequency = Hertz(CLOCK_HZ);
    config
}

/// Initialise SPI{N} as an async `embedded-hal-async` SpiBus value (DMA-backed).
pub fn init<'d>(
    spi: Peri<'d, peripherals::SPI{N}>,
    sck: Peri<'d, impl SckPin<peripherals::SPI{N}>>,
    mosi: Peri<'d, impl MosiPin<peripherals::SPI{N}>>,
    miso: Peri<'d, impl MisoPin<peripherals::SPI{N}>>,
    tx_dma: Peri<'d, impl TxDma<peripherals::SPI{N}>>,
    rx_dma: Peri<'d, impl RxDma<peripherals::SPI{N}>>,
) -> impl embedded_hal_async::spi::SpiBus<u8> + 'd {
    Spi::new(spi, sck, mosi, miso, tx_dma, rx_dma, get_config())
}
"#;

/// Render the SPI config file for instance `n`, picking the blocking or
/// async-DMA template from the module's [`AsyncBusMode`].
pub fn spi_config_file(n: u8, cfg: Option<&SpiModuleConfig>) -> String {
    let mode = cfg.map(|c| c.mode).unwrap_or(0);
    let clk = cfg.map(|c| c.clock_hz).unwrap_or(1_000_000);
    let tmpl = match cfg.map(|c| c.async_mode).unwrap_or_default() {
        AsyncBusMode::Blocking => ASYNC_SPI_TMPL_BLOCKING,
        AsyncBusMode::AsyncDma => ASYNC_SPI_TMPL_DMA,
    };
    tmpl.replace("{N}", &n.to_string())
        .replace("{MODE}", &mode.to_string())
        .replace("{CLK}", &clk.to_string())
}

// ── Async I2C config file (blocking | async-DMA) ──────────────────────────────

/// Blocking I2C (`I2c::new_blocking`) exposed as the STANDARD blocking
/// `embedded-hal` 1.0 `I2c`. No DMA/interrupts — compiles out of the box.
const ASYNC_I2C_TMPL_BLOCKING: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const CLOCK_HZ: u32 = {CLK};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// `init` returns a STANDARD `embedded-hal` 1.0 `I2c` (BLOCKING). A blocking bus in
// an async project is a common, valid pattern; for `.await`-able DMA I2C switch
// this module to "Async-DMA" in the IDE.
//
//     fn app<I: embedded_hal::i2c::I2c>(i2c: &mut I) { /* … */ }
use embassy_stm32::i2c::{Config, I2c, SclPin, SdaPin};
use embassy_stm32::time::Hertz;
use embassy_stm32::{peripherals, Peri};

fn get_config() -> Config {
    let mut config = Config::default();
    config.frequency = Hertz(CLOCK_HZ);
    config
}

/// Initialise I2C{N} as a blocking `embedded-hal` 1.0 I2c value.
pub fn init<'d>(
    i2c: Peri<'d, peripherals::I2C{N}>,
    scl: Peri<'d, impl SclPin<peripherals::I2C{N}>>,
    sda: Peri<'d, impl SdaPin<peripherals::I2C{N}>>,
) -> impl embedded_hal::i2c::I2c + 'd {
    I2c::new_blocking(i2c, scl, sda, get_config())
}
"#;

/// Async DMA I2C (`I2c::new`) exposed as `embedded-hal-async` `I2c`
/// (`.await`-able). Needs an interrupt binding (event + error) and two DMA
/// channels (passed by `main.rs`).
const ASYNC_I2C_TMPL_DMA: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const CLOCK_HZ: u32 = {CLK};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// `init` returns an ASYNC `embedded-hal-async` `I2c` (`.await`-able), backed by
// DMA. The DMA channels are passed in from `main.rs`.
//
//     async fn app<I: embedded_hal_async::i2c::I2c>(i2c: &mut I) { /* … */ }
use embassy_stm32::i2c::{
    Config, ErrorInterruptHandler, EventInterruptHandler, I2c, RxDma, SclPin, SdaPin, TxDma,
};
use embassy_stm32::time::Hertz;
use embassy_stm32::{bind_interrupts, peripherals, Peri};

bind_interrupts!(struct Irqs {
    I2C{N}_EV => EventInterruptHandler<peripherals::I2C{N}>;
    I2C{N}_ER => ErrorInterruptHandler<peripherals::I2C{N}>;
});

fn get_config() -> Config {
    let mut config = Config::default();
    config.frequency = Hertz(CLOCK_HZ);
    config
}

/// Initialise I2C{N} as an async `embedded-hal-async` I2c value (DMA-backed).
pub fn init<'d>(
    i2c: Peri<'d, peripherals::I2C{N}>,
    scl: Peri<'d, impl SclPin<peripherals::I2C{N}>>,
    sda: Peri<'d, impl SdaPin<peripherals::I2C{N}>>,
    tx_dma: Peri<'d, impl TxDma<peripherals::I2C{N}>>,
    rx_dma: Peri<'d, impl RxDma<peripherals::I2C{N}>>,
) -> impl embedded_hal_async::i2c::I2c + 'd {
    I2c::new(i2c, scl, sda, Irqs, tx_dma, rx_dma, get_config())
}
"#;

/// Render the I2C config file for instance `n`, picking the blocking or
/// async-DMA template from the module's [`AsyncBusMode`].
pub fn i2c_config_file(n: u8, cfg: Option<&I2cModuleConfig>) -> String {
    let clk = cfg.map(|c| c.clock_hz).unwrap_or(100_000);
    let tmpl = match cfg.map(|c| c.async_mode).unwrap_or_default() {
        AsyncBusMode::Blocking => ASYNC_I2C_TMPL_BLOCKING,
        AsyncBusMode::AsyncDma => ASYNC_I2C_TMPL_DMA,
    };
    tmpl.replace("{N}", &n.to_string()).replace("{CLK}", &clk.to_string())
}
