//! STM32 code generation — HAL code building, section splicing, pin parsing.

use super::super::clock::frequencies;
use super::super::clock::model::{ClockConfig, PllSrc, Stm32f1Clock, SysclkSrc};
use super::super::modules::{
    ApiStyle, CanModuleConfig, I2cModuleConfig, Parity, SpiModuleConfig, StopBits,
    UsartModuleConfig, UsbModuleConfig,
};
use super::super::pins::logic::pin::{GpioMode, Pin};
use super::super::pins::logic::pin_function::PinFunction;
use super::{GEN_BEGIN, GEN_END, USER_TAIL, mcu_id_marker_line, pin_binding, sanitize_label};
use std::collections::{BTreeMap, BTreeSet};

/// `_<sanitized label>` suffix for a module's generated handle variable, or ""
/// when the module has no user label. So a GI_SPI labelled "imu" turns `_spi1`
/// into `_spi1_imu` — the module analogue of the per-pin `<pin>_<type>_<label>`.
fn module_label_sfx(label: &str) -> String {
    let s = sanitize_label(label);
    if s.is_empty() {
        String::new()
    } else {
        format!("_{s}")
    }
}

/// Variable (binding) name for a pin: `<pin>_<type>[_<label>]`, e.g. `pc13_out`,
/// `pb9_i2c1_sda`, or `pc13_out_led` when the pin carries a user label. Only the
/// `let` binding and later references carry the suffix — the HAL field access
/// stays the bare pin (`meta.var`, e.g. `gpioc.pc13`).
fn binding_of(pin: &Pin, meta: &PinMeta) -> String {
    pin_binding(&meta.var, &pin.selected_function, &pin.custom_label)
}

// ── Section splicing ──────────────────────────────────────────────────────────

pub fn splice_section(existing: &str, new_section: &str, mcu_name: &str, mcu_id: &str) -> String {
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        // Strip ALL leading newlines after GEN_END, then re-add exactly one
        // blank line.  This makes splice idempotent: running it N times always
        // produces the same result instead of accumulating newlines.
        let after = existing[end..].trim_start_matches('\n');

        // Detect old format (had fn custom_config / fn loop_code after GEN_END).
        // Rebuild from scratch so the user tail is the new flat loop{} style.
        if after.contains("fn custom_config()") || after.contains("fn loop_code()") {
            return format!(
                "{}{}\n{}",
                invariant_header(mcu_name, mcu_id),
                new_section,
                USER_TAIL,
            );
        }

        // new_section already ends with "// <<< GENERATED END >>>\n"
        // + one more "\n" gives a single blank line before the user tail.
        format!("{}{}\n{}", &existing[..begin], new_section, after)
    } else {
        // Markers not found — rebuild from scratch.
        format!(
            "{}{}\n{}",
            invariant_header(mcu_name, mcu_id),
            new_section,
            USER_TAIL,
        )
    }
}

// ── Invariant file header ─────────────────────────────────────────────────────

pub fn invariant_header(mcu_name: &str, mcu_id: &str) -> String {
    format!(
        "// Auto-generated by Embedded IDE\n\
         // MCU: {mcu_name} | HAL: stm32f1xx-hal\n\
         {id}\n\
         #![no_std]\n\
         #![no_main]\n\n\
         pub mod pins;\n\n\
         use panic_halt as _;\n\
         use cortex_m_rt::entry;\n\n",
        id = mcu_id_marker_line(mcu_id),
    )
}

// ── Clock setup (rcc.cfgr chain) ──────────────────────────────────────────────

/// Format a Hz value as a stm32f1xx-hal rate literal (`72.MHz()`, `48.kHz()`…).
fn freq_lit(hz: u32) -> String {
    if hz % 1_000_000 == 0 {
        format!("{}.MHz()", hz / 1_000_000)
    } else if hz % 1_000 == 0 {
        format!("{}.kHz()", hz / 1_000)
    } else {
        format!("{hz}.Hz()")
    }
}

/// Build the `rcc.cfgr … .freeze(&mut flash.acr)` chain from the clock config.
///
/// Only knobs that deviate from the HAL's natural defaults are emitted, so the
/// default 72 MHz config produces exactly the original
/// `use_hse(8).sysclk(72).pclk1(36)` chain (no spurious diffs).
pub fn clock_setup_chain(clock: &ClockConfig) -> String {
    let c: Stm32f1Clock = match clock {
        // The graph is the only clock model — read its node states back into
        // the typed codegen intermediate.
        ClockConfig::Graph(gc) => {
            crate::panels::mcu_module::clock::graph::graph_to_stm32f1(&gc.for_codegen())
        }
        ClockConfig::None => Stm32f1Clock::default(),
    };
    let f = frequencies(&c);
    // Newline + 17 spaces → lines up the `.method()` calls under `rcc.cfgr`.
    const IND: &str = "\n                 ";

    let mut s = String::from("rcc.cfgr");
    let use_hse = c.hse_enabled
        && (c.sysclk_src == SysclkSrc::Hse
            || (c.sysclk_src == SysclkSrc::Pll
                && matches!(c.pll_src, PllSrc::Hse | PllSrc::HseDiv2)));
    if use_hse {
        s.push_str(&format!("{IND}.use_hse({})", freq_lit(c.hse_hz)));
    }
    s.push_str(&format!("{IND}.sysclk({})", freq_lit(f.sysclk)));
    s.push_str(&format!("{IND}.pclk1({})", freq_lit(f.pclk1)));
    if c.ahb_pre != 1 {
        s.push_str(&format!("{IND}.hclk({})", freq_lit(f.hclk)));
    }
    if c.apb2_pre != 1 {
        s.push_str(&format!("{IND}.pclk2({})", freq_lit(f.pclk2)));
    }
    if c.adc_pre != 6 {
        s.push_str(&format!("{IND}.adcclk({})", freq_lit(f.adcclk)));
    }
    s.push_str(&format!("{IND}.freeze(&mut flash.acr)"));
    s
}

// ── Generated section builder ─────────────────────────────────────────────────

/// The pieces of an STM32F1 init sequence, before they are arranged into a
/// program.
///
/// Extracted so the RTIC backend can lay the SAME init out inside `#[init]`
/// instead of `fn main`. Two copies of this logic would drift the first time a
/// peripheral is added, and only one of them would be the one under test.
pub(super) struct GenParts {
    /// Items for the `use stm32f1xx_hal::{ ... };` block, already indented.
    pub use_block: String,
    /// Top-level `use`s that cannot live inside the HAL block (USB).
    pub extra_uses: &'static str,
    /// `let mut afio = ...;` or empty.
    pub afio_line: &'static str,
    /// Right-hand side of `let clocks = ...`.
    pub clock_chain: String,
    /// `let mut gpioX = dp.GPIOX.split();` lines.
    pub port_splits: String,
    /// Per-pin `let` bindings, grouped by port.
    pub pin_section: String,
    /// Peripheral init calls (`pins::configs::usart1::init(...)`, ADC, CAN...).
    pub fn_calls: String,
}

/// Build the init pieces. `None` when no pin is configured — the caller decides
/// what an empty project looks like.
#[allow(clippy::too_many_arguments)]
/// How a pin's `let` binding is produced.
///
/// The bare-metal path takes `&mut` of the freshly-configured pin because
/// everything stays inside one `fn main` and nothing outlives it. RTIC cannot:
/// each pin is MOVED into a `Local` resource that outlives `#[init]`, and a
/// `&mut` to a temporary would not even compile. Same lines, one prefix apart.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Binding {
    /// `let p = &mut gpioa.pa0.into_...();` — the historical form.
    MutRef,
    /// `let p = gpioa.pa0.into_...();` — movable into an RTIC resource.
    Owned,
}

pub(super) fn gen_parts(
    binding_style: Binding,
    all_pins: &[&Pin],
    clock: &ClockConfig,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    can: &BTreeMap<u8, CanModuleConfig>,
    usb: &BTreeMap<u8, UsbModuleConfig>,
    gpio_native: bool,
    // `let x = Foo::new(pa0_out, …);` lines for the Custom modules — appended
    // last, after every binding/init they consume (see `Mcu::custom_module_inits`).
    custom_inits: &str,
) -> Option<GenParts> {
    let configured: Vec<(&Pin, PinMeta)> = all_pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .filter_map(|p| parse_pin(&p.name).map(|m| (*p, m)))
        .collect();

    if configured.is_empty() {
        return None;
    }

    // ── Ports used ───────────────────────────────────────────────────────────
    // A port whose pins are configured is split `let mut` — every `into_*` takes
    // `&mut gpioX.crl`. A port pulled in only to free the JTAG pins below is not
    // written through at all, so it must NOT be `mut`.
    let mut ports_written: BTreeSet<char> = BTreeSet::new();
    for (_, meta) in &configured {
        ports_written.insert(meta.port);
    }
    let mut ports_used: BTreeSet<char> = ports_written.clone();

    // ── JTAG pins ────────────────────────────────────────────────────────────
    // PA15, PB3 and PB4 come out of reset as the JTAG port, typed
    // `Pin<'B', 3, Debugger>` — a state with no `into_*` methods at all, so a
    // project using any of them did not compile. `afio.mapr.disable_jtag` is the
    // way out, and it takes ALL THREE at once (used or not), which is why the
    // ports of the other two get split here too.
    let jtag_used = configured
        .iter()
        .any(|(p, _)| JTAG_PINS.contains(&p.name.as_str()));
    // Two of three cannot be handed to the call, so a chip missing one is left
    // exactly as it was rather than given code that won't build either way.
    let jtag_pins_exist = JTAG_PINS
        .iter()
        .all(|n| all_pins.iter().any(|p| p.name == *n));
    let free_jtag = jtag_used && jtag_pins_exist;
    if free_jtag {
        ports_used.insert('A');
        ports_used.insert('B');
    }

    // ── Feature flags ────────────────────────────────────────────────────────
    let has_serial = configured.iter().any(|(p, _)| {
        matches!(
            p.selected_function,
            PinFunction::UsartTx(_) | PinFunction::UsartRx(_)
        )
    });
    let has_spi = configured.iter().any(|(p, _)| {
        matches!(
            p.selected_function,
            PinFunction::SpiSck(_) | PinFunction::SpiMosi(_)
        )
    });
    let has_i2c = configured.iter().any(|(p, _)| {
        matches!(
            p.selected_function,
            PinFunction::I2cScl(_) | PinFunction::I2cSda(_)
        )
    });
    let has_adc = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::AdcChannel { .. }));
    let has_timer = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::TimerPwm { .. }));
    let has_can = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::CanRx | PinFunction::CanTx));
    let has_usb = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::UsbDm | PinFunction::UsbDp));
    // CAN's `assign_pins` needs AFIO too (it may remap the pins), and so does
    // `disable_jtag` — it lives on `afio.mapr`.
    let needs_afio = has_serial || has_spi || has_i2c || has_timer || has_can || free_jtag;
    let has_periph_fns = has_serial || has_spi || has_i2c || has_adc || has_can;

    // ── SPI instances ────────────────────────────────────────────────────────
    let mut spi_instances: BTreeSet<u8> = BTreeSet::new();
    for (pin, _) in &configured {
        match pin.selected_function {
            PinFunction::SpiSck(n)
            | PinFunction::SpiMosi(n)
            | PinFunction::SpiMiso(n)
            | PinFunction::SpiNss(n) => {
                spi_instances.insert(n);
            }
            _ => {}
        }
    }

    // ── HAL use block ────────────────────────────────────────────────────────
    let mut use_items: Vec<String> = vec!["pac".into(), "prelude::*".into()];
    // if has_periph_fns || needs_afio {
    //     if needs_afio {
    //         use_items.push("afio".into());
    //     }
    //     use_items.push("rcc::Clocks".into());
    // }
    if has_serial {
        // use_items.push("serial::{self, Config, Serial}".into());
    }
    if has_spi {
        // let remaps = spi_instances
        //     .iter()
        //     .map(|n| format!("Spi{n}NoRemap"))
        //     .collect::<Vec<_>>()
        //     .join(", ");
        // use_items.push(format!(
        //     "spi::{{self, Mode, Phase, Polarity, Spi, {remaps}}}"
        // ));
    }
    if has_i2c {
        //  use_items.push("i2c::{self, BlockingI2c, Mode as I2cMode}".into());
    }
    if has_adc {
        use_items.push("adc".into());
    }
    if has_timer {
        use_items.push("timer::Timer".into());
    }
    if has_usb {
        use_items.push("usb::{Peripheral, UsbBus}".into());
    }

    let use_block = use_items
        .iter()
        .map(|s| format!("    {s},"))
        .collect::<Vec<_>>()
        .join("\n");

    // USB needs top-level `use`s from the external usb-device / usbd-serial
    // crates (auto-added to Cargo.toml) — these can't live in the HAL `use {}`.
    let extra_uses = if has_usb {
        "use usb_device::prelude::*;\nuse usbd_serial::{SerialPort, USB_CLASS_CDC};\n"
    } else {
        ""
    };

    // ── Pin declaration lines ────────────────────────────────────────────────
    let mut port_groups: BTreeMap<char, Vec<String>> = BTreeMap::new();
    for (pin, meta) in &configured {
        let expr = into_expr(
            &pin.selected_function,
            pin.io_mode,
            &meta.port_var,
            meta.crx,
        );
        let comment = pin.selected_function.label();
        let line = if is_comment_expr(&expr) {
            format!(
                "    // {}: {}",
                pin.name,
                expr.trim_start_matches("//").trim()
            )
        } else {
            // GPIO In/Out binding shape follows the project's GPIO api
            // (`gpio_native`):
            //  · Portable (default) → wrap in the `pins::configs::io` bridge so
            //    the binding is a STANDARD `embedded-hal` 1.0 pin — portable to
            //    any HAL. The wrapper is transparent (`.0` gives the raw HAL pin
            //    back).
            //  · Native → bind the raw HAL pin (no io.rs, no embedded-hal dep).
            //
            // A GPIO pin is bound BY VALUE (no `&mut` on the right-hand side):
            // owning it is what lets the user move it into a driver or a struct,
            // which a `&mut` to a temporary never allowed. Peripheral pins keep
            // the old shape — they are consumed by an `init_*` call.
            let binding = binding_of(pin, meta);
            let (prefix, open, close) = match pin.selected_function {
                // RTIC: the pin is moved into a `Local`, so it must be owned.
                _ if binding_style == Binding::Owned => ("", "", ""),
                PinFunction::GpioOutput if !gpio_native => {
                    ("", "pins::configs::io::DigitalOut(", ")")
                }
                PinFunction::GpioInput if !gpio_native => {
                    ("", "pins::configs::io::DigitalIn(", ")")
                }
                PinFunction::GpioOutput | PinFunction::GpioInput => ("", "", ""),
                ref f if needs_mut_ref(f) => ("&mut ", "", ""),
                _ => ("", "", ""),
            };
            // A freed JTAG pin is no longer a field of the port: `disable_jtag`
            // moved it out and handed it back as a plain binding.
            let src = if free_jtag && JTAG_PINS.contains(&pin.name.as_str()) {
                meta.var.clone()
            } else {
                format!("{}.{}", meta.port_var, meta.var)
            };
            format!(
                "    let {mut_}{binding} = {prefix}{open}{src}.{expr}{close}; // {comment}",
                mut_ = if needs_mut_binding(pin, gpio_native, binding_style, &binding, custom_inits)
                {
                    "mut "
                } else {
                    ""
                },
            )
        };
        port_groups.entry(meta.port).or_default().push(line);
    }

    let mut pin_section = String::new();
    for (port, lines) in &port_groups {
        pin_section.push_str(&format!("    // ── Port {port} ──\n"));
        for l in lines {
            pin_section.push_str(l);
            pin_section.push('\n');
        }
        pin_section.push('\n');
    }

    // Peripheral helper functions (init_usartN, init_spiN, init_i2cN) are NOT
    // emitted here: USART/SPI/I2C init lives in `src/pins/configs/` and the ADC
    // is constructed inline below (one plain `Adc::adc1` line — no helper fn).

    // ── Peripheral init calls (inside fn main) ───────────────────────────────
    let mut fn_calls = String::new();
    let mut any_call = false;

    macro_rules! header {
        () => {
            if !any_call {
                fn_calls.push_str("    // ── Peripheral initialisation ──\n");
                any_call = true;
            }
        };
    }

    for n in 1u8..=3 {
        let tx = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::UsartTx(n));
        let rx = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::UsartRx(n));
        if tx.is_none() && rx.is_none() {
            continue;
        }
        header!();
        let tx_v = tx
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_tx{n}"));
        let rx_v = rx
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_rx{n}"));
        let sfx = usart
            .get(&n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        // The binding shape follows the config's return type (see `api_style`):
        //  · Native  → the split `(Tx, Rx)` handles     → `let (mut _txN, mut _rxN)`
        //  · Portable → one `embedded_io::{Read,Write}`  → `let mut _serialN`
        let native = matches!(usart.get(&n).map(|c| c.api_style), Some(ApiStyle::Native));
        let binding = if native {
            format!("let (mut _tx{n}{sfx}, mut _rx{n}{sfx})")
        } else {
            format!("let mut _serial{n}{sfx}")
        };
        fn_calls.push_str(&format!(
            "    {binding} = \
             pins::configs::usart{n}::init(dp.USART{n}, ({tx_v}, {rx_v}), &mut afio, &clocks);\n"
        ));
    }

    for n in 1u8..=2 {
        let sck = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::SpiSck(n));
        let miso = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::SpiMiso(n));
        let mosi = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::SpiMosi(n));
        if sck.is_none() && mosi.is_none() {
            continue;
        }
        header!();
        // A signal the user left unwired gets the HAL's own placeholder — the
        // same type `SpiPins` in the config module names for it, and a value
        // that exists (the old `_miso{n}` was a binding nothing ever declared).
        let sck_v = sck
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| SPI_NO_SCK.to_string());
        let miso_v = miso
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| SPI_NO_MISO.to_string());
        let mosi_v = mosi
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| SPI_NO_MOSI.to_string());
        let sfx = spi
            .get(&n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    let _spi{n}{sfx} = \
             pins::configs::spi{n}::init(dp.SPI{n}, ({sck_v}, {miso_v}, {mosi_v}), &mut afio, &clocks);\n"
        ));
    }

    for n in 1u8..=2 {
        let scl = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::I2cScl(n));
        let sda = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::I2cSda(n));
        if scl.is_none() || sda.is_none() {
            continue;
        }
        header!();
        let scl_v = {
            let (p, m) = scl.unwrap();
            binding_of(p, m)
        };
        let sda_v = {
            let (p, m) = sda.unwrap();
            binding_of(p, m)
        };
        let sfx = i2c
            .get(&n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    let _i2c{n}{sfx} = \
             pins::configs::i2c{n}::init(dp.I2C{n}, ({scl_v}, {sda_v}), &mut afio, &clocks);\n"
        ));
    }

    if has_adc {
        header!();
        // Plain one-liner — `Adc::adc1` takes `Clocks` BY VALUE (Clocks is Copy).
        fn_calls.push_str("    let mut _adc1 = adc::Adc::adc1(dp.ADC1, clocks);\n");
        for (p, meta) in configured
            .iter()
            .filter(|(p, _)| matches!(p.selected_function, PinFunction::AdcChannel { .. }))
        {
            fn_calls.push_str(&format!(
                "    // let val: u16 = _adc1.read(&mut {}).unwrap();\n",
                binding_of(p, meta)
            ));
        }
    }

    if has_timer {
        header!();
        fn_calls.push_str("    // ── Timers / PWM ──\n");
        fn_calls.push_str("    // let pwm = Timer::tim2(dp.TIM2, &clocks)\n");
        fn_calls.push_str(
            "    //     .pwm_hz::<Tim2NoRemap, _, _>((pa0, pa1), &mut afio.mapr, 1.kHz());\n",
        );
    }

    let can_rx = configured
        .iter()
        .find(|(p, _)| p.selected_function == PinFunction::CanRx);
    let can_tx_pin = configured
        .iter()
        .find(|(p, _)| p.selected_function == PinFunction::CanTx);
    if can_rx.is_some() || can_tx_pin.is_some() {
        header!();
        let rx_v = can_rx
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or("_can_rx".into());
        let tx_v = can_tx_pin
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or("_can_tx".into());
        let sfx = can
            .get(&1)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        // `assign_pins` (and bxcan) expect the pins as `(TX, RX)`.
        fn_calls.push_str(&format!(
            "    let mut _can{sfx} = \
             pins::configs::can1::init(dp.CAN1, ({tx_v}, {rx_v}), &mut afio);\n"
        ));
    }

    // ── USB (CDC ACM serial) — full init in main's scope (option A) ───────────
    // USB needs `usb_dev`/`serial` to live where the user's loop polls them, and
    // its bus allocator borrows them, so it can't go in a `pins::configs` init().
    // Pins PA11(D-)/PA12(D+) are emitted as comments (not generic bindings), so
    // this block owns their configuration.
    if has_usb {
        header!();
        let cfg = usb.get(&1);
        let vid = cfg.map(|c| c.vid).unwrap_or(0x16c0);
        let pid = cfg.map(|c| c.pid).unwrap_or(0x27dd);
        let product = cfg.map(|c| c.product.as_str()).unwrap_or("Serial port");
        let sfx = cfg
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    // ── USB (CDC ACM serial) ──\n\
             // Needs the `usb-device` + `usbd-serial` crates and the HAL `stm32-usbd`\n\
             // feature (auto-added to Cargo.toml). Poll in your loop:\n\
             //     if usb_dev{sfx}.poll(&mut [&mut serial{sfx}]) {{ /* read/write serial */ }}\n\
             // Pull D+ low briefly so the host re-enumerates after a reset.\n\
             let mut usb_dp = gpioa.pa12.into_push_pull_output(&mut gpioa.crh);\n\
             usb_dp.set_low();\n\
             cortex_m::asm::delay(clocks.sysclk().raw() / 100);\n\
             let usb_periph = Peripheral {{\n\
                 usb: dp.USB,\n\
                 pin_dm: gpioa.pa11,\n\
                 pin_dp: usb_dp.into_floating_input(&mut gpioa.crh),\n\
             }};\n\
             let usb_bus = UsbBus::new(usb_periph);\n\
             let mut serial{sfx} = SerialPort::new(&usb_bus);\n\
             let mut usb_dev{sfx} = UsbDeviceBuilder::new(&usb_bus, UsbVidPid(0x{vid:04x}, 0x{pid:04x}))\n\
                 .product(\"{product}\")\n\
                 .device_class(USB_CLASS_CDC)\n\
                 .build();\n"
        ));
    }

    if any_call {
        fn_calls.push('\n');
    }

    // ── Custom modules ───────────────────────────────────────────────────────
    // Last, so every pin binding and peripheral init they consume already
    // exists above.
    if !custom_inits.is_empty() {
        fn_calls.push_str("    // ── Custom modules ──\n");
        fn_calls.push_str(custom_inits);
        fn_calls.push('\n');
    }

    // ── Assemble port splits ─────────────────────────────────────────────────
    let mut port_splits = ports_used
        .iter()
        .map(|p| {
            let lc = p.to_ascii_lowercase();
            let mut_ = if ports_written.contains(p) {
                "mut "
            } else {
                ""
            };
            format!("    let {mut_}gpio{lc} = dp.GPIO{p}.split();")
        })
        .collect::<Vec<_>>()
        .join("\n");
    if free_jtag {
        port_splits.push_str(&jtag_release_line(&configured));
    }

    let afio_line = if needs_afio {
        "let mut afio = dp.AFIO.constrain();\n"
    } else {
        ""
    };

    // ── Clock setup chain (from the Clock tab config) ────────────────────────
    let clock_chain = clock_setup_chain(clock);

    // Peripheral config constants now live in the per-peripheral modules under
    // `src/pins/configs/` (e.g. `pins::configs::usart1`), seeded from the wired
    // Virtual Module — no longer emitted in main.rs.

    Some(GenParts {
        use_block,
        extra_uses,
        afio_line,
        clock_chain,
        port_splits,
        pin_section,
        fn_calls,
    })
}

/// The classic bare-metal `main.rs` GEN block: `#[entry] fn main() -> !` with
/// the whole init inlined.
///
/// Byte-for-byte what it always produced — the parts moved out, the arrangement
/// did not (guarded by `blocking_output_is_unchanged`).
#[allow(clippy::too_many_arguments)]
pub fn make_generated_section(
    mcu_name: &str,
    all_pins: &[&Pin],
    clock: &ClockConfig,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    can: &BTreeMap<u8, CanModuleConfig>,
    usb: &BTreeMap<u8, UsbModuleConfig>,
    gpio_native: bool,
    custom_inits: &str,
) -> String {
    let Some(parts) = gen_parts(
        Binding::MutRef,
        all_pins,
        clock,
        usart,
        spi,
        i2c,
        can,
        usb,
        gpio_native,
        custom_inits,
    ) else {
        return make_default_gen_section(mcu_name, clock);
    };
    let GenParts {
        use_block,
        extra_uses,
        afio_line,
        clock_chain,
        port_splits,
        pin_section,
        fn_calls,
    } = parts;
    // Nothing is appended after `fn main` any more: USART/SPI/I2C init live in
    // `src/pins/configs/` and the ADC is a single line inside the GEN block.
    format!(
        "{GEN_BEGIN}\n\
         use stm32f1xx_hal::{{\n\
         {use_block}\n\
         }};\n\
         {extra_uses}\
         \n\
         #[entry]\n\
         fn main() -> ! {{\n\
             let dp = pac::Peripherals::take().unwrap();\n\n\
             let mut flash = dp.FLASH.constrain();\n\
             let rcc = dp.RCC.constrain();\n\
         {afio_line}\
             let clocks = {clock_chain};\n\n\
         {port_splits}\n\n\
         {pin_section}\
         {fn_calls}\
         {GEN_END}\n"
    )
}

// ── Default generated section (no pins configured yet) ────────────────────────

fn make_default_gen_section(mcu_name: &str, clock: &ClockConfig) -> String {
    let clock_chain = clock_setup_chain(clock);
    format!(
        "{GEN_BEGIN}\n\
         // MCU: {mcu_name}\n\
         use stm32f1xx_hal::{{pac, prelude::*}};\n\n\
         #[entry]\n\
         fn main() -> ! {{\n\
             let dp = pac::Peripherals::take().unwrap();\n\n\
             let mut flash = dp.FLASH.constrain();\n\
             let rcc = dp.RCC.constrain();\n\
             let clocks = {clock_chain};\n\n\
             // Select pins in the MCU Configurator to generate code here.\n\
         {GEN_END}\n"
    )
}

// ── Per-peripheral config files (src/pins/configs/) ───────────────────────────

/// The body of each `src/pins/configs/<periph>.rs` init module: config
/// constants (seeded from the wired Virtual Module) + a `use` block + a config
/// helper + `pub fn init`. Returns `(file_name, generated_body)` per configured
/// USART/SPI/I2C. `project_tree::sync_config_files` wraps the body in GENERATED
/// markers and splices it (so user code outside the markers survives). main.rs
/// calls `pins::configs::<periph>::init(...)`.
pub fn config_files(
    all_pins: &[&Pin],
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    can: &BTreeMap<u8, CanModuleConfig>,
    clock: &ClockConfig,
    gpio_native: bool,
) -> Vec<(String, String)> {
    let funcs: Vec<&PinFunction> = all_pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .map(|p| &p.selected_function)
        .collect();
    let has = |want: PinFunction| funcs.iter().any(|f| **f == want);

    let mut out: Vec<(String, String)> = Vec::new();
    for n in 1u8..=3 {
        if has(PinFunction::UsartTx(n)) || has(PinFunction::UsartRx(n)) {
            out.push((format!("usart{n}.rs"), usart_config_file(n, usart.get(&n))));
        }
    }
    for n in 1u8..=2 {
        if has(PinFunction::SpiSck(n)) || has(PinFunction::SpiMosi(n)) {
            out.push((
                format!("spi{n}.rs"),
                spi_config_file(n, spi.get(&n), &spi_pin_tys(n, all_pins)),
            ));
        }
    }
    for n in 1u8..=2 {
        if has(PinFunction::I2cScl(n)) && has(PinFunction::I2cSda(n)) {
            out.push((
                format!("i2c{n}.rs"),
                i2c_config_file(n, i2c.get(&n), &i2c_pin_tys(n, all_pins)),
            ));
        }
    }
    // CAN — single instance on STM32F1; the bit-timing register depends on the
    // APB1 (PCLK1) clock, so the clock config is read here.
    if has(PinFunction::CanRx) || has(PinFunction::CanTx) {
        out.push((
            "can1.rs".to_string(),
            can_config_file(can.get(&1), pclk1_of(clock)),
        ));
    }
    // The GPIO/Delay → embedded-hal 1.0 bridge module — ONLY on the Portable
    // GPIO api (`!gpio_native`), when any GPIO in/out pin is configured (the pin
    // bindings wrap it). On the Native GPIO api the pins bind raw, so io.rs would
    // be dead code + pull an unused `embedded-hal` — skip it.
    if !gpio_native && (has(PinFunction::GpioOutput) || has(PinFunction::GpioInput)) {
        out.push(("io.rs".to_string(), GPIO_IO_FILE.to_string()));
    }
    out
}

/// The pins the JTAG port holds at reset. `disable_jtag` frees exactly these
/// three, together — the order is the one its signature takes.
const JTAG_PINS: [&str; 3] = ["PA15", "PB3", "PB4"];

/// The `let (…) = afio.mapr.disable_jtag(…)` line, with the pins the project
/// does not use underscored so they don't read as forgotten bindings.
fn jtag_release_line(configured: &[(&Pin, PinMeta)]) -> String {
    let names = JTAG_PINS
        .iter()
        .map(|n| {
            let var = n.to_ascii_lowercase();
            if configured.iter().any(|(p, _)| p.name == *n) {
                var
            } else {
                format!("_{var}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "\n    // PA15/PB3/PB4 are the JTAG port at reset and have no usable pin\n\
         \x20   // mode until it is given up. SWD keeps working; JTAG debugging does not.\n\
         \x20   let ({names}) = afio.mapr.disable_jtag(gpioa.pa15, gpiob.pb3, gpiob.pb4);"
    )
}

// ── Concrete pin types for the bus config modules ─────────────────────────────
//
// SPI and I2C keep their pins IN the handle type (`Spi<SPI1, REMAP, PINS, u8>`,
// `BlockingI2c<I2C1, PINS>`), so a config module cannot name what `init` returns
// without naming the pins. USART could get away with `Handle` alone — its
// `split()` erases them — these two cannot, and a named handle is what an RTIC
// `Local` resource (or any struct field) needs.
//
// The aliases therefore live INSIDE each file's GENERATED block: re-wiring a
// peripheral must rewrite them, and only that block is re-spliced on save.

/// The HAL placeholders for an unwired SPI signal. main.rs passes the VALUE (by
/// full path — its `use` block does not import `spi`); the config module's
/// `SpiPins` names the TYPE through the `hal_spi` alias it imports itself.
const SPI_NO_SCK: &str = "stm32f1xx_hal::spi::NoSck";
const SPI_NO_MISO: &str = "stm32f1xx_hal::spi::NoMiso";
const SPI_NO_MOSI: &str = "stm32f1xx_hal::spi::NoMosi";

/// The pin carrying `want`, or `None` when the user has not wired that signal.
fn wired<'a>(all_pins: &[&'a Pin], want: PinFunction) -> Option<&'a Pin> {
    all_pins
        .iter()
        .copied()
        .find(|p| !p.reserved && p.selected_function == want)
}

/// The `stm32f1xx-hal` type a configured bus pin ends up with — the value
/// [`into_expr`] builds, named. `hal_gpio` is the alias the GENERATED block of
/// each config file imports for itself, so the type keeps resolving whatever the
/// user does to the editable `use` block below it.
fn hal_pin_ty(pin: &Pin) -> Option<String> {
    let mode = match pin.selected_function {
        // `into_alternate_push_pull` → `Alternate<PushPull>`, and `PushPull` is
        // the alias' default parameter.
        PinFunction::SpiSck(_) | PinFunction::SpiMosi(_) => "hal_gpio::Alternate",
        PinFunction::SpiMiso(_) => "hal_gpio::Input<hal_gpio::Floating>",
        PinFunction::I2cScl(_) | PinFunction::I2cSda(_) => {
            "hal_gpio::Alternate<hal_gpio::OpenDrain>"
        }
        _ => return None,
    };
    let m = parse_pin(&pin.name)?;
    Some(format!("hal_gpio::P{}{}<{mode}>", m.port, m.pin_num))
}

/// One line per element of a generated tuple type, indented for the alias.
fn tuple_body(items: &[String]) -> String {
    items
        .iter()
        .map(|t| format!("\n    {t},"))
        .collect::<String>()
        + "\n"
}

/// `(SpiPins tuple body, SpiRemap type)` for SPI`n`, as its config module
/// spells them.
fn spi_pin_tys(n: u8, all_pins: &[&Pin]) -> (String, String) {
    let ty = |f: PinFunction, filler: &str| {
        wired(all_pins, f)
            .and_then(hal_pin_ty)
            // Same placeholder main.rs passes for the missing signal, with the
            // full path swapped for the file's own `hal_spi` alias.
            .unwrap_or_else(|| filler.replace("stm32f1xx_hal::spi::", "hal_spi::"))
    };
    let pins = tuple_body(&[
        ty(PinFunction::SpiSck(n), SPI_NO_SCK),
        ty(PinFunction::SpiMiso(n), SPI_NO_MISO),
        ty(PinFunction::SpiMosi(n), SPI_NO_MOSI),
    ]);
    (pins, spi_remap_ty(n, all_pins))
}

/// The remap type-state for SPI`n`. Only SPI1 has an alternate pin set on this
/// family (PB3/PB4/PB5 instead of PA5/PA6/PA7) and the HAL takes the remap
/// REGISTER BIT from this type, so naming the wrong one drives the wrong pads.
/// SPI2's own pins are on port B as well — hence the instance check.
///
/// The clock pin decides, falling back to MOSI then MISO: the HAL's remap is
/// all-or-nothing, so a wiring that mixes the two sets has no right answer here
/// — it is rejected by the `Pins` impls, at the pin that does not belong.
fn spi_remap_ty(n: u8, all_pins: &[&Pin]) -> String {
    let remapped = n == 1
        && [
            PinFunction::SpiSck(n),
            PinFunction::SpiMosi(n),
            PinFunction::SpiMiso(n),
        ]
        .into_iter()
        .find_map(|f| wired(all_pins, f).and_then(|p| parse_pin(&p.name)))
        .is_some_and(|m| m.port == 'B');
    if remapped {
        "hal_spi::Spi1Remap".to_string()
    } else {
        format!("hal_spi::Spi{n}NoRemap")
    }
}

/// The `I2cPins` tuple body for I2C`n` — (SCL, SDA), the order the HAL's `Pins`
/// impls and main.rs's call both use. Both signals are required for the file to
/// be generated at all, so there is no placeholder case.
fn i2c_pin_tys(n: u8, all_pins: &[&Pin]) -> String {
    let ty = |f: PinFunction| {
        wired(all_pins, f)
            .and_then(hal_pin_ty)
            .unwrap_or_else(|| "()".to_string())
    };
    tuple_body(&[ty(PinFunction::I2cScl(n)), ty(PinFunction::I2cSda(n))])
}

/// `src/pins/configs/io.rs` — bridges the HAL's embedded-hal 0.2 GPIO + blocking
/// delay to the STANDARD `embedded-hal` 1.0 traits (`OutputPin`/`InputPin`/
/// `DelayNs`), so driver/app code stays portable across HALs. Real-compile
/// verified on thumbv7m. The leading GENERATED marker block is required by
/// `sync_config_files` (there is no per-chip config here — it stays a comment).
const GPIO_IO_FILE: &str = r#"// <<< GENERATED>>>
// Portable GPIO/Delay bridges — no per-chip config; this marker just frames the
// regenerated region. Edit the bridges below freely.
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// Wrap a HAL pin/delay to make it a STANDARD `embedded-hal` 1.0 value, so your
// driver/app code is portable across chips/HALs:
//
//     fn app<P: embedded_hal::digital::OutputPin>(led: &mut P) { /* … */ }
#[derive(Debug)]
pub struct IoError;
impl embedded_hal::digital::Error for IoError {
    fn kind(&self) -> embedded_hal::digital::ErrorKind {
        embedded_hal::digital::ErrorKind::Other
    }
}

/// A HAL output pin (embedded-hal 0.2) as an `embedded-hal` 1.0 pin.
pub struct DigitalOut<P>(pub P);
impl<P> embedded_hal::digital::ErrorType for DigitalOut<P> {
    type Error = IoError;
}
impl<P: embedded_hal_0_2::digital::v2::OutputPin> embedded_hal::digital::OutputPin for DigitalOut<P> {
    fn set_low(&mut self) -> Result<(), Self::Error> { self.0.set_low().map_err(|_| IoError) }
    fn set_high(&mut self) -> Result<(), Self::Error> { self.0.set_high().map_err(|_| IoError) }
}
impl<P> embedded_hal::digital::StatefulOutputPin for DigitalOut<P>
where
    P: embedded_hal_0_2::digital::v2::OutputPin + embedded_hal_0_2::digital::v2::StatefulOutputPin,
{
    fn is_set_high(&mut self) -> Result<bool, Self::Error> { self.0.is_set_high().map_err(|_| IoError) }
    fn is_set_low(&mut self) -> Result<bool, Self::Error> { self.0.is_set_low().map_err(|_| IoError) }
}

/// A HAL input pin (embedded-hal 0.2) as an `embedded-hal` 1.0 pin.
pub struct DigitalIn<P>(pub P);
impl<P> embedded_hal::digital::ErrorType for DigitalIn<P> {
    type Error = IoError;
}
impl<P: embedded_hal_0_2::digital::v2::InputPin> embedded_hal::digital::InputPin for DigitalIn<P> {
    fn is_high(&mut self) -> Result<bool, Self::Error> { self.0.is_high().map_err(|_| IoError) }
    fn is_low(&mut self) -> Result<bool, Self::Error> { self.0.is_low().map_err(|_| IoError) }
}

/// A HAL blocking delay (embedded-hal 0.2) as an `embedded-hal` 1.0 `DelayNs`.
/// Build one from the SysTick: `let mut d = pins::configs::io::Delay(cp.SYST.delay(&clocks));`
#[allow(dead_code)]
pub struct Delay<D>(pub D);
impl<D: embedded_hal_0_2::blocking::delay::DelayUs<u32>> embedded_hal::delay::DelayNs for Delay<D> {
    fn delay_ns(&mut self, ns: u32) { self.0.delay_us(ns.div_ceil(1000)); }
    fn delay_us(&mut self, us: u32) { self.0.delay_us(us); }
}
"#;

/// APB1 (PCLK1) frequency in Hz from the clock config — needed for the CAN bit
/// timing. Mirrors [`clock_setup_chain`]'s graph→typed→frequencies path.
fn pclk1_of(clock: &ClockConfig) -> u32 {
    let c: Stm32f1Clock = match clock {
        ClockConfig::Graph(gc) => {
            crate::panels::mcu_module::clock::graph::graph_to_stm32f1(&gc.for_codegen())
        }
        ClockConfig::None => Stm32f1Clock::default(),
    };
    frequencies(&c).pclk1
}

/// STM32 `CAN_BTR` register value for `bitrate` at `pclk1`, aiming for a ~87.5%
/// sample point. Searches total time-quanta 8..=20 for an exact prescaler.
/// Returns 0 when none fits (so the user notices and fixes the bit timing).
fn can_btr(bitrate: u32, pclk1: u32) -> u32 {
    if bitrate == 0 || pclk1 == 0 {
        return 0;
    }
    for ntq in (8u32..=20).rev() {
        let denom = bitrate * ntq;
        if pclk1 % denom != 0 {
            continue;
        }
        let brp = pclk1 / denom;
        if !(1..=1024).contains(&brp) {
            continue;
        }
        // total = 1 (sync) + ts1 + ts2 = ntq; sample point ≈ ts1/ntq.
        let ts1 = ((ntq * 7) / 8).clamp(2, 16);
        let ts2 = (ntq - 1).saturating_sub(ts1);
        if !(1..=8).contains(&ts2) {
            continue;
        }
        let sjw = 1u32;
        return ((sjw - 1) << 24) | ((ts2 - 1) << 20) | ((ts1 - 1) << 16) | (brp - 1);
    }
    0
}

const CAN_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const BITRATE: u32 = {BITRATE}; // bits/s
// CAN_BTR register value, computed from BITRATE and the APB1 clock ({PCLK1} Hz).
const BTR: u32 = {BTR};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
// CAN on STM32F1 needs the `bxcan` + `nb` crates (auto-added to Cargo.toml when a
// CAN module is present). Verify the bit timing / filters for your bus.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    can::Can,
};

/// The concrete type [`init`] hands back.
///
/// CAN already returned a named type; the alias exists so every config module
/// spells its handle the same way, which is what the RTIC generator looks for.
pub type Handle = bxcan::Can<Can<pac::CAN1>>;

pub fn init<PINS>(
    can: pac::CAN1,
    pins: PINS,
    afio: &mut afio::Parts,
) -> Handle
where
    PINS: stm32f1xx_hal::can::Pins<Instance = pac::CAN1>,
{
    let mut hal_can = Can::new(can);
    hal_can.assign_pins(pins, &mut afio.mapr);

    let mut bx = bxcan::Can::builder(hal_can)
        .set_bit_timing(BTR)
        .leave_disabled();

    // Accept every frame by default — tighten the filter for your application.
    bx.modify_filters().enable_bank(0, bxcan::filter::Mask32::accept_all());

    nb::block!(bx.enable_non_blocking()).ok();
    bx
}

// ── Using CAN1 ──
// In main.rs, after the init above:
//
//     use bxcan::{Frame, StandardId};
//
//     // Send
//     let id = StandardId::new(0x123).unwrap();
//     let frame = Frame::new_data(id, [1u8, 2, 3, 4]);
//     nb::block!(_can1.transmit(&frame)).ok();
//
//     // Receive (nb: Err(WouldBlock) while the mailboxes are empty)
//     if let Ok(rx) = {HANDLE}.receive() {
//         if let Some(data) = rx.data() {
//             // data[..] holds the payload
//         }
//     }

"#;

fn can_config_file(cfg: Option<&CanModuleConfig>, pclk1: u32) -> String {
    let bitrate = cfg.map(|c| c.bitrate).unwrap_or(500_000);
    let btr = can_btr(bitrate, pclk1);
    let sfx = cfg
        .map(|c| module_label_sfx(&c.custom_label))
        .unwrap_or_default();
    CAN_TMPL
        .replace("{HANDLE}", &format!("_can{sfx}"))
        .replace("{BITRATE}", &bitrate.to_string())
        .replace("{PCLK1}", &pclk1.to_string())
        .replace("{BTR}", &format!("0x{btr:08X}"))
}

const USART_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const BAUDRATE: u32 = {BAUD};
const DATA_BITS: u8 = {DATA}; // 8, 9
const PARITY: char = '{PARITY}'; // 'N' None, 'O' Odd, 'E' Even
const STOP_BITS: u8 = {STOP}; // 1, 2
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
//
// `init` returns a value implementing the STANDARD `embedded-io` traits
// (`Read` + `Write`), so your application code stays portable across chips/HALs:
//
//     fn app<S: embedded_io::Read + embedded_io::Write>(serial: &mut S) { /* … */ }
//
// stm32f1xx-hal 0.10 still speaks embedded-hal 0.2 (`nb`), so `SerialIo` below
// bridges its split `Tx`/`Rx` to `embedded-io`.
use stm32f1xx_hal::{
    pac,
    prelude::*,       // brings the embedded-hal 0.2 `nb` serial methods into scope
    afio,
    rcc::Clocks,
    serial::{self, Config, Serial, StopBits},
};

fn get_config() -> serial::Config {
    let mut config = Config::default().baudrate(BAUDRATE.bps());

    if DATA_BITS == 8 {
        config = config.wordlength_8bits();
    } else if DATA_BITS == 9 {
        config = config.wordlength_9bits();
    }

    if PARITY == 'N' {
        config = config.parity_none();
    } else if PARITY == 'O' {
        config = config.parity_odd();
    } else if PARITY == 'E' {
        config = config.parity_even();
    }

    if STOP_BITS == 1 {
        config = config.stopbits(StopBits::STOP1);
    } else if STOP_BITS == 2 {
        config = config.stopbits(StopBits::STOP2);
    }

    config
}

/// Bridges the HAL's `nb` serial (embedded-hal 0.2) to blocking `embedded-io`.
pub struct SerialIo<TX, RX>(pub TX, pub RX);

#[derive(Debug)]
pub struct IoError;
// embedded-io 0.7 requires `Error: core::error::Error`, which in turn wants
// Display. Two tiny impls, and the bridge works on 0.6 and 0.7 alike.
impl core::fmt::Display for IoError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("serial I/O error")
    }
}
impl core::error::Error for IoError {}
impl embedded_io::Error for IoError {
    fn kind(&self) -> embedded_io::ErrorKind {
        embedded_io::ErrorKind::Other
    }
}
impl<TX, RX> embedded_io::ErrorType for SerialIo<TX, RX> {
    type Error = IoError;
}
impl<TX: embedded_hal_0_2::serial::Write<u8>, RX> embedded_io::Write for SerialIo<TX, RX> {
    fn write(&mut self, buf: &[u8]) -> Result<usize, Self::Error> {
        for &b in buf {
            nb::block!(self.0.write(b)).map_err(|_| IoError)?;
        }
        Ok(buf.len())
    }
    fn flush(&mut self) -> Result<(), Self::Error> {
        nb::block!(self.0.flush()).map_err(|_| IoError)
    }
}
impl<TX, RX: embedded_hal_0_2::serial::Read<u8>> embedded_io::Read for SerialIo<TX, RX> {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize, Self::Error> {
        if buf.is_empty() {
            return Ok(0);
        }
        // `embedded-io::Read` blocks until at least one byte is available.
        buf[0] = nb::block!(self.1.read()).map_err(|_| IoError)?;
        Ok(1)
    }
}

/// The concrete type [`init`] hands back.
///
/// A NAMED type, not `impl Trait`: a struct field has to name its type, and on
/// the RTIC runtime this handle becomes a `Local` resource. Returning `impl
/// Trait` made the peripheral unusable there — `#[init]` returned and dropped
/// it. Still `embedded-io` Read + Write for every caller.
pub type Handle = SerialIo<serial::Tx<pac::USART{N}>, serial::Rx<pac::USART{N}>>;

/// Initialise USART{N} and expose it as an `embedded-io` Read + Write value.
pub fn init(
    usart: pac::USART{N},
    pins: impl serial::Pins<pac::USART{N}>,
    afio: &mut afio::Parts,
    clocks: &Clocks,
) -> Handle {
    let (tx, rx) = Serial::new(usart, pins, &mut afio.mapr, get_config(), clocks).split();
    SerialIo(tx, rx)
}

// ── Using USART{N} ──
// Portable init — the handle is an `embedded-io` Read + Write, so this code
// works unchanged on any HAL. In main.rs, after the init above:
//
//     use embedded_io::{Read, Write};
//
//     // Send
//     {HANDLE}.write_all(b"hello\r\n").ok();
//     {HANDLE}.flush().ok();
//
//     // Receive exactly N bytes (blocks until they arrive)
//     let mut buf = [0u8; 4];
//     {HANDLE}.read_exact(&mut buf).ok();
//
//     // Or take whatever is available right now
//     let n = {HANDLE}.read(&mut buf).unwrap_or(0);

"#;

fn usart_config_file(n: u8, cfg: Option<&UsartModuleConfig>) -> String {
    let baud = cfg.map(|c| c.baud_rate).unwrap_or(115_200);
    let data = cfg.map(|c| c.data_bits).unwrap_or(8);
    let parity = match cfg.map(|c| c.parity) {
        Some(Parity::Odd) => 'O',
        Some(Parity::Even) => 'E',
        _ => 'N',
    };
    let stop = match cfg.map(|c| c.stop_bits) {
        Some(StopBits::Two) => 2,
        _ => 1,
    };
    let tmpl = match cfg.map(|c| c.api_style).unwrap_or_default() {
        ApiStyle::Portable => USART_TMPL,
        ApiStyle::Native => USART_TMPL_NATIVE,
    };
    // The handle the example names is the one `main.rs` actually binds —
    // module label included (`_serial1_mw_radar`), or the split pair on Native.
    let sfx = cfg
        .map(|c| module_label_sfx(&c.custom_label))
        .unwrap_or_default();
    tmpl.replace("{HANDLE}", &format!("_serial{n}{sfx}"))
        .replace("{TX}", &format!("_tx{n}{sfx}"))
        .replace("{RX}", &format!("_rx{n}{sfx}"))
        .replace("{N}", &n.to_string())
        .replace("{BAUD}", &baud.to_string())
        .replace("{DATA}", &data.to_string())
        .replace("{PARITY}", &parity.to_string())
        .replace("{STOP}", &stop.to_string())
}

/// Native `stm32f1xx-hal` USART init (no embedded-io bridge). Returns the split
/// `(Tx, Rx)` halves — the idiomatic stm32f1xx-hal handles (TX for `writeln!`, RX
/// for reading). Selected via `ApiStyle`; the `main.rs` binding destructures the
/// tuple (`let (mut _txN, mut _rxN) = …`), unlike the single-value Portable form.
const USART_TMPL_NATIVE: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const BAUDRATE: u32 = {BAUD};
const DATA_BITS: u8 = {DATA}; // 8, 9
const PARITY: char = '{PARITY}'; // 'N' None, 'O' Odd, 'E' Even
const STOP_BITS: u8 = {STOP}; // 1, 2
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
// NATIVE stm32f1xx-hal API (chosen in the Virtual Module). `init` returns the
// split `(Tx, Rx)` handles — use `Tx` with `writeln!` / `Rx` with `.read()`.
// Switch to the portable `embedded-io` API in the Virtual Module.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    serial::{self, Config, Serial, StopBits},
};

fn get_config() -> serial::Config {
    let mut config = Config::default().baudrate(BAUDRATE.bps());
    if DATA_BITS == 8 {
        config = config.wordlength_8bits();
    } else if DATA_BITS == 9 {
        config = config.wordlength_9bits();
    }
    if PARITY == 'N' {
        config = config.parity_none();
    } else if PARITY == 'O' {
        config = config.parity_odd();
    } else if PARITY == 'E' {
        config = config.parity_even();
    }
    if STOP_BITS == 1 {
        config = config.stopbits(StopBits::STOP1);
    } else if STOP_BITS == 2 {
        config = config.stopbits(StopBits::STOP2);
    }
    config
}

pub fn init<PINS: serial::Pins<pac::USART{N}>>(
    usart: pac::USART{N},
    pins: PINS,
    afio: &mut afio::Parts,
    clocks: &Clocks,
) -> (serial::Tx<pac::USART{N}>, serial::Rx<pac::USART{N}>) {
    Serial::new(usart, pins, &mut afio.mapr, get_config(), clocks).split()
}

// ── Using USART{N} ──
// Native init — `init` returns the HAL's own split halves, which are `nb`
// (non-blocking) based. In main.rs, after the init above:
//
//     use nb::block;
//
//     // Send one byte at a time
//     for b in b"hello\r\n" {
//         block!({TX}.write(*b)).ok();
//     }
//     block!({TX}.flush()).ok();
//
//     // Receive one byte, blocking until it arrives
//     let byte = block!({RX}.read()).unwrap_or(0);
//
//     // Non-blocking poll: Err(nb::Error::WouldBlock) means "nothing yet"
//     match {RX}.read() {
//         Ok(b) => { /* got b */ }
//         Err(nb::Error::WouldBlock) => { /* try again later */ }
//         Err(_) => { /* framing / overrun error */ }
//     }

"#;

const SPI_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const SPI_MODE: u8 = {MODE}; // 0..=3 (CPOL/CPHA)
const CLOCK_KHZ: u32 = {KHZ};

// The wired pins, straight from the MCU Configurator's pin map. They live in
// this block because re-wiring the peripheral has to update them; the `use` is
// here too, so the aliases hold whatever you do to the `use` block below.
use stm32f1xx_hal::{gpio as hal_gpio, spi as hal_spi};

/// The pins SPI{N} is wired to, in HAL order: (SCK, MISO, MOSI). A signal you
/// left unwired is the HAL's `No…` placeholder.
///
/// `allow(dead_code)`: `init` below is yours to edit and may stop naming it.
#[allow(dead_code)]
pub type SpiPins = ({PINS});

/// Whether those are the peripheral's default pins or its remapped set — the
/// HAL takes the remap register bit from this type.
#[allow(dead_code)]
pub type SpiRemap = {REMAP};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    spi::{Mode, Phase, Polarity, Spi},
};

fn get_mode() -> Mode {
    match SPI_MODE {
        1 => Mode { polarity: Polarity::IdleLow, phase: Phase::CaptureOnSecondTransition },
        2 => Mode { polarity: Polarity::IdleHigh, phase: Phase::CaptureOnFirstTransition },
        3 => Mode { polarity: Polarity::IdleHigh, phase: Phase::CaptureOnSecondTransition },
        _ => Mode { polarity: Polarity::IdleLow, phase: Phase::CaptureOnFirstTransition },
    }
}

/// Bridges the HAL's blocking/nb SPI (embedded-hal 0.2) to the STANDARD
/// `embedded-hal` 1.0 `SpiBus`, so driver/app code stays portable across HALs:
///
///     fn app<S: embedded_hal::spi::SpiBus>(spi: &mut S) { /* … */ }
pub struct SpiBusIo<SPI>(pub SPI);

#[derive(Debug)]
pub struct IoError;
impl embedded_hal::spi::Error for IoError {
    fn kind(&self) -> embedded_hal::spi::ErrorKind {
        embedded_hal::spi::ErrorKind::Other
    }
}
impl<SPI> embedded_hal::spi::ErrorType for SpiBusIo<SPI> {
    type Error = IoError;
}
impl<SPI> embedded_hal::spi::SpiBus<u8> for SpiBusIo<SPI>
where
    SPI: embedded_hal_0_2::blocking::spi::Write<u8>
        + embedded_hal_0_2::blocking::spi::Transfer<u8>
        + embedded_hal_0_2::spi::FullDuplex<u8>,
{
    fn write(&mut self, words: &[u8]) -> Result<(), Self::Error> {
        embedded_hal_0_2::blocking::spi::Write::write(&mut self.0, words).map_err(|_| IoError)
    }
    fn read(&mut self, words: &mut [u8]) -> Result<(), Self::Error> {
        for w in words.iter_mut() {
            nb::block!(embedded_hal_0_2::spi::FullDuplex::send(&mut self.0, 0)).map_err(|_| IoError)?;
            *w = nb::block!(embedded_hal_0_2::spi::FullDuplex::read(&mut self.0)).map_err(|_| IoError)?;
        }
        Ok(())
    }
    fn transfer_in_place(&mut self, words: &mut [u8]) -> Result<(), Self::Error> {
        embedded_hal_0_2::blocking::spi::Transfer::transfer(&mut self.0, words)
            .map(|_| ())
            .map_err(|_| IoError)
    }
    fn transfer(&mut self, read: &mut [u8], write: &[u8]) -> Result<(), Self::Error> {
        // Clock max(read, write) bytes; pad the write with 0, ignore reads past `read`.
        for i in 0..read.len().max(write.len()) {
            let b = write.get(i).copied().unwrap_or(0);
            nb::block!(embedded_hal_0_2::spi::FullDuplex::send(&mut self.0, b)).map_err(|_| IoError)?;
            let r = nb::block!(embedded_hal_0_2::spi::FullDuplex::read(&mut self.0)).map_err(|_| IoError)?;
            if let Some(slot) = read.get_mut(i) {
                *slot = r;
            }
        }
        Ok(())
    }
    fn flush(&mut self) -> Result<(), Self::Error> {
        Ok(())
    }
}

/// The concrete type [`init`] hands back.
///
/// A NAMED type, not `impl Trait`: a struct field — an RTIC `Local` resource,
/// say — has to name what it holds, and an opaque type cannot be named. The pins
/// stay inside the HAL's `Spi<…>`, so `SpiPins`/`SpiRemap` from the GENERATED
/// block above are part of it; re-wiring SPI{N} updates this alias with them.
/// It is still an `embedded-hal` 1.0 `SpiBus` for every caller.
pub type Handle = SpiBusIo<Spi<pac::SPI{N}, SpiRemap, SpiPins, u8>>;

/// Initialise SPI{N} and expose it as an `embedded-hal` 1.0 `SpiBus`.
pub fn init(
    spi: pac::SPI{N},
    pins: SpiPins,
    {AFIO_PARAM}: &mut afio::Parts,
    clocks: &Clocks,
) -> Handle {
    let bus = Spi::spi{N}(spi, pins, {AFIO_ARG}get_mode(), CLOCK_KHZ.kHz(), *clocks);
    SpiBusIo(bus)
}

// ── Using SPI{N} ──
// Portable init — the handle is an `embedded-hal` 1.0 `SpiBus`. In main.rs,
// after the init above:
//
// NOTE: main.rs binds this handle as `let {HANDLE} = …` — add `mut`
// there before calling anything below (bus methods take `&mut self`).
//
//     use embedded_hal::spi::SpiBus;
//
//     // Write only
//     {HANDLE}.write(&[0x9F]).ok();
//
//     // Read only (clocks out zeros)
//     let mut rx = [0u8; 3];
//     {HANDLE}.read(&mut rx).ok();
//
//     // Full duplex, separate buffers
//     {HANDLE}.transfer(&mut rx, &[0x9F, 0x00, 0x00]).ok();
//
//     // Full duplex in place: `buf` is sent, then overwritten by the reply
//     let mut buf = [0x9F, 0x00, 0x00];
//     {HANDLE}.transfer_in_place(&mut buf).ok();
//     {HANDLE}.flush().ok();
//
//     // NSS/CS is a plain GPIO here — drive it low around a transaction.

"#;

fn spi_config_file(n: u8, cfg: Option<&SpiModuleConfig>, pin_tys: &(String, String)) -> String {
    let mode = cfg.map(|c| c.mode).unwrap_or(0);
    let khz = cfg.map(|c| c.clock_hz).unwrap_or(1_000_000) / 1_000;
    let tmpl = match cfg.map(|c| c.api_style).unwrap_or_default() {
        ApiStyle::Portable => SPI_TMPL,
        ApiStyle::Native => SPI_TMPL_NATIVE,
    };
    let (pins, remap) = pin_tys;
    // Only SPI1 can be remapped, so only `Spi::spi1` takes the AFIO register.
    let (afio_param, afio_arg) = afio_subst(n == 1);
    let sfx = cfg
        .map(|c| module_label_sfx(&c.custom_label))
        .unwrap_or_default();
    tmpl.replace("{HANDLE}", &format!("_spi{n}{sfx}"))
        .replace("{N}", &n.to_string())
        .replace("{MODE}", &mode.to_string())
        .replace("{KHZ}", &khz.to_string())
        .replace("{PINS}", pins)
        .replace("{REMAP}", remap)
        .replace("{AFIO_PARAM}", afio_param)
        .replace("{AFIO_ARG}", afio_arg)
}

/// `({AFIO_PARAM}, {AFIO_ARG})` for a config template.
///
/// In stm32f1xx-hal 0.10 only the FIRST instance of SPI and I2C takes the AFIO
/// remap register — `Spi::spi2` / `BlockingI2c::i2c2` have no `mapr` argument,
/// because those peripherals have no alternate pin set to select. main.rs passes
/// `&mut afio` to every instance all the same (one call shape for all of them),
/// so the parameter stays and is underscored where the HAL cannot use it.
fn afio_subst(takes_mapr: bool) -> (&'static str, &'static str) {
    if takes_mapr {
        ("afio", "&mut afio.mapr, ")
    } else {
        ("_afio", "")
    }
}

/// Native `stm32f1xx-hal` SPI init (no eh-1.0 bridge). Returns `Spi<…>`.
const SPI_TMPL_NATIVE: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const SPI_MODE: u8 = {MODE}; // 0..=3 (CPOL/CPHA)
const CLOCK_KHZ: u32 = {KHZ};

// The wired pins, straight from the MCU Configurator's pin map. They live in
// this block because re-wiring the peripheral has to update them; the `use` is
// here too, so the aliases hold whatever you do to the `use` block below.
use stm32f1xx_hal::{gpio as hal_gpio, spi as hal_spi};

/// The pins SPI{N} is wired to, in HAL order: (SCK, MISO, MOSI). A signal you
/// left unwired is the HAL's `No…` placeholder.
///
/// `allow(dead_code)`: `init` below is yours to edit and may stop naming it.
#[allow(dead_code)]
pub type SpiPins = ({PINS});

/// Whether those are the peripheral's default pins or its remapped set — the
/// HAL takes the remap register bit from this type.
#[allow(dead_code)]
pub type SpiRemap = {REMAP};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
// NATIVE stm32f1xx-hal API — returns `Spi<…>`. Switch to the portable
// `embedded-hal` 1.0 `SpiBus` API in the Virtual Module.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    spi::{Mode, Phase, Polarity, Spi},
};

fn get_mode() -> Mode {
    match SPI_MODE {
        1 => Mode { polarity: Polarity::IdleLow, phase: Phase::CaptureOnSecondTransition },
        2 => Mode { polarity: Polarity::IdleHigh, phase: Phase::CaptureOnFirstTransition },
        3 => Mode { polarity: Polarity::IdleHigh, phase: Phase::CaptureOnSecondTransition },
        _ => Mode { polarity: Polarity::IdleLow, phase: Phase::CaptureOnFirstTransition },
    }
}

/// The concrete type [`init`] hands back — the HAL's own `Spi`, with the pins
/// and the remap state it keeps in its type. Named so it can be a struct field
/// (an RTIC `Local` resource, say); the two aliases come from the GENERATED
/// block above, so re-wiring SPI{N} updates this one with them.
pub type Handle = Spi<pac::SPI{N}, SpiRemap, SpiPins, u8>;

pub fn init(
    spi: pac::SPI{N},
    pins: SpiPins,
    {AFIO_PARAM}: &mut afio::Parts,
    clocks: &Clocks,
) -> Handle {
    Spi::spi{N}(spi, pins, {AFIO_ARG}get_mode(), CLOCK_KHZ.kHz(), *clocks)
}

// ── Using SPI{N} ──
// Native init — the concrete `stm32f1xx-hal` Spi, whose traits are
// `embedded-hal` 0.2. In main.rs, after the init above:
//
// NOTE: the Native path needs the 0.2 traits, which the IDE only adds to
// Cargo.toml for PORTABLE modules. Add them yourself:
//   embedded-hal-0-2 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }
// — or switch this module's Init API to Portable, where the handle is an
// embedded-hal 1.0 bus and no extra dependency is needed.
//
// NOTE: main.rs binds this handle as `let {HANDLE} = …` — add `mut`
// there before calling anything below (bus methods take `&mut self`).
//
//     use embedded_hal_0_2::blocking::spi::{Transfer, Write};
//
//     // Write only
//     {HANDLE}.write(&[0x9F]).ok();
//
//     // Full duplex in place: the buffer is sent, then holds the reply
//     let mut buf = [0x9F, 0x00, 0x00];
//     {HANDLE}.transfer(&mut buf).ok();
//
//     // NSS/CS is a plain GPIO here — drive it low around a transaction.

"#;

const I2C_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const CLOCK_KHZ: u32 = {KHZ}; // <=100 Standard, >100 Fast

// The wired pins, straight from the MCU Configurator's pin map. They live in
// this block because re-wiring the peripheral has to update them; the `use` is
// here too, so the alias holds whatever you do to the `use` block below.
use stm32f1xx_hal::gpio as hal_gpio;

/// The pins I2C{N} is wired to, in HAL order: (SCL, SDA).
///
/// `allow(dead_code)`: `init` below is yours to edit and may stop naming it.
#[allow(dead_code)]
pub type I2cPins = ({PINS});
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    i2c::{self, BlockingI2c, Mode as I2cMode},
};

fn get_mode() -> I2cMode {
    if CLOCK_KHZ <= 100 {
        I2cMode::Standard { frequency: CLOCK_KHZ.kHz() }
    } else {
        I2cMode::Fast { frequency: CLOCK_KHZ.kHz(), duty_cycle: i2c::DutyCycle::Ratio2to1 }
    }
}

/// Bridges the HAL's blocking I2C (embedded-hal 0.2) to the STANDARD
/// `embedded-hal` 1.0 `I2c`, so driver/app code stays portable across HALs:
///
///     fn app<I: embedded_hal::i2c::I2c>(i2c: &mut I) { /* … */ }
pub struct I2cIo<I2C>(pub I2C);

#[derive(Debug)]
pub struct IoError;
impl embedded_hal::i2c::Error for IoError {
    fn kind(&self) -> embedded_hal::i2c::ErrorKind {
        embedded_hal::i2c::ErrorKind::Other
    }
}
impl<I2C> embedded_hal::i2c::ErrorType for I2cIo<I2C> {
    type Error = IoError;
}
impl<I2C> embedded_hal::i2c::I2c<embedded_hal::i2c::SevenBitAddress> for I2cIo<I2C>
where
    I2C: embedded_hal_0_2::blocking::i2c::Read
        + embedded_hal_0_2::blocking::i2c::Write
        + embedded_hal_0_2::blocking::i2c::WriteRead,
{
    fn transaction(
        &mut self,
        addr: u8,
        ops: &mut [embedded_hal::i2c::Operation<'_>],
    ) -> Result<(), Self::Error> {
        use embedded_hal::i2c::Operation;
        // Optimise the common `[Write, Read]` (register read) into one
        // repeated-start `write_read`; single ops map directly. Other multi-op
        // sequences fall back to per-op (each with its own START/STOP).
        match ops {
            [Operation::Write(w), Operation::Read(r)] => {
                embedded_hal_0_2::blocking::i2c::WriteRead::write_read(&mut self.0, addr, w, r)
                    .map_err(|_| IoError)
            }
            _ => {
                for op in ops.iter_mut() {
                    match op {
                        Operation::Read(r) => {
                            embedded_hal_0_2::blocking::i2c::Read::read(&mut self.0, addr, r)
                                .map_err(|_| IoError)?
                        }
                        Operation::Write(w) => {
                            embedded_hal_0_2::blocking::i2c::Write::write(&mut self.0, addr, w)
                                .map_err(|_| IoError)?
                        }
                    }
                }
                Ok(())
            }
        }
    }
}

/// The concrete type [`init`] hands back.
///
/// A NAMED type, not `impl Trait`: a struct field — an RTIC `Local` resource,
/// say — has to name what it holds, and an opaque type cannot be named. The pins
/// stay inside the HAL's `BlockingI2c<…>`, so `I2cPins` from the GENERATED block
/// above is part of it; re-wiring I2C{N} updates this alias with it. It is still
/// an `embedded-hal` 1.0 `I2c` for every caller.
pub type Handle = I2cIo<BlockingI2c<pac::I2C{N}, I2cPins>>;

/// Initialise I2C{N} and expose it as an `embedded-hal` 1.0 `I2c`.
pub fn init(
    i2c: pac::I2C{N},
    pins: I2cPins,
    {AFIO_PARAM}: &mut afio::Parts,
    clocks: &Clocks,
) -> Handle {
    let bus = BlockingI2c::i2c{N}(i2c, pins, {AFIO_ARG}get_mode(), *clocks, 1000, 10, 1000, 1000);
    I2cIo(bus)
}

// ── Using I2C{N} ──
// Portable init — the handle is an `embedded-hal` 1.0 `I2c`. In main.rs,
// after the init above:
//
// NOTE: main.rs binds this handle as `let {HANDLE} = …` — add `mut`
// there before calling anything below (bus methods take `&mut self`).
//
//     use embedded_hal::i2c::I2c;
//
//     const ADDR: u8 = 0x3C; // 7-bit device address
//
//     // Write to a register
//     {HANDLE}.write(ADDR, &[0x10, 0x42]).ok();
//
//     // Read bytes
//     let mut rx = [0u8; 2];
//     {HANDLE}.read(ADDR, &mut rx).ok();
//
//     // Register read: write the address, then read WITHOUT releasing the bus
//     // (repeated START) — what most sensors expect.
//     {HANDLE}.write_read(ADDR, &[0x10], &mut rx).ok();

"#;

fn i2c_config_file(n: u8, cfg: Option<&I2cModuleConfig>, pins: &str) -> String {
    let khz = cfg.map(|c| c.clock_hz).unwrap_or(100_000) / 1_000;
    let tmpl = match cfg.map(|c| c.api_style).unwrap_or_default() {
        ApiStyle::Portable => I2C_TMPL,
        ApiStyle::Native => I2C_TMPL_NATIVE,
    };
    // Only I2C1 can be remapped (PB8/PB9), so only `i2c1` takes the AFIO.
    let (afio_param, afio_arg) = afio_subst(n == 1);
    let sfx = cfg
        .map(|c| module_label_sfx(&c.custom_label))
        .unwrap_or_default();
    tmpl.replace("{HANDLE}", &format!("_i2c{n}{sfx}"))
        .replace("{N}", &n.to_string())
        .replace("{KHZ}", &khz.to_string())
        .replace("{PINS}", pins)
        .replace("{AFIO_PARAM}", afio_param)
        .replace("{AFIO_ARG}", afio_arg)
}

/// Native `stm32f1xx-hal` I2C init (no eh-1.0 bridge). Returns `BlockingI2c<…>`.
const I2C_TMPL_NATIVE: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const CLOCK_KHZ: u32 = {KHZ}; // <=100 Standard, >100 Fast

// The wired pins, straight from the MCU Configurator's pin map. They live in
// this block because re-wiring the peripheral has to update them; the `use` is
// here too, so the alias holds whatever you do to the `use` block below.
use stm32f1xx_hal::gpio as hal_gpio;

/// The pins I2C{N} is wired to, in HAL order: (SCL, SDA).
///
/// `allow(dead_code)`: `init` below is yours to edit and may stop naming it.
#[allow(dead_code)]
pub type I2cPins = ({PINS});
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
// NATIVE stm32f1xx-hal API — returns `BlockingI2c<…>`. Switch to the portable
// `embedded-hal` 1.0 `I2c` API in the Virtual Module.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    i2c::{self, BlockingI2c, Mode as I2cMode},
};

fn get_mode() -> I2cMode {
    if CLOCK_KHZ <= 100 {
        I2cMode::Standard { frequency: CLOCK_KHZ.kHz() }
    } else {
        I2cMode::Fast { frequency: CLOCK_KHZ.kHz(), duty_cycle: i2c::DutyCycle::Ratio2to1 }
    }
}

/// The concrete type [`init`] hands back — the HAL's own `BlockingI2c`, with the
/// pins it keeps in its type. Named so it can be a struct field (an RTIC `Local`
/// resource, say); `I2cPins` comes from the GENERATED block above, so re-wiring
/// I2C{N} updates this one with it.
pub type Handle = BlockingI2c<pac::I2C{N}, I2cPins>;

pub fn init(
    i2c: pac::I2C{N},
    pins: I2cPins,
    {AFIO_PARAM}: &mut afio::Parts,
    clocks: &Clocks,
) -> Handle {
    BlockingI2c::i2c{N}(i2c, pins, {AFIO_ARG}get_mode(), *clocks, 1000, 10, 1000, 1000)
}

// ── Using I2C{N} ──
// Native init — the concrete `stm32f1xx-hal` BlockingI2c, whose traits are
// `embedded-hal` 0.2. In main.rs, after the init above:
//
// NOTE: the Native path needs the 0.2 traits, which the IDE only adds to
// Cargo.toml for PORTABLE modules. Add them yourself:
//   embedded-hal-0-2 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }
// — or switch this module's Init API to Portable, where the handle is an
// embedded-hal 1.0 bus and no extra dependency is needed.
//
// NOTE: main.rs binds this handle as `let {HANDLE} = …` — add `mut`
// there before calling anything below (bus methods take `&mut self`).
//
//     use embedded_hal_0_2::blocking::i2c::{Read, Write, WriteRead};
//
//     const ADDR: u8 = 0x3C; // 7-bit device address
//
//     {HANDLE}.write(ADDR, &[0x10, 0x42]).ok();
//
//     let mut rx = [0u8; 2];
//     {HANDLE}.read(ADDR, &mut rx).ok();
//     {HANDLE}.write_read(ADDR, &[0x10], &mut rx).ok();

"#;

/// The section header older versions inserted before the appended helpers.
const HELPERS_HEADER: &str = "── Peripheral init helpers";

/// Helper fns older versions appended after `fn main`. All of them are dead code
/// now: USART/SPI/I2C init moved to `src/pins/configs/` and the ADC is built by
/// a plain `adc::Adc::adc1(dp.ADC1, clocks)` line inside the GENERATED block.
const OBSOLETE_HELPERS: &[&str] = &["init_usart", "init_spi", "init_i2c", "init_adc"];

/// Strip the obsolete peripheral init helpers (and their now-empty section
/// header) from an existing `main.rs`. These were generated code, so they are
/// removed whole — body included — rather than left behind as dead fns the
/// project can no longer compile (their `Clocks` parameter has no import).
pub fn strip_obsolete_helpers(file: String) -> String {
    let is_obsolete_fn = |line: &str| {
        line.trim_start().strip_prefix("fn ").is_some_and(|rest| {
            OBSOLETE_HELPERS.iter().any(|name| {
                rest.starts_with(name)
                    && rest[name.len()..].starts_with(|c: char| c.is_ascii_digit())
            })
        })
    };
    if !file.lines().any(is_obsolete_fn) {
        return file;
    }

    // Drop each helper from its `fn` line through its closing brace.
    let mut kept: Vec<&str> = Vec::new();
    let mut depth = 0i32;
    let mut in_helper = false;
    for line in file.lines() {
        if !in_helper && is_obsolete_fn(line) {
            in_helper = true;
            depth = 0;
        }
        if in_helper {
            depth += line.matches('{').count() as i32;
            depth -= line.matches('}').count() as i32;
            // `depth == 0` before the opening brace too (multi-line signature),
            // so only a line that actually closed a brace ends the helper.
            if depth <= 0 && line.contains('}') {
                in_helper = false;
            }
            continue;
        }
        kept.push(line);
    }

    // The section header is only there to introduce the helpers — drop it (and
    // the blank lines around it) once nothing follows it any more.
    if let Some(hdr) = kept.iter().position(|l| l.contains(HELPERS_HEADER)) {
        if kept[hdr + 1..].iter().all(|l| l.trim().is_empty()) {
            kept.truncate(hdr);
        }
    }
    while kept.last().is_some_and(|l| l.trim().is_empty()) {
        kept.pop();
    }

    let mut out = kept.join("\n");
    out.push('\n');
    out
}

// ── Pin helpers ───────────────────────────────────────────────────────────────

struct PinMeta {
    port: char,
    pin_num: u8,
    var: String,
    port_var: String,
    crx: &'static str,
}

fn parse_pin(name: &str) -> Option<PinMeta> {
    let bytes = name.as_bytes();
    if bytes.len() < 3 || bytes[0] != b'P' {
        return None;
    }
    let port = bytes[1] as char;
    if !port.is_ascii_uppercase() {
        return None;
    }
    let pin_num: u8 = name[2..].parse().ok()?;
    let lc = port.to_ascii_lowercase();
    Some(PinMeta {
        port,
        pin_num,
        var: format!("p{}{}", lc, pin_num),
        port_var: format!("gpio{}", lc),
        crx: if pin_num < 8 { "crl" } else { "crh" },
    })
}

/// The `.into_*(…)` call for a pin. `mode` is the user's GPIO drive/pull choice
/// (`None` = this backend's default: floating in, push-pull out) and only
/// applies to GPIO In/Out — a peripheral pin's mode is dictated by the
/// peripheral, not by the user.
fn into_expr(func: &PinFunction, mode: Option<GpioMode>, pv: &str, crx: &str) -> String {
    match func {
        PinFunction::GpioInput => {
            let m = mode.unwrap_or(GpioMode::Floating).into_method();
            format!("{m}(&mut {pv}.{crx})")
        }
        PinFunction::GpioOutput => {
            let m = mode.unwrap_or(GpioMode::PushPull).into_method();
            format!("{m}(&mut {pv}.{crx})")
        }
        // Same call as an ADC channel: analog mode IS `into_analog`, it just
        // doesn't name which analog block reads the pin.
        PinFunction::GpioAnalog | PinFunction::AdcChannel { .. } => {
            format!("into_analog(&mut {pv}.{crx})")
        }
        PinFunction::TimerPwm { .. } => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        // LPUART / SPI-RDY don't exist on STM32F1; they're grouped with their
        // closest USART/SPI analogue so the mode stays sane if ever selected.
        PinFunction::UsartTx(_) | PinFunction::UsartCk(_) | PinFunction::LpuartTx(_) => {
            format!("into_alternate_push_pull(&mut {pv}.{crx})")
        }
        PinFunction::UsartRx(_)
        | PinFunction::UsartCts(_)
        | PinFunction::LpuartRx(_)
        | PinFunction::LpuartCts(_) => {
            format!("into_floating_input(&mut {pv}.{crx})")
        }
        PinFunction::UsartRts(_) | PinFunction::LpuartRts(_) => {
            format!("into_push_pull_output(&mut {pv}.{crx})")
        }
        PinFunction::SpiSck(_) | PinFunction::SpiMosi(_) => {
            format!("into_alternate_push_pull(&mut {pv}.{crx})")
        }
        PinFunction::SpiNss(_) => format!("into_push_pull_output(&mut {pv}.{crx})"),
        PinFunction::SpiMiso(_) | PinFunction::SpiRdy(_) => {
            format!("into_floating_input(&mut {pv}.{crx})")
        }
        PinFunction::I2cScl(_) | PinFunction::I2cSda(_) => {
            format!("into_alternate_open_drain(&mut {pv}.{crx})")
        }
        PinFunction::Mco => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        PinFunction::CanTx => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        PinFunction::CanRx => format!("into_floating_input(&mut {pv}.{crx})"),
        PinFunction::UsbDm | PinFunction::UsbDp => {
            "// USB — configured automatically by the USB peripheral".to_owned()
        }
        PinFunction::SwdIo | PinFunction::SwdClk => {
            "// SWD — active by default, no config needed".to_owned()
        }
        // Generic alternate function — push-pull AF is the safe default; the
        // user refines it if that peripheral needs something else.
        PinFunction::Other(_) => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        PinFunction::Unset => unreachable!(),
    }
}

fn is_comment_expr(expr: &str) -> bool {
    expr.trim_start().starts_with("//")
}

/// Returns `true` for pins that are driven (output / alternate-output).
/// These get a `&mut` prefix so the binding is immediately usable as a
/// mutable reference without a later `&mut var` at each call site.
/// Whether an OWNED GPIO binding has to be `let mut`.
///
/// Owning the pin (instead of taking `&mut` of a temporary) means the `mut` now
/// has to be spelled out wherever the pin is written through:
/// * an **output** always — `set_high` takes `&mut self` in both `embedded-hal`
///   0.2 and 1.0;
/// * an **input** only on the Portable path — `embedded-hal` 1.0's `InputPin`
///   reads through `&mut self`, while the raw `stm32f1xx-hal` (0.2) input reads
///   through `&self`, where a `mut` would just earn an unused-mut warning;
/// * never when the pin is **moved into a Custom module** below, since the
///   binding is then consumed, never written through.
///
/// The "moved" test reads the already-rendered `custom_inits` text rather than
/// re-deriving which modules get built: that text is what actually passes the
/// binding, so the two can't disagree.
fn needs_mut_binding(
    pin: &Pin,
    gpio_native: bool,
    binding_style: Binding,
    binding: &str,
    custom_inits: &str,
) -> bool {
    if binding_style == Binding::Owned {
        return false; // RTIC moves it into a `Local`
    }
    let write_through = match pin.selected_function {
        PinFunction::GpioOutput => true,
        PinFunction::GpioInput => !gpio_native,
        _ => false,
    };
    if !write_through {
        return false;
    }
    let moved = custom_inits.contains(&format!("{binding},"))
        || custom_inits.contains(&format!("{binding})"));
    !moved
}

fn needs_mut_ref(func: &PinFunction) -> bool {
    matches!(
        func,
        PinFunction::GpioOutput
            | PinFunction::TimerPwm { .. }
          //  | PinFunction::UsartTx(_)
            | PinFunction::UsartCk(_)
            | PinFunction::UsartRts(_)
           //cd  | PinFunction::SpiSck(_)
           // | PinFunction::SpiMosi(_)
           // | PinFunction::SpiNss(_)
           // | PinFunction::I2cScl(_)
           // | PinFunction::I2cSda(_)
            | PinFunction::Mco
            | PinFunction::CanTx
    )
}
