//! STM32 code generation — HAL code building, section splicing, pin parsing.

use super::super::clock::frequencies;
use super::super::clock::model::{ClockConfig, PllSrc, Stm32f1Clock, SysclkSrc};
use super::super::modules::{
    CanModuleConfig, I2cModuleConfig, Parity, SpiModuleConfig, StopBits, UsartModuleConfig,
    UsbModuleConfig,
};
use super::super::pins::logic::pin::Pin;
use super::super::pins::logic::pin_function::PinFunction;
use super::{GEN_BEGIN, GEN_END, USER_TAIL, mcu_id_marker_line, pin_binding, sanitize_label};
use std::collections::{BTreeMap, BTreeSet};

/// `_<sanitized label>` suffix for a module's generated handle variable, or ""
/// when the module has no user label. So a GI_SPI labelled "imu" turns `_spi1`
/// into `_spi1_imu` — the module analogue of the per-pin `<pin>_<type>_<label>`.
fn module_label_sfx(label: &str) -> String {
    let s = sanitize_label(label);
    if s.is_empty() {
        String::new()
    } else {
        format!("_{s}")
    }
}

/// Variable (binding) name for a pin: `<pin>_<type>[_<label>]`, e.g. `pc13_out`,
/// `pb9_i2c1_sda`, or `pc13_out_led` when the pin carries a user label. Only the
/// `let` binding and later references carry the suffix — the HAL field access
/// stays the bare pin (`meta.var`, e.g. `gpioc.pc13`).
fn binding_of(pin: &Pin, meta: &PinMeta) -> String {
    pin_binding(&meta.var, &pin.selected_function, &pin.custom_label)
}

// ── Section splicing ──────────────────────────────────────────────────────────

pub fn splice_section(existing: &str, new_section: &str, mcu_name: &str, mcu_id: &str) -> String {
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        // Strip ALL leading newlines after GEN_END, then re-add exactly one
        // blank line.  This makes splice idempotent: running it N times always
        // produces the same result instead of accumulating newlines.
        let after = existing[end..].trim_start_matches('\n');

        // Detect old format (had fn custom_config / fn loop_code after GEN_END).
        // Rebuild from scratch so the user tail is the new flat loop{} style.
        if after.contains("fn custom_config()") || after.contains("fn loop_code()") {
            return format!(
                "{}{}\n{}",
                invariant_header(mcu_name, mcu_id),
                new_section,
                USER_TAIL,
            );
        }

        // new_section already ends with "// <<< GENERATED END >>>\n"
        // + one more "\n" gives a single blank line before the user tail.
        format!("{}{}\n{}", &existing[..begin], new_section, after)
    } else {
        // Markers not found — rebuild from scratch.
        format!(
            "{}{}\n{}",
            invariant_header(mcu_name, mcu_id),
            new_section,
            USER_TAIL,
        )
    }
}

// ── Invariant file header ─────────────────────────────────────────────────────

pub fn invariant_header(mcu_name: &str, mcu_id: &str) -> String {
    format!(
        "// Auto-generated by Embedded IDE\n\
         // MCU: {mcu_name} | HAL: stm32f1xx-hal\n\
         {id}\n\
         #![no_std]\n\
         #![no_main]\n\n\
         pub mod pins;\n\n\
         use panic_halt as _;\n\
         use cortex_m_rt::entry;\n\n",
        id = mcu_id_marker_line(mcu_id),
    )
}

// ── Clock setup (rcc.cfgr chain) ──────────────────────────────────────────────

/// Format a Hz value as a stm32f1xx-hal rate literal (`72.MHz()`, `48.kHz()`…).
fn freq_lit(hz: u32) -> String {
    if hz % 1_000_000 == 0 {
        format!("{}.MHz()", hz / 1_000_000)
    } else if hz % 1_000 == 0 {
        format!("{}.kHz()", hz / 1_000)
    } else {
        format!("{hz}.Hz()")
    }
}

/// Build the `rcc.cfgr … .freeze(&mut flash.acr)` chain from the clock config.
///
/// Only knobs that deviate from the HAL's natural defaults are emitted, so the
/// default 72 MHz config produces exactly the original
/// `use_hse(8).sysclk(72).pclk1(36)` chain (no spurious diffs).
pub fn clock_setup_chain(clock: &ClockConfig) -> String {
    let c: Stm32f1Clock = match clock {
        // The graph is the only clock model — read its node states back into
        // the typed codegen intermediate.
        ClockConfig::Graph(gc) => {
            crate::panels::mcu_module::clock::graph::graph_to_stm32f1(&gc.graph)
        }
        ClockConfig::None => Stm32f1Clock::default(),
    };
    let f = frequencies(&c);
    // Newline + 17 spaces → lines up the `.method()` calls under `rcc.cfgr`.
    const IND: &str = "\n                 ";

    let mut s = String::from("rcc.cfgr");
    let use_hse = c.hse_enabled
        && (c.sysclk_src == SysclkSrc::Hse
            || (c.sysclk_src == SysclkSrc::Pll
                && matches!(c.pll_src, PllSrc::Hse | PllSrc::HseDiv2)));
    if use_hse {
        s.push_str(&format!("{IND}.use_hse({})", freq_lit(c.hse_hz)));
    }
    s.push_str(&format!("{IND}.sysclk({})", freq_lit(f.sysclk)));
    s.push_str(&format!("{IND}.pclk1({})", freq_lit(f.pclk1)));
    if c.ahb_pre != 1 {
        s.push_str(&format!("{IND}.hclk({})", freq_lit(f.hclk)));
    }
    if c.apb2_pre != 1 {
        s.push_str(&format!("{IND}.pclk2({})", freq_lit(f.pclk2)));
    }
    if c.adc_pre != 6 {
        s.push_str(&format!("{IND}.adcclk({})", freq_lit(f.adcclk)));
    }
    s.push_str(&format!("{IND}.freeze(&mut flash.acr)"));
    s
}

// ── Generated section builder ─────────────────────────────────────────────────

pub fn make_generated_section(
    mcu_name: &str,
    all_pins: &[&Pin],
    clock: &ClockConfig,
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    can: &BTreeMap<u8, CanModuleConfig>,
    usb: &BTreeMap<u8, UsbModuleConfig>,
) -> String {
    let configured: Vec<(&Pin, PinMeta)> = all_pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .filter_map(|p| parse_pin(&p.name).map(|m| (*p, m)))
        .collect();

    if configured.is_empty() {
        return make_default_gen_section(mcu_name, clock);
    }

    // ── Ports used ───────────────────────────────────────────────────────────
    let mut ports_used: BTreeSet<char> = BTreeSet::new();
    for (_, meta) in &configured {
        ports_used.insert(meta.port);
    }

    // ── Feature flags ────────────────────────────────────────────────────────
    let has_serial = configured.iter().any(|(p, _)| {
        matches!(
            p.selected_function,
            PinFunction::UsartTx(_) | PinFunction::UsartRx(_)
        )
    });
    let has_spi = configured.iter().any(|(p, _)| {
        matches!(
            p.selected_function,
            PinFunction::SpiSck(_) | PinFunction::SpiMosi(_)
        )
    });
    let has_i2c = configured.iter().any(|(p, _)| {
        matches!(
            p.selected_function,
            PinFunction::I2cScl(_) | PinFunction::I2cSda(_)
        )
    });
    let has_adc = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::AdcChannel { .. }));
    let has_timer = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::TimerPwm { .. }));
    let has_can = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::CanRx | PinFunction::CanTx));
    let has_usb = configured
        .iter()
        .any(|(p, _)| matches!(p.selected_function, PinFunction::UsbDm | PinFunction::UsbDp));
    // CAN's `assign_pins` needs AFIO too (it may remap the pins).
    let needs_afio = has_serial || has_spi || has_i2c || has_timer || has_can;
    let has_periph_fns = has_serial || has_spi || has_i2c || has_adc || has_can;

    // ── SPI instances ────────────────────────────────────────────────────────
    let mut spi_instances: BTreeSet<u8> = BTreeSet::new();
    for (pin, _) in &configured {
        match pin.selected_function {
            PinFunction::SpiSck(n)
            | PinFunction::SpiMosi(n)
            | PinFunction::SpiMiso(n)
            | PinFunction::SpiNss(n) => {
                spi_instances.insert(n);
            }
            _ => {}
        }
    }

    // ── HAL use block ────────────────────────────────────────────────────────
    let mut use_items: Vec<String> = vec!["pac".into(), "prelude::*".into()];
    // if has_periph_fns || needs_afio {
    //     if needs_afio {
    //         use_items.push("afio".into());
    //     }
    //     use_items.push("rcc::Clocks".into());
    // }
    if has_serial {
        // use_items.push("serial::{self, Config, Serial}".into());
    }
    if has_spi {
        // let remaps = spi_instances
        //     .iter()
        //     .map(|n| format!("Spi{n}NoRemap"))
        //     .collect::<Vec<_>>()
        //     .join(", ");
        // use_items.push(format!(
        //     "spi::{{self, Mode, Phase, Polarity, Spi, {remaps}}}"
        // ));
    }
    if has_i2c {
        //  use_items.push("i2c::{self, BlockingI2c, Mode as I2cMode}".into());
    }
    if has_adc {
        use_items.push("adc".into());
    }
    if has_timer {
        use_items.push("timer::Timer".into());
    }
    if has_usb {
        use_items.push("usb::{Peripheral, UsbBus}".into());
    }

    let use_block = use_items
        .iter()
        .map(|s| format!("    {s},"))
        .collect::<Vec<_>>()
        .join("\n");

    // USB needs top-level `use`s from the external usb-device / usbd-serial
    // crates (auto-added to Cargo.toml) — these can't live in the HAL `use {}`.
    let extra_uses = if has_usb {
        "use usb_device::prelude::*;\nuse usbd_serial::{SerialPort, USB_CLASS_CDC};\n"
    } else {
        ""
    };

    // ── Pin declaration lines ────────────────────────────────────────────────
    let mut port_groups: BTreeMap<char, Vec<String>> = BTreeMap::new();
    for (pin, meta) in &configured {
        let expr = into_expr(&pin.selected_function, &meta.port_var, meta.crx);
        let comment = pin.selected_function.label();
        let line = if is_comment_expr(&expr) {
            format!(
                "    // {}: {}",
                pin.name,
                expr.trim_start_matches("//").trim()
            )
        } else {
            let prefix = if needs_mut_ref(&pin.selected_function) {
                "&mut "
            } else {
                ""
            };
            format!(
                "    let {binding} = {prefix}{pv}.{field}.{expr}; // {comment}",
                binding = binding_of(pin, meta),
                field = meta.var,
                pv = meta.port_var,
            )
        };
        port_groups.entry(meta.port).or_default().push(line);
    }

    let mut pin_section = String::new();
    for (port, lines) in &port_groups {
        pin_section.push_str(&format!("    // ── Port {port} ──\n"));
        for l in lines {
            pin_section.push_str(l);
            pin_section.push('\n');
        }
        pin_section.push('\n');
    }

    // Peripheral helper functions (init_usartN, init_spiN, init_i2cN,
    // init_adc1) are NO LONGER emitted inside this generated block. They are
    // placed in the editable region AFTER `fn main` (see `helper_defs` /
    // `ensure_helper_defs`) so the user can tweak them. `fn_calls` below still
    // references them by name.

    // ── Peripheral init calls (inside fn main) ───────────────────────────────
    let mut fn_calls = String::new();
    let mut any_call = false;

    macro_rules! header {
        () => {
            if !any_call {
                fn_calls.push_str("    // ── Peripheral initialisation ──\n");
                any_call = true;
            }
        };
    }

    for n in 1u8..=3 {
        let tx = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::UsartTx(n));
        let rx = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::UsartRx(n));
        if tx.is_none() && rx.is_none() {
            continue;
        }
        header!();
        let tx_v = tx
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_tx{n}"));
        let rx_v = rx
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_rx{n}"));
        let sfx = usart
            .get(&n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    let (mut _tx{n}{sfx}, mut _rx{n}{sfx}) = \
             pins::configs::usart{n}::init(dp.USART{n}, ({tx_v}, {rx_v}), &mut afio, &clocks);\n"
        ));
    }

    for n in 1u8..=2 {
        let sck = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::SpiSck(n));
        let miso = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::SpiMiso(n));
        let mosi = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::SpiMosi(n));
        if sck.is_none() && mosi.is_none() {
            continue;
        }
        header!();
        let sck_v = sck
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_sck{n}"));
        let miso_v = miso
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_miso{n}"));
        let mosi_v = mosi
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or_else(|| format!("_mosi{n}"));
        let sfx = spi
            .get(&n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    let _spi{n}{sfx} = \
             pins::configs::spi{n}::init(dp.SPI{n}, ({sck_v}, {miso_v}, {mosi_v}), &mut afio, &clocks);\n"
        ));
    }

    for n in 1u8..=2 {
        let scl = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::I2cScl(n));
        let sda = configured
            .iter()
            .find(|(p, _)| p.selected_function == PinFunction::I2cSda(n));
        if scl.is_none() || sda.is_none() {
            continue;
        }
        header!();
        let scl_v = {
            let (p, m) = scl.unwrap();
            binding_of(p, m)
        };
        let sda_v = {
            let (p, m) = sda.unwrap();
            binding_of(p, m)
        };
        let sfx = i2c
            .get(&n)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    let _i2c{n}{sfx} = \
             pins::configs::i2c{n}::init(dp.I2C{n}, ({scl_v}, {sda_v}), &mut afio, &clocks);\n"
        ));
    }

    if has_adc {
        header!();
        fn_calls.push_str("    let mut _adc1 = init_adc1(dp.ADC1, clocks);\n");
        for (p, meta) in configured
            .iter()
            .filter(|(p, _)| matches!(p.selected_function, PinFunction::AdcChannel { .. }))
        {
            fn_calls.push_str(&format!(
                "    // let val: u16 = _adc1.read(&mut {}).unwrap();\n",
                binding_of(p, meta)
            ));
        }
    }

    if has_timer {
        header!();
        fn_calls.push_str("    // ── Timers / PWM ──\n");
        fn_calls.push_str("    // let pwm = Timer::tim2(dp.TIM2, &clocks)\n");
        fn_calls.push_str(
            "    //     .pwm_hz::<Tim2NoRemap, _, _>((pa0, pa1), &mut afio.mapr, 1.kHz());\n",
        );
    }

    let can_rx = configured
        .iter()
        .find(|(p, _)| p.selected_function == PinFunction::CanRx);
    let can_tx_pin = configured
        .iter()
        .find(|(p, _)| p.selected_function == PinFunction::CanTx);
    if can_rx.is_some() || can_tx_pin.is_some() {
        header!();
        let rx_v = can_rx
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or("_can_rx".into());
        let tx_v = can_tx_pin
            .map(|(p, m)| binding_of(p, m))
            .unwrap_or("_can_tx".into());
        let sfx = can
            .get(&1)
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        // `assign_pins` (and bxcan) expect the pins as `(TX, RX)`.
        fn_calls.push_str(&format!(
            "    let mut _can{sfx} = \
             pins::configs::can1::init(dp.CAN1, ({tx_v}, {rx_v}), &mut afio);\n"
        ));
    }

    // ── USB (CDC ACM serial) — full init in main's scope (option A) ───────────
    // USB needs `usb_dev`/`serial` to live where the user's loop polls them, and
    // its bus allocator borrows them, so it can't go in a `pins::configs` init().
    // Pins PA11(D-)/PA12(D+) are emitted as comments (not generic bindings), so
    // this block owns their configuration.
    if has_usb {
        header!();
        let cfg = usb.get(&1);
        let vid = cfg.map(|c| c.vid).unwrap_or(0x16c0);
        let pid = cfg.map(|c| c.pid).unwrap_or(0x27dd);
        let product = cfg.map(|c| c.product.as_str()).unwrap_or("Serial port");
        let sfx = cfg
            .map(|c| module_label_sfx(&c.custom_label))
            .unwrap_or_default();
        fn_calls.push_str(&format!(
            "    // ── USB (CDC ACM serial) ──\n\
             // Needs the `usb-device` + `usbd-serial` crates and the HAL `stm32-usbd`\n\
             // feature (auto-added to Cargo.toml). Poll in your loop:\n\
             //     if usb_dev{sfx}.poll(&mut [&mut serial{sfx}]) {{ /* read/write serial */ }}\n\
             // Pull D+ low briefly so the host re-enumerates after a reset.\n\
             let mut usb_dp = gpioa.pa12.into_push_pull_output(&mut gpioa.crh);\n\
             usb_dp.set_low();\n\
             cortex_m::asm::delay(clocks.sysclk().raw() / 100);\n\
             let usb_periph = Peripheral {{\n\
                 usb: dp.USB,\n\
                 pin_dm: gpioa.pa11,\n\
                 pin_dp: usb_dp.into_floating_input(&mut gpioa.crh),\n\
             }};\n\
             let usb_bus = UsbBus::new(usb_periph);\n\
             let mut serial{sfx} = SerialPort::new(&usb_bus);\n\
             let mut usb_dev{sfx} = UsbDeviceBuilder::new(&usb_bus, UsbVidPid(0x{vid:04x}, 0x{pid:04x}))\n\
                 .product(\"{product}\")\n\
                 .device_class(USB_CLASS_CDC)\n\
                 .build();\n"
        ));
    }

    if any_call {
        fn_calls.push('\n');
    }

    // ── Assemble port splits ─────────────────────────────────────────────────
    let port_splits = ports_used
        .iter()
        .map(|p| {
            let lc = p.to_ascii_lowercase();
            format!("    let mut gpio{lc} = dp.GPIO{p}.split();")
        })
        .collect::<Vec<_>>()
        .join("\n");

    let afio_line = if needs_afio {
        "let mut afio = dp.AFIO.constrain();\n"
    } else {
        ""
    };

    // ── Clock setup chain (from the Clock tab config) ────────────────────────
    let clock_chain = clock_setup_chain(clock);

    // Peripheral config constants now live in the per-peripheral modules under
    // `src/pins/configs/` (e.g. `pins::configs::usart1`), seeded from the wired
    // Virtual Module — no longer emitted in main.rs.

    // ── Put it all together ──────────────────────────────────────────────────
    // Only the ADC init helper is appended after `fn main` (by
    // `ensure_helper_defs`); USART/SPI/I2C init live in `src/pins/configs/`.
    format!(
        "{GEN_BEGIN}\n\
         use stm32f1xx_hal::{{\n\
         {use_block}\n\
         }};\n\
         {extra_uses}\
         \n\
         #[entry]\n\
         fn main() -> ! {{\n\
             let dp = pac::Peripherals::take().unwrap();\n\n\
             let mut flash = dp.FLASH.constrain();\n\
             let rcc = dp.RCC.constrain();\n\
         {afio_line}\
             let clocks = {clock_chain};\n\n\
         {port_splits}\n\n\
         {pin_section}\
         {fn_calls}\
         {GEN_END}\n"
    )
}

// ── Default generated section (no pins configured yet) ────────────────────────

fn make_default_gen_section(mcu_name: &str, clock: &ClockConfig) -> String {
    let clock_chain = clock_setup_chain(clock);
    format!(
        "{GEN_BEGIN}\n\
         // MCU: {mcu_name}\n\
         use stm32f1xx_hal::{{pac, prelude::*}};\n\n\
         #[entry]\n\
         fn main() -> ! {{\n\
             let dp = pac::Peripherals::take().unwrap();\n\n\
             let mut flash = dp.FLASH.constrain();\n\
             let rcc = dp.RCC.constrain();\n\
             let _clocks = {clock_chain};\n\n\
             // Select pins in the MCU Configurator to generate code here.\n\
         {GEN_END}\n"
    )
}

// ── Editable peripheral init helper (ADC only — placed after `fn main`) ───────

/// Peripheral init helper(s) that stay inline in `main.rs` — only the ADC one
/// now (it has no Virtual-Module config and takes `Clocks` by value). Each entry
/// is `(fn_name, full_definition)`, added additively by [`ensure_helper_defs`]
/// to the user-editable region after `fn main`. USART/SPI/I2C init moved to the
/// per-peripheral modules under `src/pins/configs/` (see `config_files`).

pub fn helper_defs(all_pins: &[&Pin]) -> Vec<(String, String)> {
    let funcs: Vec<&PinFunction> = all_pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .map(|p| &p.selected_function)
        .collect();

    let mut defs: Vec<(String, String)> = Vec::new();

    // USART / SPI / I2C init now live in `src/pins/configs/` (see `config_files`).
    // Only the ADC helper stays inline here — `Adc::adc1` takes `Clocks` BY VALUE
    // (Clocks is Copy), not `&Clocks`, and ADC has no Virtual-Module config.
    if funcs
        .iter()
        .any(|f| matches!(f, PinFunction::AdcChannel { .. }))
    {
        defs.push((
            "init_adc1".to_string(),
            "fn init_adc1(adc1: pac::ADC1, clocks: Clocks) -> adc::Adc<pac::ADC1> {
    adc::Adc::adc1(adc1, clocks)
}"
            .to_string(),
        ));
    }

    defs
}

// ── Per-peripheral config files (src/pins/configs/) ───────────────────────────

/// The body of each `src/pins/configs/<periph>.rs` init module: config
/// constants (seeded from the wired Virtual Module) + a `use` block + a config
/// helper + `pub fn init`. Returns `(file_name, generated_body)` per configured
/// USART/SPI/I2C. `project_tree::sync_config_files` wraps the body in GENERATED
/// markers and splices it (so user code outside the markers survives). main.rs
/// calls `pins::configs::<periph>::init(...)`.
pub fn config_files(
    all_pins: &[&Pin],
    usart: &BTreeMap<u8, UsartModuleConfig>,
    spi: &BTreeMap<u8, SpiModuleConfig>,
    i2c: &BTreeMap<u8, I2cModuleConfig>,
    can: &BTreeMap<u8, CanModuleConfig>,
    clock: &ClockConfig,
) -> Vec<(String, String)> {
    let funcs: Vec<&PinFunction> = all_pins
        .iter()
        .filter(|p| !p.reserved && p.selected_function != PinFunction::Unset)
        .map(|p| &p.selected_function)
        .collect();
    let has = |want: PinFunction| funcs.iter().any(|f| **f == want);

    let mut out: Vec<(String, String)> = Vec::new();
    for n in 1u8..=3 {
        if has(PinFunction::UsartTx(n)) || has(PinFunction::UsartRx(n)) {
            out.push((format!("usart{n}.rs"), usart_config_file(n, usart.get(&n))));
        }
    }
    for n in 1u8..=2 {
        if has(PinFunction::SpiSck(n)) || has(PinFunction::SpiMosi(n)) {
            out.push((format!("spi{n}.rs"), spi_config_file(n, spi.get(&n))));
        }
    }
    for n in 1u8..=2 {
        if has(PinFunction::I2cScl(n)) && has(PinFunction::I2cSda(n)) {
            out.push((format!("i2c{n}.rs"), i2c_config_file(n, i2c.get(&n))));
        }
    }
    // CAN — single instance on STM32F1; the bit-timing register depends on the
    // APB1 (PCLK1) clock, so the clock config is read here.
    if has(PinFunction::CanRx) || has(PinFunction::CanTx) {
        out.push((
            "can1.rs".to_string(),
            can_config_file(can.get(&1), pclk1_of(clock)),
        ));
    }
    out
}

/// APB1 (PCLK1) frequency in Hz from the clock config — needed for the CAN bit
/// timing. Mirrors [`clock_setup_chain`]'s graph→typed→frequencies path.
fn pclk1_of(clock: &ClockConfig) -> u32 {
    let c: Stm32f1Clock = match clock {
        ClockConfig::Graph(gc) => {
            crate::panels::mcu_module::clock::graph::graph_to_stm32f1(&gc.graph)
        }
        ClockConfig::None => Stm32f1Clock::default(),
    };
    frequencies(&c).pclk1
}

/// STM32 `CAN_BTR` register value for `bitrate` at `pclk1`, aiming for a ~87.5%
/// sample point. Searches total time-quanta 8..=20 for an exact prescaler.
/// Returns 0 when none fits (so the user notices and fixes the bit timing).
fn can_btr(bitrate: u32, pclk1: u32) -> u32 {
    if bitrate == 0 || pclk1 == 0 {
        return 0;
    }
    for ntq in (8u32..=20).rev() {
        let denom = bitrate * ntq;
        if pclk1 % denom != 0 {
            continue;
        }
        let brp = pclk1 / denom;
        if !(1..=1024).contains(&brp) {
            continue;
        }
        // total = 1 (sync) + ts1 + ts2 = ntq; sample point ≈ ts1/ntq.
        let ts1 = ((ntq * 7) / 8).clamp(2, 16);
        let ts2 = (ntq - 1).saturating_sub(ts1);
        if !(1..=8).contains(&ts2) {
            continue;
        }
        let sjw = 1u32;
        return ((sjw - 1) << 24) | ((ts2 - 1) << 20) | ((ts1 - 1) << 16) | (brp - 1);
    }
    0
}

const CAN_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const BITRATE: u32 = {BITRATE}; // bits/s
// CAN_BTR register value, computed from BITRATE and the APB1 clock ({PCLK1} Hz).
const BTR: u32 = {BTR};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
// CAN on STM32F1 needs the `bxcan` + `nb` crates (auto-added to Cargo.toml when a
// CAN module is present). Verify the bit timing / filters for your bus.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    can::Can,
};

pub fn init<PINS>(
    can: pac::CAN1,
    pins: PINS,
    afio: &mut afio::Parts,
) -> bxcan::Can<Can<pac::CAN1>>
where
    PINS: stm32f1xx_hal::can::Pins<Instance = pac::CAN1>,
{
    let mut hal_can = Can::new(can);
    hal_can.assign_pins(pins, &mut afio.mapr);

    let mut bx = bxcan::Can::builder(hal_can)
        .set_bit_timing(BTR)
        .leave_disabled();

    // Accept every frame by default — tighten the filter for your application.
    bx.modify_filters().enable_bank(0, bxcan::filter::Mask32::accept_all());

    nb::block!(bx.enable_non_blocking()).ok();
    bx
}
"#;

fn can_config_file(cfg: Option<&CanModuleConfig>, pclk1: u32) -> String {
    let bitrate = cfg.map(|c| c.bitrate).unwrap_or(500_000);
    let btr = can_btr(bitrate, pclk1);
    CAN_TMPL
        .replace("{BITRATE}", &bitrate.to_string())
        .replace("{PCLK1}", &pclk1.to_string())
        .replace("{BTR}", &format!("0x{btr:08X}"))
}

const USART_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const BAUDRATE: u32 = {BAUD};
const DATA_BITS: u8 = {DATA}; // 8, 9
const PARITY: char = '{PARITY}'; // 'N' None, 'O' Odd, 'E' Even
const STOP_BITS: u8 = {STOP}; // 1, 2
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    serial::{self, Config, Serial, StopBits},
};

fn get_config() -> serial::Config {
    let mut config = Config::default().baudrate(BAUDRATE.bps());

    if DATA_BITS == 8 {
        config = config.wordlength_8bits();
    } else if DATA_BITS == 9 {
        config = config.wordlength_9bits();
    }

    if PARITY == 'N' {
        config = config.parity_none();
    } else if PARITY == 'O' {
        config = config.parity_odd();
    } else if PARITY == 'E' {
        config = config.parity_even();
    }

    if STOP_BITS == 1 {
        config = config.stopbits(StopBits::STOP1);
    } else if STOP_BITS == 2 {
        config = config.stopbits(StopBits::STOP2);
    }

    config
}

pub fn init(
    usart: pac::USART{N},
    pins: impl serial::Pins<pac::USART{N}>,
    afio: &mut afio::Parts,
    clocks: &Clocks,
) -> (serial::Tx<pac::USART{N}>, serial::Rx<pac::USART{N}>) {
    Serial::new(usart, pins, &mut afio.mapr, get_config(), clocks).split()
}
"#;

fn usart_config_file(n: u8, cfg: Option<&UsartModuleConfig>) -> String {
    let baud = cfg.map(|c| c.baud_rate).unwrap_or(115_200);
    let data = cfg.map(|c| c.data_bits).unwrap_or(8);
    let parity = match cfg.map(|c| c.parity) {
        Some(Parity::Odd) => 'O',
        Some(Parity::Even) => 'E',
        _ => 'N',
    };
    let stop = match cfg.map(|c| c.stop_bits) {
        Some(StopBits::Two) => 2,
        _ => 1,
    };
    USART_TMPL
        .replace("{N}", &n.to_string())
        .replace("{BAUD}", &baud.to_string())
        .replace("{DATA}", &data.to_string())
        .replace("{PARITY}", &parity.to_string())
        .replace("{STOP}", &stop.to_string())
}

const SPI_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const SPI_MODE: u8 = {MODE}; // 0..=3 (CPOL/CPHA)
const CLOCK_KHZ: u32 = {KHZ};
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    spi::{self, Mode, Phase, Polarity, Spi, Spi{N}NoRemap},
};

fn get_mode() -> Mode {
    match SPI_MODE {
        1 => Mode { polarity: Polarity::IdleLow, phase: Phase::CaptureOnSecondTransition },
        2 => Mode { polarity: Polarity::IdleHigh, phase: Phase::CaptureOnFirstTransition },
        3 => Mode { polarity: Polarity::IdleHigh, phase: Phase::CaptureOnSecondTransition },
        _ => Mode { polarity: Polarity::IdleLow, phase: Phase::CaptureOnFirstTransition },
    }
}

pub fn init<PINS>(
    spi: pac::SPI{N},
    pins: PINS,
    afio: &mut afio::Parts,
    clocks: &Clocks,
) -> Spi<pac::SPI{N}, Spi{N}NoRemap, PINS>
where
    PINS: spi::Pins<Spi{N}NoRemap>,
{
    Spi::spi{N}(spi, pins, &mut afio.mapr, get_mode(), CLOCK_KHZ.kHz(), clocks)
}
"#;

fn spi_config_file(n: u8, cfg: Option<&SpiModuleConfig>) -> String {
    let mode = cfg.map(|c| c.mode).unwrap_or(0);
    let khz = cfg.map(|c| c.clock_hz).unwrap_or(1_000_000) / 1_000;
    SPI_TMPL
        .replace("{N}", &n.to_string())
        .replace("{MODE}", &mode.to_string())
        .replace("{KHZ}", &khz.to_string())
}

const I2C_TMPL: &str = r#"// <<< GENERATED>>>
// Peripheral config (from the Virtual Module) — auto-updated; edit in the module.
const CLOCK_KHZ: u32 = {KHZ}; // <=100 Standard, >100 Fast
// <<< GENERATED END >>>

// Everything below is editable — your changes are preserved on regeneration.
use stm32f1xx_hal::{
    pac,
    prelude::*,
    afio,
    rcc::Clocks,
    i2c::{self, BlockingI2c, Mode as I2cMode},
};

fn get_mode() -> I2cMode {
    if CLOCK_KHZ <= 100 {
        I2cMode::Standard { frequency: CLOCK_KHZ.kHz() }
    } else {
        I2cMode::Fast { frequency: CLOCK_KHZ.kHz(), duty_cycle: i2c::DutyCycle::Ratio2to1 }
    }
}

pub fn init<PINS>(
    i2c: pac::I2C{N},
    pins: PINS,
    afio: &mut afio::Parts,
    clocks: &Clocks,
) -> BlockingI2c<pac::I2C{N}, PINS>
where
    PINS: i2c::Pins<pac::I2C{N}>,
{
    BlockingI2c::i2c{N}(i2c, pins, &mut afio.mapr, get_mode(), *clocks, 1000, 10, 1000, 1000)
}
"#;

fn i2c_config_file(n: u8, cfg: Option<&I2cModuleConfig>) -> String {
    let khz = cfg.map(|c| c.clock_hz).unwrap_or(100_000) / 1_000;
    I2C_TMPL
        .replace("{N}", &n.to_string())
        .replace("{KHZ}", &khz.to_string())
}

/// Append any **missing** helper functions to `file`, after `fn main`, in the
/// user-editable region. Helpers already present (matched by `fn <name>(`) are
/// left untouched so user edits survive every regeneration — only brand-new
/// ones are appended. A section header is inserted once.
pub fn ensure_helper_defs(mut file: String, all_pins: &[&Pin]) -> String {
    let defs = helper_defs(all_pins);
    // A helper is "present" if its `fn <name>` is followed by either `(` (plain
    // fns like `init_adc1`) or `<` (generic fns like `init_spi1<PINS>` /
    // `init_i2c1<PINS>`). Checking only `(` missed the generic ones, so they
    // were re-appended on every regen — the infinite-growth bug. (The config
    // constants the helpers reference live in the regenerated GEN block, not
    // here, so they track the module config live.)
    let missing: Vec<&(String, String)> = defs
        .iter()
        .filter(|(name, _)| {
            !(file.contains(&format!("fn {name}(")) || file.contains(&format!("fn {name}<")))
        })
        .collect();
    if missing.is_empty() {
        return file;
    }

    if !file.ends_with('\n') {
        file.push('\n');
    }
    if !file.contains("── Peripheral init helpers") {
        file.push_str(
            "\n// ── Peripheral init helpers (editable — tweak as needed) ────────────────\n",
        );
    }
    for (_, def) in missing {
        file.push('\n');
        file.push_str(def);
        file.push('\n');
    }
    file
}

// ── Pin helpers ───────────────────────────────────────────────────────────────

struct PinMeta {
    port: char,
    pin_num: u8,
    var: String,
    port_var: String,
    crx: &'static str,
}

fn parse_pin(name: &str) -> Option<PinMeta> {
    let bytes = name.as_bytes();
    if bytes.len() < 3 || bytes[0] != b'P' {
        return None;
    }
    let port = bytes[1] as char;
    if !port.is_ascii_uppercase() {
        return None;
    }
    let pin_num: u8 = name[2..].parse().ok()?;
    let lc = port.to_ascii_lowercase();
    Some(PinMeta {
        port,
        pin_num,
        var: format!("p{}{}", lc, pin_num),
        port_var: format!("gpio{}", lc),
        crx: if pin_num < 8 { "crl" } else { "crh" },
    })
}

fn into_expr(func: &PinFunction, pv: &str, crx: &str) -> String {
    match func {
        PinFunction::GpioInput => format!("into_floating_input(&mut {pv}.{crx})"),
        PinFunction::GpioOutput => format!("into_push_pull_output(&mut {pv}.{crx})"),
        PinFunction::AdcChannel { .. } => format!("into_analog(&mut {pv}.{crx})"),
        PinFunction::TimerPwm { .. } => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        PinFunction::UsartTx(_) | PinFunction::UsartCk(_) => {
            format!("into_alternate_push_pull(&mut {pv}.{crx})")
        }
        PinFunction::UsartRx(_) | PinFunction::UsartCts(_) => {
            format!("into_floating_input(&mut {pv}.{crx})")
        }
        PinFunction::UsartRts(_) => format!("into_push_pull_output(&mut {pv}.{crx})"),
        PinFunction::SpiSck(_) | PinFunction::SpiMosi(_) => {
            format!("into_alternate_push_pull(&mut {pv}.{crx})")
        }
        PinFunction::SpiNss(_) => format!("into_push_pull_output(&mut {pv}.{crx})"),
        PinFunction::SpiMiso(_) => format!("into_floating_input(&mut {pv}.{crx})"),
        PinFunction::I2cScl(_) | PinFunction::I2cSda(_) => {
            format!("into_alternate_open_drain(&mut {pv}.{crx})")
        }
        PinFunction::Mco => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        PinFunction::CanTx => format!("into_alternate_push_pull(&mut {pv}.{crx})"),
        PinFunction::CanRx => format!("into_floating_input(&mut {pv}.{crx})"),
        PinFunction::UsbDm | PinFunction::UsbDp => {
            "// USB — configured automatically by the USB peripheral".to_owned()
        }
        PinFunction::SwdIo | PinFunction::SwdClk => {
            "// SWD — active by default, no config needed".to_owned()
        }
        PinFunction::Unset => unreachable!(),
    }
}

fn is_comment_expr(expr: &str) -> bool {
    expr.trim_start().starts_with("//")
}

/// Returns `true` for pins that are driven (output / alternate-output).
/// These get a `&mut` prefix so the binding is immediately usable as a
/// mutable reference without a later `&mut var` at each call site.
fn needs_mut_ref(func: &PinFunction) -> bool {
    matches!(
        func,
        PinFunction::GpioOutput
            | PinFunction::TimerPwm { .. }
          //  | PinFunction::UsartTx(_)
            | PinFunction::UsartCk(_)
            | PinFunction::UsartRts(_)
           //cd  | PinFunction::SpiSck(_)
           // | PinFunction::SpiMosi(_)
           // | PinFunction::SpiNss(_)
           // | PinFunction::I2cScl(_)
           // | PinFunction::I2cSda(_)
            | PinFunction::Mco
            | PinFunction::CanTx
    )
}
