//! STM32WBA family codegen — `embassy-stm32` in BLOCKING style.
//!
//! Why embassy and not a classic `stm32wbaxx-hal`: there is no mature blocking
//! HAL crate for the STM32WBA series, but `embassy-stm32` genuinely supports it
//! and its GPIO API (`Output::new` / `Input::new`) is small and stable. Used
//! WITHOUT the async executor — `embassy_stm32::init()` hands back the
//! peripheral singletons and the `Output`/`Input` wrappers work fine under
//! `cortex_m_rt::entry`, so the generated project fits the same base
//! `Cargo.toml` (cortex-m-rt + panic-halt + the `hal_dep` line) every other
//! `RustEmbedded` family uses.
//!
//! Scope of v1: GPIO input/output pins get real, compiling init; bus / analog
//! pins (USART/SPI/I2C/ADC/…) are bound to their raw `embassy_stm32`
//! peripheral singleton (`let pa9 = p.PA9;`) with the role in the comment —
//! ready to hand to `embassy_stm32::usart::Uart::new(...)` etc. Every line
//! round-trips through [`super::parse_main_rs`], so the Pins canvas restores on
//! reopen. Full peripheral-driver generation (like the STM32F1 config files)
//! is a later step.

use super::{mcu_id_marker_line, pin_binding, GEN_BEGIN, GEN_END, USER_TAIL};
use crate::panels::mcu_module::pins::logic::pin::Pin;
use crate::panels::mcu_module::pins::logic::pin_function::PinFunction;

/// Invariant file header (above `GEN_BEGIN`, survives every re-splice).
pub fn invariant_header(mcu_name: &str, mcu_id: &str) -> String {
    format!(
        "// Auto-generated by Embedded IDE\n\
         // MCU: {mcu_name} | HAL: embassy-stm32 (blocking)\n\
         {id}\n\
         #![no_std]\n\
         #![no_main]\n\n\
         use panic_halt as _;\n\
         use cortex_m_rt::entry;\n\n",
        id = mcu_id_marker_line(mcu_id),
    )
}

/// The generated section: gpio `use` items (only when needed), `#[entry]`,
/// `embassy_stm32::init`, and one `let` binding per configured pin. Opens
/// `fn main()` — `USER_TAIL` closes it with the editable loop.
pub fn make_generated_section(mcu_name: &str, pins: &[&Pin]) -> String {
    let configured: Vec<&&Pin> = pins
        .iter()
        .filter(|p| p.selected_function != PinFunction::Unset)
        .collect();

    let any_output = configured
        .iter()
        .any(|p| p.selected_function == PinFunction::GpioOutput);
    let any_input = configured
        .iter()
        .any(|p| p.selected_function == PinFunction::GpioInput);

    // Only import the gpio types actually used (no unused-import warnings).
    let mut imports = Vec::new();
    if any_input {
        imports.push("Input");
        imports.push("Pull");
    }
    if any_output {
        imports.push("Level");
        imports.push("Output");
        imports.push("Speed");
    }
    imports.sort_unstable();
    imports.dedup();
    let use_line = if imports.is_empty() {
        String::new()
    } else {
        format!("use embassy_stm32::gpio::{{{}}};\n", imports.join(", "))
    };

    let mut body = String::new();
    for p in &configured {
        body.push_str(&pin_binding_line(p));
        body.push('\n');
    }
    if body.is_empty() {
        body.push_str("    // No pins configured yet — assign functions on the Pins canvas.\n");
    }

    format!(
        "{GEN_BEGIN}\n\
         {use_line}\n\
         #[entry]\n\
         #[allow(unused_variables, unused_mut)]\n\
         fn main() -> ! {{\n\
         \x20   // {mcu_name}\n\
         \x20   // Clock: set via embassy_stm32::Config (RCC). Default shown;\n\
         \x20   // see the Clock tab target + embassy-stm32 docs to raise SYSCLK.\n\
         \x20   let p = embassy_stm32::init(Default::default());\n\
         \n\
         {body}\
         {GEN_END}\n",
    )
}

/// Re-splice only the generated section of an existing `main.rs`, preserving
/// the user tail. Rebuilds from scratch when the markers are gone.
pub fn splice_section(existing: &str, new_section: &str, mcu_name: &str, mcu_id: &str) -> String {
    if let (Some(begin), Some(end_start)) = (existing.find(GEN_BEGIN), existing.find(GEN_END)) {
        let end = end_start + GEN_END.len();
        let after = existing[end..].trim_start_matches('\n');
        format!("{}{}\n{}", &existing[..begin], new_section, after)
    } else {
        format!(
            "{}{}\n{}",
            invariant_header(mcu_name, mcu_id),
            new_section,
            USER_TAIL,
        )
    }
}

/// One pin's `let` line. Output → `let mut pXY = Output::new(...)`; input →
/// `let pXY = Input::new(...)`; anything else → the raw singleton `let pXY =
/// p.PXY;` (hand to a driver). The trailing `// <Label>` is what
/// [`super::parse_main_rs`] reads back.
fn pin_binding_line(p: &Pin) -> String {
    let func = &p.selected_function;
    let base = p.name.to_ascii_lowercase(); // "PB5" → "pb5"
    let var = pin_binding(&base, func, &p.custom_label);
    let singleton = &p.name; // embassy singleton = "PB5"
    let label = func.label();
    match func {
        PinFunction::GpioOutput => format!(
            "    let mut {var} = Output::new(p.{singleton}, Level::Low, Speed::Low); // {label}"
        ),
        PinFunction::GpioInput => {
            format!("    let {var} = Input::new(p.{singleton}, Pull::None); // {label}")
        }
        // Bus / analog / debug: bind the raw peripheral, ready for its driver.
        _ => format!("    let {var} = p.{singleton}; // {label}"),
    }
}

#[cfg(test)]
mod tests {
    use super::super::parse_main_rs;
    use super::*;
    use crate::panels::mcu_module::pins::logic::pin::Pin;

    fn pin(name: &str, func: PinFunction) -> Pin {
        Pin {
            name: name.into(),
            number: 0,
            reserved: false,
            available_functions: vec![func.clone()],
            selected_function: func,
            custom_label: String::new(),
        }
    }

    /// A GPIO output + input + a bus pin generate compiling embassy code, and
    /// every configured pin round-trips through the shared parser.
    #[test]
    fn generates_and_round_trips_pins() {
        let pb5 = pin("PB5", PinFunction::GpioOutput);
        let pc13 = pin("PC13", PinFunction::GpioInput);
        let pa9 = pin("PA9", PinFunction::UsartTx(1));
        let refs: Vec<&Pin> = vec![&pb5, &pc13, &pa9];
        let section = make_generated_section("STM32WBA55CG", &refs);

        // Shape: gpio imports (both kinds), embassy init, one line per pin.
        assert!(section.contains("use embassy_stm32::gpio::{Input, Level, Output, Pull, Speed};"));
        assert!(section.contains("embassy_stm32::init(Default::default())"));
        assert!(section.contains(
            "let mut pb5_out = Output::new(p.PB5, Level::Low, Speed::Low); // GPIO Output"
        ));
        assert!(section.contains("let pc13_in = Input::new(p.PC13, Pull::None); // GPIO Input"));
        assert!(section.contains("let pa9_usart1_tx = p.PA9; // USART1  TX"));

        // Round-trip: the full file's GEN block parses back to the same pins,
        // INCLUDING the `let mut` output (the parser tweak this relies on).
        let file = format!(
            "{}{section}\n{USER_TAIL}",
            invariant_header("STM32WBA55CG", "stm32wba55cg")
        );
        let parsed = parse_main_rs(&file);
        assert!(parsed.contains(&("PB5".into(), PinFunction::GpioOutput)));
        assert!(parsed.contains(&("PC13".into(), PinFunction::GpioInput)));
        assert!(parsed.contains(&("PA9".into(), PinFunction::UsartTx(1))));
    }

    /// No configured pins → no gpio import, a placeholder comment, still valid.
    #[test]
    fn empty_config_omits_imports() {
        let section = make_generated_section("STM32WBA55CG", &[]);
        assert!(!section.contains("use embassy_stm32::gpio"));
        assert!(section.contains("No pins configured yet"));
        assert!(section.contains("fn main() -> !"));
    }

    /// Splice replaces only the GEN block, keeping the user tail.
    #[test]
    fn splice_preserves_user_tail() {
        let v1 = format!(
            "{}{}\n{USER_TAIL}",
            invariant_header("X", "x"),
            make_generated_section("X", &[])
        );
        let edited = v1.replace(
            "// Your main loop code here.",
            "// Your main loop code here.\n        my_custom();",
        );
        let pb5 = pin("PB5", PinFunction::GpioOutput);
        let v2 = splice_section(
            &edited,
            &make_generated_section("X", &[&pb5]),
            "X",
            "x",
        );
        assert!(v2.contains("my_custom();")); // user edit survived
        assert!(v2.contains("Output::new(p.PB5")); // new pin present
    }
}
