//! Persist virtual modules to a one-line `// @modules <ron>` marker in
//! `main.rs`, parsed back on project open — a lossless round-trip of the full
//! module state (config + connections + data models), mirroring the `@clock`
//! marker. RON serialises to a single line (newlines in data models are
//! escaped), so it fits in a comment.

use super::VirtualModule;

/// Marker prefix for the modules comment line.
pub const MODULES_TAG: &str = "// @modules";

/// The `// @modules <ron>` line for `modules`, or `None` when there are none.
pub fn marker_line(modules: &[VirtualModule]) -> Option<String> {
    if modules.is_empty() {
        return None;
    }
    let ron = ron::to_string(modules).ok()?;
    Some(format!("{MODULES_TAG} {ron}"))
}

/// Parse the `// @modules …` line from a saved `main.rs` back into modules.
/// Returns an empty vec when the marker is absent or unparseable.
pub fn parse_from_source(source: &str) -> Vec<VirtualModule> {
    source
        .lines()
        .find_map(|l| {
            let rest = l.trim_start().strip_prefix(MODULES_TAG)?;
            ron::from_str::<Vec<VirtualModule>>(rest.trim_start()).ok()
        })
        .unwrap_or_default()
}

/// Refresh the `@modules` marker in `code` so it reflects `modules` (placed just
/// after the header's first line). Removes the marker when there are no modules.
pub fn with_marker(code: &str, modules: &[VirtualModule]) -> String {
    let stripped = strip_marker(code);
    match marker_line(modules) {
        Some(line) => insert_after_first_line(&stripped, &line),
        None => stripped,
    }
}

fn strip_marker(code: &str) -> String {
    let Some(start) = code.find(MODULES_TAG) else {
        return code.to_owned();
    };
    let end = code[start..]
        .find('\n')
        .map(|i| start + i + 1)
        .unwrap_or(code.len());
    let mut s = String::with_capacity(code.len());
    s.push_str(&code[..start]);
    s.push_str(&code[end..]);
    s
}

fn insert_after_first_line(code: &str, line: &str) -> String {
    match code.find('\n') {
        Some(i) => format!("{}{}\n{}", &code[..=i], line, &code[i + 1..]),
        None => format!("{code}\n{line}\n"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::panels::mcu_module::modules::{
        Connection, ModuleConfig, ModuleKind, ModuleSignal, UsartModuleConfig,
    };

    fn sample() -> VirtualModule {
        let mut cfg = UsartModuleConfig::new(1);
        cfg.baud_rate = 9600;
        cfg.rx_model = "pub struct R {\n    pub t: f32,\n}".into(); // multi-line on purpose
        VirtualModule {
            id: "gi_usart_1".into(),
            kind: ModuleKind::GenericInterfaceUsart,
            name: "GI_USART1".into(),
            pos: (12.0, 34.0),
            config: ModuleConfig::Usart(cfg),
            connections: vec![
                Connection { signal: ModuleSignal::Tx, mcu_pin: 30 },
                Connection { signal: ModuleSignal::Rx, mcu_pin: 31 },
            ],
        }
    }

    #[test]
    fn marker_round_trips_through_source() {
        let modules = vec![sample()];
        let line = marker_line(&modules).unwrap();
        assert!(line.starts_with(MODULES_TAG));
        assert!(!line.contains('\n'), "marker must be a single line");

        let source = format!("// Auto-generated\n{line}\n#![no_std]\n");
        let parsed = parse_from_source(&source);
        assert_eq!(parsed, modules, "lossless round-trip");
    }

    #[test]
    fn with_marker_inserts_and_is_idempotent() {
        let modules = vec![sample()];
        let base = "// Auto-generated by Embedded IDE\n// MCU: x\n#![no_std]\n".to_owned();
        let once = with_marker(&base, &modules);
        assert!(once.contains(MODULES_TAG));
        // Re-applying keeps exactly one marker (no growth).
        let twice = with_marker(&once, &modules);
        assert_eq!(twice.matches(MODULES_TAG).count(), 1);
        assert_eq!(once, twice);
    }

    #[test]
    fn with_marker_removes_when_empty() {
        let with = with_marker("// hdr\n#![no_std]\n", &[sample()]);
        let without = with_marker(&with, &[]);
        assert!(!without.contains(MODULES_TAG));
        assert_eq!(without, "// hdr\n#![no_std]\n");
    }
}
