#!/usr/bin/env python3
"""Harvest embassy's per-peripheral clock mux tables from stm32-metapac.

The Clock tab lets a user pick a source for a peripheral's kernel clock
(USART1SEL, I2C1SEL, ADCSEL, ...). To emit that as embassy config we need three
names per selector, and NONE of them is guessable:

    config.rcc.mux.usart1sel = mux::Usart1sel::HSI;
                     ^field         ^enum      ^variant

The field is not the enum: on WBA, `usart2sel` and `usart3sel` both use
`Usartsel`, and `i2c2sel`/`i2c4sel` both use `I2c1sel`. Deriving one from the
other produces code that names a type which does not exist.

So the table is HARVESTED from the same data embassy itself generates from —
`stm32-metapac`'s register IR — rather than written by hand. Run this whenever
the metapac version moves; the output is committed so a build needs no registry
access.

    python scripts/harvest-rcc-mux.py [path-to-stm32-metapac]
"""

import glob
import os
import re
import sys

OUT = os.path.join(
    "src", "panels", "mcu_module", "codegen", "rcc_mux_data.rs"
)

# IDE family key -> metapac RCC register version.
#
# Only families whose version is UNAMBIGUOUS by name are listed. `stm32g0` is
# deliberately absent: metapac splits it into `rcc_g0x0` and `rcc_g0x1` (the
# value line vs the rest) and the choice is per chip, not per family — emitting
# either one for every G0 would be a guess, and a guess here is a compile error
# in the user's project.
FAMILIES = {
    "stm32f2": "f2",
    "stm32f4": "f4",
    "stm32f7": "f7",
    "stm32g4": "g4",
    "stm32l4": "l4",
    "stm32wba": "wba",
}


def find_metapac(argv):
    if len(argv) > 1:
        return argv[1]
    home = os.environ.get("USERPROFILE") or os.environ.get("HOME") or ""
    pattern = os.path.join(home, ".cargo", "registry", "src", "*", "stm32-metapac-*")
    hits = sorted(glob.glob(pattern))
    if not hits:
        sys.exit("stm32-metapac not found in the cargo registry; pass its path")
    return hits[-1]


def harvest(path):
    """(field, enum, [variants]) for every `*sel` field in one RCC version."""
    text = open(path, encoding="utf-8", errors="replace").read()

    enums = {}
    for m in re.finditer(
        r'Enum \{\s*name: "([A-Za-z0-9_]+)",.*?variants: &\[(.*?)\n            \],',
        text,
        re.S,
    ):
        # Name AND register value: the value is what a mux input index has to
        # agree with, and nothing guarantees the file lists them in value order.
        enums[m.group(1)] = re.findall(
            r'name: "([A-Za-z0-9_]+)",\s*description:.*?value: (\d+)', m.group(2), re.S
        )

    out = []
    seen = set()
    for m in re.finditer(
        r'Field \{\s*name: "([a-z0-9_]+sel)".*?enumm: Some\(\s*"([A-Za-z0-9_]+)",?\s*\)',
        text,
        re.S,
    ):
        field, enum = m.group(1), m.group(2)
        # A field can appear in several register banks; the first wins, as it
        # does in embassy's own BTreeSet.
        if field in seen:
            continue
        variants = enums.get(enum)
        # DISABLE is skipped by embassy's generator too — it is the "off" state,
        # not a clock source.
        variants = [(n, v) for (n, v) in (variants or []) if n != "DISABLE"]
        if not variants:
            continue
        seen.add(field)
        out.append((field, enum, variants))
    return out


def main():
    root = find_metapac(sys.argv)
    regs = os.path.join(root, "src", "registers")
    if not os.path.isdir(regs):
        sys.exit("no src/registers under " + root)

    lines = [
        "//! Per-peripheral clock mux tables, harvested from stm32-metapac.",
        "//!",
        "//! GENERATED by `scripts/harvest-rcc-mux.py` — do not edit by hand.",
        "//! Source: " + os.path.basename(root),
        "//!",
        "//! Each entry is one selector embassy exposes as",
        "//! `config.rcc.mux.<field> = mux::<Enum>::<VARIANT>;`. The enum is NOT",
        "//! derivable from the field name (WBA's `usart2sel` uses `Usartsel`),",
        "//! which is why this is data rather than a rule.",
        "",
        "use super::rcc_mux::MuxField;",
        "",
    ]

    total = 0
    for family in sorted(FAMILIES):
        version = FAMILIES[family]
        path = os.path.join(regs, "rcc_" + version + ".rs")
        if not os.path.isfile(path):
            sys.exit("missing " + path)
        fields = harvest(path)
        total += len(fields)
        const = family.upper().replace("STM32", "STM32_")
        lines.append("/// `rcc_%s` — %d selectors." % (version, len(fields)))
        lines.append("static %s: &[MuxField] = &[" % const)
        for field, enum, variants in fields:
            vs = ", ".join("(%s, \"%s\")" % (v, n) for (n, v) in variants)
            lines.append(
                '    MuxField { field: "%s", enum_name: "%s", variants: &[%s] },'
                % (field, enum, vs)
            )
        lines.append("];")
        lines.append("")

    lines.append("/// Every family this IDE can emit peripheral clock muxes for.")
    lines.append("pub static RCC_MUX: &[(&str, &[MuxField])] = &[")
    for family in sorted(FAMILIES):
        const = family.upper().replace("STM32", "STM32_")
        lines.append('    ("%s", %s),' % (family, const))
    lines.append("];")
    lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s — %d families, %d selectors" % (OUT, len(FAMILIES), total))


if __name__ == "__main__":
    main()
