//! Linux udev rules for the debug probes and USB-serial adapters this IDE talks
//! to (bottom-panel Tools tab → "USB probe udev rules").
//!
//! # Why this exists
//!
//! On Linux a raw USB device node is root-only, so `probe-rs`, `dfu-util`,
//! `openocd` and `espflash` can SEE a probe and still fail to open it. Every one
//! of those projects ships its own rules file, and between them they cover their
//! own hardware — but the IDE already knows exactly which VID:PIDs it looks for
//! ([`crate::dfu::KNOWN_PROGRAMMERS`]), so generating the file from that table is
//! the only way it cannot drift from what the app actually enumerates.
//!
//! # What the IDE does and does not do
//!
//! Installing into `/etc/udev/rules.d` needs root, which a GUI app must not try
//! to acquire behind the user's back. So: the IDE WRITES the file somewhere the
//! user owns and SHOWS the one command that installs it. The privileged step
//! stays a deliberate act.

use std::path::PathBuf;

/// Conventional file name. The `69-` prefix puts it before systemd's own
/// `70-uaccess.rules`, which is what makes `TAG+="uaccess"` take effect.
pub const RULES_FILE_NAME: &str = "69-embedded-ide.rules";

/// Where the IDE stages the generated file: the same per-user folder as the MCU
/// registry and the crash log. Never `/etc` — that write needs root.
pub fn staged_rules_path() -> PathBuf {
    crate::panels::mcu_module::registry::user_config_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join(RULES_FILE_NAME)
}

/// Split a `"0483:3748"` catalogue key into `(vid, pid)`. `None` for a malformed
/// entry, so one bad row can't produce a rule that silently matches nothing.
fn split_vid_pid(key: &str) -> Option<(&str, &str)> {
    let (vid, pid) = key.split_once(':')?;
    let ok = |s: &str| s.len() == 4 && s.chars().all(|c| c.is_ascii_hexdigit());
    (ok(vid) && ok(pid)).then_some((vid, pid))
}

/// Is this catalogue entry reached over a serial port (`/dev/ttyUSB*`,
/// `/dev/ttyACM*`) rather than raw USB? Those need a `tty` rule as well, which
/// is what lets the Serial tab and `espflash` open the port without waiting for
/// a `dialout` group change to take effect at the next login.
fn is_serial_kind(kind: &str) -> bool {
    matches!(kind, "USB-Serial" | "ESP32")
}

/// The complete rules file.
///
/// Access is granted the way probe-rs' own rules do it — `TAG+="uaccess"` plus
/// `MODE="0660", GROUP="plugdev"` — deliberately, rather than a simpler
/// world-writable `MODE="0666"`:
/// - `uaccess` is the correct mechanism on any systemd system: the device is
///   ACL'd to whoever is logged in at the seat, and to nobody else;
/// - the group line is the fallback for systems without it, where the user does
///   have to be in `plugdev`.
///
/// Matching the ecosystem's convention beats inventing a more permissive one.
pub fn rules_text() -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# {RULES_FILE_NAME} — generated by Embedded IDE {}\n\
         #\n\
         # Non-root access to the debug probes, DFU bootloaders and USB-serial\n\
         # adapters this IDE enumerates. Without it probe-rs / dfu-util / openocd\n\
         # / espflash can see a device but not open it (\"Permission denied\").\n\
         #\n\
         # Install:\n\
         #   sudo cp {RULES_FILE_NAME} /etc/udev/rules.d/\n\
         #   sudo udevadm control --reload-rules && sudo udevadm trigger\n\
         # Then UNPLUG AND REPLUG the device — udev applies rules at plug time.\n\
         #\n\
         # uaccess = the logged-in user gets an ACL (systemd). The plugdev group\n\
         # is the fallback for systems without it; add yourself with\n\
         #   sudo usermod -aG plugdev $USER\n\
         #\n\
         # Generated from the IDE's own programmer catalogue — regenerate it from\n\
         # the Tools tab after an update rather than editing it by hand.\n\n",
        env!("CARGO_PKG_VERSION"),
    ));

    let mut last_kind = "";
    for &(key, name, kind) in crate::dfu::KNOWN_PROGRAMMERS {
        let Some((vid, pid)) = split_vid_pid(key) else {
            continue;
        };
        if kind != last_kind {
            out.push_str(&format!("# -- {kind} --\n"));
            last_kind = kind;
        }
        out.push_str(&format!(
            "# {name}\n\
             SUBSYSTEM==\"usb\", ATTR{{idVendor}}==\"{vid}\", ATTR{{idProduct}}==\"{pid}\", \
             MODE=\"0660\", GROUP=\"plugdev\", TAG+=\"uaccess\"\n"
        ));
        if is_serial_kind(kind) {
            out.push_str(&format!(
                "SUBSYSTEM==\"tty\", ATTRS{{idVendor}}==\"{vid}\", ATTRS{{idProduct}}==\"{pid}\", \
                 MODE=\"0660\", GROUP=\"dialout\", TAG+=\"uaccess\"\n"
            ));
        }
    }
    out
}

/// Write the generated rules to [`staged_rules_path`]. Returns the path so the
/// caller can show it.
pub fn write_staged_rules() -> std::io::Result<PathBuf> {
    let path = staged_rules_path();
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&path, rules_text())?;
    Ok(path)
}

/// The exact shell command that installs a staged file. One line, so it can be
/// copied in one go — a two-step instruction is a step someone will skip.
pub fn install_command(staged: &std::path::Path) -> String {
    format!(
        "sudo cp '{}' /etc/udev/rules.d/ && sudo udevadm control --reload-rules && sudo udevadm trigger",
        staged.display()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vid_pid_split_rejects_malformed_keys() {
        assert_eq!(split_vid_pid("0483:3748"), Some(("0483", "3748")));
        assert_eq!(split_vid_pid("0483-3748"), None);
        assert_eq!(split_vid_pid("483:3748"), None); // must be 4 hex digits
        assert_eq!(split_vid_pid("0483:374g"), None);
        assert_eq!(split_vid_pid(""), None);
    }

    /// The whole point of generating: every device the IDE enumerates must have
    /// a rule. A catalogue entry added later without a rule is the failure this
    /// guards — the probe would show up in Scan USB and refuse to open.
    #[test]
    fn every_catalogued_programmer_gets_a_rule() {
        let text = rules_text();
        for &(key, name, _) in crate::dfu::KNOWN_PROGRAMMERS {
            let (vid, pid) = split_vid_pid(key).unwrap_or_else(|| panic!("bad key {key} ({name})"));
            let expected =
                format!("ATTR{{idVendor}}==\"{vid}\", ATTR{{idProduct}}==\"{pid}\"");
            assert!(text.contains(&expected), "no usb rule for {name} ({key})");
        }
    }

    /// Pin the EXACT text of one rule. udev fails silently on a malformed line —
    /// no error, the device simply stays root-only — so the syntax is asserted
    /// rather than eyeballed. `ATTR` (not `ATTRS`) for `SUBSYSTEM=="usb"`: the
    /// usb_device node carries idVendor itself, and that is the form probe-rs'
    /// own rules use. A tty node does NOT, hence `ATTRS` in the serial rule.
    #[test]
    fn a_usb_rule_has_exactly_the_expected_syntax() {
        let text = rules_text();
        let stlink_v2 = "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0483\", ATTR{idProduct}==\"3748\", \
                         MODE=\"0660\", GROUP=\"plugdev\", TAG+=\"uaccess\"";
        assert!(
            text.lines().any(|l| l == stlink_v2),
            "no line exactly matching the ST-Link v2 rule; got:\n{}",
            text.lines()
                .filter(|l| l.contains("3748"))
                .collect::<Vec<_>>()
                .join("\n")
        );
        // Every non-comment, non-blank line must be a rule (a stray line would
        // make udev reject the whole file).
        for l in text.lines().filter(|l| !l.trim_start().starts_with('#')) {
            if l.trim().is_empty() {
                continue;
            }
            assert!(l.starts_with("SUBSYSTEM=="), "not a rule line: {l}");
            assert!(l.ends_with("TAG+=\"uaccess\""), "rule not terminated: {l}");
        }
    }

    #[test]
    fn serial_adapters_also_get_a_tty_rule() {
        let text = rules_text();
        // CH340 — the classic ESP32 / Arduino clone adapter.
        assert!(text.contains("SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"1a86\", ATTRS{idProduct}==\"7523\""));
        // An ST-Link is raw USB only; a tty rule for it would be noise.
        let stlink_tty =
            "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"0483\", ATTRS{idProduct}==\"3748\"";
        assert!(!text.contains(stlink_tty), "ST-Link should have no tty rule");
    }

    /// The header has to carry the install steps: the file outlives this UI, and
    /// whoever finds it in a year needs to know what to do with it.
    #[test]
    fn header_explains_how_to_install() {
        let text = rules_text();
        assert!(text.starts_with("# 69-embedded-ide.rules"));
        assert!(text.contains("/etc/udev/rules.d/"));
        assert!(text.contains("udevadm control --reload-rules"));
        assert!(text.contains("UNPLUG AND REPLUG"));
    }

    #[test]
    fn install_command_quotes_the_path() {
        let cmd = install_command(std::path::Path::new("/home/a b/.config/x.rules"));
        assert!(cmd.contains("'/home/a b/.config/x.rules'"), "{cmd}");
        assert!(cmd.contains("udevadm trigger"), "{cmd}");
    }
}
